### ISSUE TITLE
Every line is trying to send in new message. Too many requests (caused by SendMessageRequest)

### ISSUE THREAD

**Issue by DiMiTriFrog** [LonamiWebs/Telethon#4058] opened 2023-03-11 11:50 UTC
*  When i'm trying to send message, the api is splitting in more than one message.: 
* When i remove all break lines is working and sending the message. Why can't add breaklines ? I tried with <br>, <br /> (both didn't work) and with /n (same result than actual message).
* I'm having this issue only with Telethon, with other py telegram bot libraries is working right, but i need to send from real telegram user
* The account is not flagged, when i remove the break lines in the string, is sending the message.
* I think the api is splitting the string in various messages and Telegram thinks is flood. 
* My string has 12 break lines.

**Code that causes the issue**
```python
the_str = f"""Title

Some text

Some more text

Some end"""
await client.send_message(event.chat_id, str(the_str), parse_mode="html")`
...

```

**Traceback**
```
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by SendMessageRequest)

```

**Comment by Lonami** [comment] 2023-03-12 16:14
I tried your code with some modifications:

```python
import asyncio
import os
from telethon import TelegramClient

async def main():
    the_str = f"""Title

Some text

Some more text

Some end"""
    async with TelegramClient(..., os.getenv('TG_ID'), os.getenv('TG_HASH')) as bot:
        await bot.send_message('lonami', the_str, parse_mode='html')

asyncio.run(main())
```

I received this message from the bot account I used:

![image](https://user-images.githubusercontent.com/6297805/224557446-a1edc4a6-cc42-463e-b5e4-90700e190410.png)

Therefore, I can't reproduce your issue with the code you posted.

Please create a minimal reproducible example (similar to mine, just a few lines long) which exhibits the behavior you're describing. Otherwise I really can't even attempt to debug the issue.

I will close this issue assuming the error is somewhere in your code and not the library. But I will gladly reopen the issue if you can provide faulty code, using the latest version.

As for the peer flood, that happens when the account is limited and cannot send many messages. Probably related to the fact it's sending "many messages when there are multiple lines" for you. But I really suspect either your code or a library you're using is messing with the results.

**Closed as completed by Lonami** 2023-03-12 16:14 UTC
