### ISSUE TITLE
Telethon events.NewMessage is stalling when await’ing for invoked requests.

### ISSUE THREAD

**Issue by StamatisTiniakos** [LonamiWebs/Telethon#3149] opened 2021-09-03 11:46 UTC
I run the following simple script from the command line to print on my console new messages on telegram public groups and channels.

```
import configparser
from telethon.errors import SessionPasswordNeededError
from telethon import TelegramClient, events, sync
from telethon.tl.functions.messages import (GetHistoryRequest)
from telethon.tl.types import (
PeerChannel
)

api_id = 'xxxxxx'
api_hash = 'xxxxxxxxxxxxxxxxxxxxxxx'

# Here you define the target channel that you want to listen to:
input_channels = ('https://t.me/xxxxxx','https://t.me/xxxx','https://t.me/xxxxxxx')

print(input_channels)

#create a client
client = TelegramClient('anon', api_id, api_hash)

# Listen to messages from target channel 
@client.on(events.NewMessage(chats=input_channels)) 
async def newMessageListener(event):
    # Get message text 

    message_dict = event.message.to_dict()
    sender = await event.get_sender()
    sender_dict = sender.to_dict()

    print(sender_dict)
    print("----------------")
    print(message_dict)
    print("----------------")



with client: 
    client.run_until_disconnected()
```

I have noticed that sometimes when new messages are posted they are not printed on the console. They are printed only after I press a key on the keyboard (e.g. Enter).

I wonder if this has something to do with the following part of the script:

sender = await event.get_sender()

Any idea what I am doing wrong and how to fix it?

**Comment by Lonami** [comment] 2021-09-03 11:50
Nothing in the code you posted should be blocking the code. Please enable `logging` (https://docs.telethon.dev/en/latest/basic/updates.html) to find out about issues in the code. Closing under the assumption the code works as intended.

**Closed by Lonami** 2021-09-03 11:50 UTC
