### ISSUE TITLE
Telegram has stopped sending SMS code.

### ISSUE THREAD

**Issue by Subachev** [LonamiWebs/Telethon#3835] opened 2022-05-25 13:07 UTC
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
self.telethon_client = TelegramClient(
            StringSession(),
            self.device_data.api_id,
            self.device_data.api_hash,
            proxy=self.proxy_data.tg_proxy,
            device_model=self.device_data.device_model,
            app_version=self.device_data.app_version,
            system_version=self.device_data.system_version,
        )
        self.telethon_client.start(
            first_name=first_name,
            last_name=last_name,
            phone=lambda: phone_number,
            force_sms=True,
            max_attempts=2,
        )
...
```

For a long time everything worked fine, but yesterday we ran into a problem. SMS messages stopped being sent from telegram. At all.
We used various proxies, api_id/api_hash, phone numbers (mostly +7 and a little +1).
There is no error or warning. Everything is as usual. But telegram just doesn't send SMS.

We tried to send the SMS code immediately using the send_code_request method. The result is the same.

**Comment by Lonami** [comment] 2022-05-25 13:33
The library is making the requests to Telegram for it to send the SMS. If Telegram isn't sending the SMS even after it was requested to do so, it probably has its own reasons (avoid spam), and Telethon can likely do nothing about it.

**Comment by w1ld32** [comment] 2022-05-27 06:24
I have been trying to solve this problem for 3 days. But to no avail. Codes come from official apps, but not from the telethon(

**Comment by Lonami** [comment] 2022-05-27 09:27
This might be Telegram's anti-spam measures. There is not much that can be done by Telethon to mitigate this.

**Comment by w1ld32** [comment] 2022-05-27 09:51
The codes do not even come to the official Telegram client on the PC. Not for any major third-party client (Telegram X, X Chat). The problem is definitely not in the Thelethon, but I want to solve it somehow (

**Comment by ZE1L** [comment] 2022-06-03 21:42
works fine for me, uninstall telethon and reinstall it

**Comment by Lonami** [comment] 2022-09-20 12:13
Closing since this is not something Telethon can fix. It's just the way Telegram decides to work. Telethon is making the necessary requests for Telegram to send the code, but if it still doesn't, well, then Telegram is simply ignoring the request Telethon made.

**Closed as completed by Lonami** 2022-09-20 12:13 UTC

**Comment by dumpload** [comment] 2022-09-29 11:52
Try to send SMS verification or verification code, it may be sent successfully, the possibility is very small, this problem may be the problem of tg node

**Comment by Lonami** [comment] 2022-10-30 17:59
Also duplicate of #3822.

**Comment by Lonami** [comment] 2022-10-30 17:59
And #3697, and #3719, and probably a few others.

**Comment by Lonami** [comment] 2023-02-20 21:30
On the 10th of February, Telegram sent this message to those with an application registered on https://my.telegram.org:

> Telegram API Update. Hello ▒▒▒▒,. Thank you for contributing to the open Telegram ecosystem by developing your app, ▒▒▒▒. 
> 
> Please note that due to recent updates to Telegram's handling of SMS and the integration of new SMS providers like Firebase, we are changing the way login codes are handled in third-party apps based on the Telegram API.
> 
> Starting on 18.02.2023, users logging into third-party apps will only be able to receive login codes via Telegram. It will no longer be possible to request an SMS to log into your app – just like when logging into Telegram's own desktop and web clients.
> 
> Exactly like with the Telegram Desktop and Web apps, if a user doesn’t have a Telegram account yet, they will need to create one first using an official mobile Telegram app.
> 
> We kindly ask you to update your app’s login and signup interfaces to reflect these changes before they go live on 18.02.2023 at 13:00 UTC.
> 
> This change will not significantly affect users since, according to our research, the vast majority of third-party app users also use official Telegram apps. In the coming months, we expect to offer new tools for third-party developers that will help streamline the login process.

What this means for Telethon:

* You can no longer use Telethon to sign up.
* You will only be able to receive the code via Telegram. Not SMS.

Why has Telegram done this? Probably in an attempt to reduce spam, and also because sending SMS is likely not cheap at their scale. Another possible reason may be security. We cannot know. Telethon cannot do anything to bypass these new limitations, and won't try playing tricks to do so.

**Comment by yhilgjff** [comment] 2025-02-16 14:50
This bug is still valid. Glad to see such a great team of developer(s) constantly regressing!

**Comment by Qwerty-Space** [comment] 2025-02-16 20:30
> This bug is still valid. Glad to see such a great team of developer(s) constantly regressing!

It's not a bug. It's a Telegram restriction on third-party apps: 
https://github.com/LonamiWebs/Telethon/issues/3835#issuecomment-1437572165

**Comment by Eloren1** [comment] 2025-06-19 22:55
It helped to turn on and turn off the VPN back and forth, and when I turned it off again, it finally sent the code

**Comment by yhilg** [comment] 2025-06-23 18:09
> It helped to turn on and turn off the VPN back and forth, and when I turned it off again, it finally sent the code

Thanks for the input however this has not fixed the situation over here.
