### ISSUE TITLE
Get response not working

### ISSUE THREAD

**Issue by Eikosa** [LonamiWebs/Telethon#4124] opened 2023-06-02 21:42 UTC
### Code that causes the issue

```python
async with tpp.conversation(chat_id) as conv:
    # <you> Hi!
    await conv.send_message('Hi!')

    # <usr> Hello!
    hello = await conv.get_response()

    # <you> Please tell me your name
    await conv.send_message('Please tell me your name')

    # <usr> ?
    name = (await conv.get_response()).raw_text

    while not any(x.isalpha() for x in name):
        # <you> Your name didn't have any letters! Try again
        await conv.send_message("Your name didn't have any letters! Try again")

        # <usr> Human
        name = await conv.get_response().raw_text

    # <you> Thanks Human!
    await conv.send_message('Thanks {}!'.format(name))
```

### Expected behavior

The get_response part should work

### Actual behavior

get_response code does nothing,
![image](https://github.com/LonamiWebs/Telethon/assets/20538090/f274f0df-f2dd-48b9-a0e4-c9b241e39e8a)

### Traceback

no error

### Telethon version

1.28.5

### Python version

3.10.7

### Operating system (including distribution name and version)

Ubuntu 22

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by AtlantisDe** [comment] 2023-06-03 00:55
same..... events.NewMessage Not working
```python
import asyncio
from telethon import TelegramClient,events, sync

async def main():
    client = TelegramClient(session_name, api_id, api_hash)
    await client.start()
    print("Client created and connected")

    @client.on(events.NewMessage(pattern='.*'))
    async def handle_new_message(event):
        print(f"Received new message from {event.chat_id}: {event.message.message}")

    print("Start listening for new messages...")
    await client.run_until_disconnected()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by Lonami** [comment] 2023-06-03 09:25
From your screenshot, it seems both the "Hi!" and the "wwww…" come from the same account (one being controlled by Telethon, and the other sent from a official client).

`get_response` gets an incoming message, not an outgoing one. Assuming this is the problem, I will close the issue.

> events.NewMessage Not working

That's a different problem entirely. You would need to open a new issue for that. Although it is very, very unlikely it's broken, or a lot more people would be complaining, so I might just close that immediately if I cannot reproduce the issue.

**Closed as completed by Lonami** 2023-06-03 09:25 UTC

**Comment by Eikosa** [comment] 2023-06-03 11:56
How can I use this also for outgoign messages?
