### ISSUE TITLE
Telethon is frozen

### ISSUE THREAD

**Issue by andr-04** [LonamiWebs/Telethon#256] opened 2017-09-22 14:25 UTC
Hello.

I use telethon version 0.13.4 (`TelegramClient` class) and periodically it becomes not responding on the next _invoke_ request.

Here the log when it works:
```
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Handling bad server salt
DEBUG:telethon.network.mtproto_sender:Handling bad server salt
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
```

Next, on the outside event I execute the request
`client(ResolveUsernameRequest(username))`
and it hangs for a very long time (and hangs other very important parts of code). But in result (after for about 30 minutes) I see in log the following:
```
DEBUG:telethon.telegram_bare_client:Server disconnected us. Reconnecting...
DEBUG:telethon.network.mtproto_sender:Handling container
DEBUG:telethon.network.mtproto_sender:Processing TLObject updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
DEBUG:telethon.network.mtproto_sender:Processing TLObject updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
DEBUG:telethon.network.mtproto_sender:Processing TLObject updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
DEBUG:telethon.network.mtproto_sender:Processing TLObject updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Lost request will be skipped.
DEBUG:telethon.network.mtproto_sender:Handling container
DEBUG:telethon.network.mtproto_sender:Processing TLObject updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
DEBUG:telethon.network.mtproto_sender:Processing TLObject updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
DEBUG:telethon.network.mtproto_sender:Processing TLObject updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates
DEBUG:telethon.network.mtproto_sender:Processing TLObject updateShort#78d4dec1 update:Update date:int = Updates
DEBUG:telethon.network.mtproto_sender:Processing TLObject updateShortMessage#914fbf11 flags:# out:flags.1?true mentioned:flags.4?true media_unread:flags.5?true silent:flags.13?true id:int user_id:int message:string pts:int pts_count:int date:int fwd_from:flags.2?MessageFwdHeader via_bot_id:flags.11?int reply_to_msg_id:flags.3?int entities:flags.7?Vector<MessageEntity> = Updates
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
```
and so on. The main part at the beginning: `DEBUG:telethon.telegram_bare_client:Server disconnected us. Reconnecting...`. What the reason of it and why it requires long time to determine it?

**Comment by Lonami** [comment] 2017-09-22 14:26
I just pushed `v0.13.5` to PyPi, give it a go?

**Comment by Lonami** [comment] 2017-09-22 14:26
I'm actually writing the change log right now :)

**Comment by andr-04** [comment] 2017-09-22 14:27
Ok, I'll update right now.

Does it fixed or you'd like to see new logs just?

**Comment by Lonami** [comment] 2017-09-22 14:28
Well I *think* I've fixed quite a few stuff with this background thread and I tried my best to debug it, and it indeed is better than before, but I can't reach every use case.

**Comment by andr-04** [comment] 2017-09-22 14:29
Thanks! I'll watch again.

**Comment by Lonami** [comment] 2017-09-22 14:31
Change log is now ready, as usual on the [releases tab](https://github.com/LonamiWebs/Telethon/releases/tag/v0.13.5), feel free to take a look.

**Comment by andr-04** [comment] 2017-09-22 14:49
I've reproduced the bug again. Now it is frozen, I suppose after some time it will reports "Reconnecting...".

**Comment by Lonami** [comment] 2017-09-22 14:52
No idea, this bug seems new. It's usually been crashing rather than just freezing forever. Do you think the reason could be this?:
> ```
> DEBUG:telethon.network.mtproto_sender:Lost request will be skipped.
> ```

**Comment by andr-04** [comment] 2017-09-22 14:57
No ideas. Now it doesn't reconnected yet, but in logs the following:
```
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Reading request response
DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Reading request response
DEBUG:telethon.network.mtproto_sender:Handling RPC result
DEBUG:telethon.network.mtproto_sender:Reading request response
```

`client(ResolveUsernameRequest(username))` hangs the all again.

May be you suggest the debug approach?

**Comment by Lonami** [comment] 2017-09-22 14:59
It's just strange, could you post a minimal reproducible example of what you're doing exactly? A single request like `ResolveUsernameRequest` has never failed to me so I'm sort of clueless.

**Comment by andr-04** [comment] 2017-09-22 15:07
I don't know how to do that (I'm not sure that cut out example will reproduce it) and what can raise it. I use phone calls and asyncio as well. Updates from update_handle I send to asyncio.run_coroutine_threadsafe and it works as expected.

It will be easy to debug it by myself if I know the place. I new in Telethon.

**Comment by Lonami** [comment] 2017-09-22 15:09
Hit me up [on Telegram](https://t.me/Lonami) if you want such help when debugging the library. If you can fix this bug, I would be more than thankful.

**Comment by andr-04** [comment] 2017-09-26 21:19
I suppose this bug has disappeared in new version. Thanks!

**Comment by Lonami** [comment] 2017-09-26 21:26
Nice, wonder what was triggering it exactly.

**Comment by i-paya** [comment] 2017-12-03 16:02
Hi 
I have this issue too .
I use 0.15.5.7
![issue](https://user-images.githubusercontent.com/31750044/33527144-b783e634-d860-11e7-9a45-2c9356a54479.png)

**Comment by Lonami** [comment] 2017-12-03 16:17
Can you reproduce? On what line does the program halt?

**Comment by i-paya** [comment] 2017-12-03 17:36
@Lonami  what do you mean?

**Comment by Lonami** [comment] 2017-12-03 17:37
Use a debugger and when it hangs pause it so it tells you on which line it's stopped.

**Comment by i-paya** [comment] 2017-12-03 17:59
![screenshot_1](https://user-images.githubusercontent.com/31750044/33528042-324a19e2-d870-11e7-9c7f-742b55f8c60d.png)
 and this is my code:

```python
def update_handler(update):
	if isinstance(update,UpdateShortMessage):
		print (update)
client.add_update_handler(update_handler)
input ("")```

**Comment by Lonami** [comment] 2017-12-03 17:59
No clue then.

**Comment by Lonami** [comment] 2017-12-03 18:00
I don't know.

**Comment by i-paya** [comment] 2017-12-03 18:03
when it has a few dialogs there is no problem .
but now it has too many channels.

**Comment by pioneerit** [comment] 2017-12-28 12:39
@Lonami I believe that `reconnect` logic missing debug messages in logs. Probably it is frozen somewhere there with the locks.

@i-paya, I made a small workaround. As I have a Thread doing some job, I give access to the client in the thread and doing next:
```
 while True:
                if client.is_connected():
                    sleep(60)
                else:
                    os._exit(1)
```

When process exits supervisor or docker just restarts everything. And it is fine in my case.

**Comment by Lonami** [comment] 2018-01-15 10:06
There's been a few changes regarding updates so @i-paya please follow the examples on http://telethon.readthedocs.io/en/latest/extra/basic/working-with-updates.html. Closing.

**Closed by Lonami** 2018-01-15 10:06 UTC
