### ISSUE TITLE
Can not send  sms code after Feb.20.

### ISSUE THREAD

**Issue by yangdiweif** [LonamiWebs/Telethon#4040] opened 2023-02-20 17:48 UTC
my code:

await self.client.send_code_request(phone, force_sms=True)

I don't know what updates by telegram team,  but can not send  sms code by telethon after Feb.20.

**Comment by Lonami** [comment] 2023-02-20 21:26
Closing as a duplicate of #3835.

**Closed as completed by Lonami** 2023-02-20 21:26 UTC
