### ISSUE TITLE
Messages, createdby the library are not searchable.

### ISSUE THREAD

**Issue by socketpair** [LonamiWebs/Telethon#1602] opened 2020-10-17 18:44 UTC
I've written a simple program that adds a message to a private channel. It works. But for some reason, messages created by the library are not searchable! Neither by get_messages(search=....) nor in Android/Linux client at least.

Interesting effect 2:
After adding (using the library) a message with text, say, `TheRoot`, if you go to the official client (Android or Linux) and add the same message in the same channel by typing it on the keyboard, it will also be unsearchable!

Effect 3:
if I add a message using mobile client, and the add the same message using the library, only first one will be searchable.

**Comment by Lonami** [comment] 2020-10-17 19:04
Sending with Telethon and searching with both Telegram Desktop and Telegram X, in all cases the message shows fine for me. Are you sure you're sending/searching the message in the right chat? Are you sure this has nothing to do with the application's cache? Are you sure you copied the text `"TheRoot"` exactly with no strange characters in between? Try using raw API directly with [`SendMessageRequest`](https://tl.telethon.dev/methods/messages/send_message.html). If the issue still occurs with that after checking al the other things, the issue is with Telegram and not the library. If it does not occur there, it might be an issue in the library, but closing under the assumption it's not.

**Comment by socketpair** [comment] 2020-10-17 19:08
Please reopen.
1. Yes, I'm sure because mesage apperas in correct channel (asserted in mobile and desktop clients)
2. I'm unsure, but the effect of searching is the same on mobile, telethon and desktop versions
3. Yes, I'm sure.
4. Please provide an example...
5. If it is a bug in Telegram (not in the libray), why bug happens only when sending messages using the library ?

I will provide sample program in a few minutes

**Comment by Lonami** [comment] 2020-10-17 19:11
1. A chat upgraded to a megagroup will be "merged" in the official client but are in fact two different things which may be messing things up.
2. Try closing the application, clearing cache, and searching.
3. -
4. There's an example in the linked page.
5. No idea, Telegram is weird.

I still don't think there's anything here to fix but whatever.

**Comment by socketpair** [comment] 2020-10-17 19:13
It is reproducible with erased messages and not reproduced with new ones! Seems case of reproduction is more comples. Please wait for.

**Comment by socketpair** [comment] 2020-10-17 19:14
The entity I send to is a simple private channel.

**Comment by socketpair** [comment] 2020-10-17 19:15
I can give you admin rights to the channel in order you to check that bug exists. Unfotunatelly it reproduces with SOME messages.

**Comment by socketpair** [comment] 2020-10-17 19:28
So, how to trigger:
1. create an empty private channel (I create it using desktop client)
2. Create simple message with text "XXX" using Telethon
3. Erase message in Desktop client. (yes, important!)
4. Send the same message "XXX" using Telethon
5. client.get_messages(channel, search="XXX") will give empty result
6. client.get_messages(channel) will show the message created at step 4.
7. Desktop will not find the message  by text "XXX"

P.S. its a Telegram bug. I reproduced it using desktop only client. Sorry. Please close. It will be nice if you tell me where to report.

**Comment by socketpair** [comment] 2020-10-17 20:53
Sorry twice. It's not easy to spot the bug. Please open again :( The program that reproduces:

```python
#!/usr/bin/python3
import random

from telethon.sync import TelegramClient

api_id = 100500
api_hash = 'aaaaabbbcbcccdd....'

with TelegramClient('name', api_id, api_hash) as client:
    channel = client.get_entity('telegram.me/joinchat/sOmePrivateCHaT')
    TAG = f'#x{random.randrange(0, 2 ** 64)}y'
    msg1 = client.send_message(channel, TAG)
    print('searching first:', [i.text for i in client.get_messages(channel, search=TAG, limit=10)])
    client.delete_messages(channel, msg1)

    msg2 = client.send_message(channel, TAG)
    print('searching second:', [i.text for i in client.get_messages(channel, search=TAG, limit=10)])
    client.delete_messages(channel, msg2)
```

Anyway. Here is a program that triggers bug.

**Comment by socketpair** [comment] 2020-10-17 21:11
Another program:

```python
#!/usr/bin/python3
import random

from telethon.sync import TelegramClient

api_id = 234234
api_hash = 'fb88234234234234234234290a4748'

with TelegramClient('name', api_id, api_hash) as client:
    channel = client.get_entity('telegram.me/joinchat/AAHGhjGHJgkjqVIxhyQ')
    TAG = f'#x{random.randrange(0, 2 ** 64)}y'

    print(TAG)
    client.get_messages(channel, search=TAG, limit=10)  # <============= comment it, and search will work(!)
    client.send_message(channel, TAG)
    print([i.text for i in client.get_messages(channel, search=TAG, limit=10)])
```

Interestingly. only channel-local search is broken. Global search works OK.

**Comment by Lonami** [comment] 2020-10-17 22:23
I will test this with raw API another time (or feel free to do so yourself, it's simply using getHistory and messages.search from https://telethon.dev). If it can reproduce with that, it's an issue with Telegram and not the library.

**Comment by Lonami** [comment] 2020-10-18 10:57
Nevermind, tested with Telegram Desktop instead, but the results are the same. So this seems like an issue with Telegram and not the library.

**Closed by Lonami** 2020-10-18 10:57 UTC

**Comment by Lonami** [comment] 2020-10-18 19:03
For what is worth, the search works fine after a certain period of time, though I have not tried to get an accurate measure of this. Probably varies.
