### ISSUE TITLE
Sending Parameters in Stripe Payments using Inputmediainvoice

### ISSUE THREAD

**Issue by nikhilbharadwaj005** [LonamiWebs/Telethon#1686] opened 2021-01-31 07:32 UTC
Hi, 

I used the exact file name **payment.py** provided in **telethon_examples** folder.

Stripe in india says

![image](https://user-images.githubusercontent.com/48579448/106377137-da2a2d80-63c0-11eb-84aa-30689da6b068.png)

In, #1470 ,in generate_invoice method, the **inputmediainvoice** has a key **provider_data** where it should contain the data required by payment_provider. 
![image](https://user-images.githubusercontent.com/48579448/106377191-60467400-63c1-11eb-8429-e12f855789d2.png)

So, I tried 3 ways:

Method-1:

I directly used the payment.py and tested with my stripe test token.

Method-2:

I sent the types.DataJSON of invoice to provider_data as below:

```
def generate_invoice(price_label: str, price_amount: int, currency: str, title: str,
                     description: str, payload: str, start_param: str) -> types.InputMediaInvoice:
    price = types.LabeledPrice(label=price_label, amount=price_amount)  # label - just a text, amount=10000 means 100.00
    invoice = types.Invoice(
        currency=currency,  # currency like USD
        prices=[price],  # there could be a couple of prices.
        test=True,  # if you're working with test token, else set test=False.
        # More info at https://core.telegram.org/bots/payments
        
        # params for requesting specific fields
        name_requested=True,
        phone_requested=False,
        email_requested=True,
        shipping_address_requested=True,

        # if price changes depending on shipping
        flexible=False,

        # send data to provider
        phone_to_provider=True,
        email_to_provider=True
    )

    return types.InputMediaInvoice(
        title=title,
        description=description,
        invoice=invoice,
        payload=payload.encode('UTF-8'),  # payload, which will be sent to next 2 handlers
        provider=provider_token,
  #----------------------------------------------------------------------------------------------------------------------------------
        provider_data=types.DataJSON(invoice.to_json()),
  #----------------------------------------------------------------------------------------------------------------------------------
        # data about the invoice, which will be shared with the payment provider. A detailed description of
        # required fields should be provided by the payment provider.

        start_param=start_param,
        # Unique deep-linking parameter. May also be used in UpdateBotPrecheckoutQuery
        # see: https://core.telegram.org/bots#deep-linking
        # it may be the empty string if not needed

    )
```

Method-3:
I set the data manually
```
def generate_invoice(price_label: str, price_amount: int, currency: str, title: str,
                     description: str, payload: str, start_param: str) -> types.InputMediaInvoice:
    price = types.LabeledPrice(label=price_label, amount=price_amount)  # label - just a text, amount=10000 means 100.00
    invoice = types.Invoice(
        currency=currency,  # currency like USD
        prices=[price],  # there could be a couple of prices.
        test=True,  # if you're working with test token, else set test=False.
        # More info at https://core.telegram.org/bots/payments
        
        # params for requesting specific fields
        name_requested=True,
        phone_requested=False,
        email_requested=True,
        shipping_address_requested=True,

        # if price changes depending on shipping
        flexible=False,

        # send data to provider
        phone_to_provider=True,
        email_to_provider=True
    )

    return types.InputMediaInvoice(
        title=title,
        description=description,
        invoice=invoice,
        payload=payload.encode('UTF-8'),  # payload, which will be sent to next 2 handlers
        provider=provider_token,
  #----------------------------------------------------------------------------------------------------------------------------------
        provider_data=types.DataJSON("{\"name\":\"john\",\"shipping\":{\"name\":\"Jenny Rosen\",\"address\":{\"line1\":\"510 Townsend St\",\"postal_code\":\"98140\",\"city\":\"San Francisco\",\"state\":\"CA\",\"country\":\"US\"}}}"),
  #----------------------------------------------------------------------------------------------------------------------------------
        # data about the invoice, which will be shared with the payment provider. A detailed description of
        # required fields should be provided by the payment provider.

        start_param=start_param,
        # Unique deep-linking parameter. May also be used in UpdateBotPrecheckoutQuery
        # see: https://core.telegram.org/bots#deep-linking
        # it may be the empty string if not needed

    )
```

**None of the above methods sends the shipping data to stripe.**

Here is the event log from stripe test data, the request doesn't contain the address and name.

![image](https://user-images.githubusercontent.com/48579448/106377607-32aefa00-63c4-11eb-853b-2b9b844e1924.png)

**Comment by Lonami** [comment] 2021-01-31 08:21
cc @apepenkov

**Comment by apepenkov** [comment] 2021-01-31 08:58
Afaik, for stripe it should be left empty. I mean, I use Stripe, leave it empty and all works great.

**Comment by nikhilbharadwaj005** [comment] 2021-01-31 09:32
Hi @apepenkov ,

I tried with the empty value also, but it didn't work.

For international transaction in stripe for india, stripe requests need that extra parameters like name and address, 

Initially, I thought there is problem with stripe but I made an LMS where my stripe is working fine for international transactions.

if there anyway that can modify the data before sending the data to stripe using telethon..?

**Comment by apepenkov** [comment] 2021-01-31 09:37
I have no idea about provider data, you'll have to invistigate yourself.

**Comment by nikhilbharadwaj005** [comment] 2021-01-31 09:39
Okay @apepenkov , Thanks.

**Comment by Lonami** [comment] 2021-01-31 09:40
Thanks for checking. The answer may be in the linked documentation page https://stripe.com/docs/india-accept-international-payments.

I suggest you `import json` and try with something like the following:

```python
import json
...
provider_data=types.DataJSON(json.dumps(dict(
  name='Jenny Rosen',
  address={
    'line1': '510 Townsend St',
    'postal_code': '98140',
    'city': 'San Francisco',
    'state': 'CA',
    'country': 'US',
  },
))),
```

Or maybe you need to combine intent and customer, not sure. Please keep this open until you resolve the issue, and let us know when/if you do, to help others as well.

**Comment by Lonami** [comment] 2021-04-20 21:20
Bump @nikhilbharadwaj005, did you get it to work? If so, how?

**Comment by xArcticWolfx** [comment] 2021-05-03 15:01
Hey guys, I'm currently facing the same problem - Stripe doesn't receive any shipment/optional data at all.

I've tried all the options above. Any updates on that problem?

Cheers!

**Comment by Lonami** [comment] 2021-05-03 16:09
No new information as far as I know. @xArcticWolfx have you tried https://github.com/LonamiWebs/Telethon/issues/1686#issuecomment-770354437? Any results with that? Perhaps you spot something in the linked stripe docs that we may be missing?

You could also try to find the source for a bot that does this, so we can check what info they're passing.

**Comment by xArcticWolfx** [comment] 2021-05-03 16:29
> No new information as far as I know. @xArcticWolfx have you tried [#1686 (comment)](https://github.com/LonamiWebs/Telethon/issues/1686#issuecomment-770354437)? Any results with that? Perhaps you spot something in the linked stripe docs that we may be missing?
> 
> You could also try to find the source for a bot that does this, so we can check what info they're passing.

Ya I'm running into a problem with that one:
`TypeError: <telethon.tl.types.DataJSON object at 0x0000023E0274F550> is not JSON serializable`

Unfortunately I'm rly not used to json serialization and barely manage to troubleshoot it - been testing a ton of options tho and even the one's which don't throw an error don't seem to work. Might be on Stripes side tho? Thanks for your quick reply!

**Comment by nikhilbharadwaj005** [comment] 2021-05-03 18:01
> Bump @nikhilbharadwaj005, did you get it to work? If so, how?

No @Lonami, I tried but nothing worked..

**Comment by Lonami** [comment] 2021-05-03 18:18
> Ya I'm running into a problem with that one:
> `TypeError: <telethon.tl.types.DataJSON object at 0x0000023E0274F550> is not JSON serializable`

That error is a different story and should not be caused by the code I posted.

**Comment by GlaedrWolf** [comment] 2021-05-03 22:03
> > Ya I'm running into a problem with that one:
> > `TypeError: <telethon.tl.types.DataJSON object at 0x0000023E0274F550> is not JSON serializable`
> 
> That error is a different story and should not be caused by the code I posted.

You're right, your code works outside of `InputInvoiceMessageContent`, but it won't get accepted as `provider_data`
I'll update you in here if I find something out.

**Comment by Lonami** [comment] 2021-05-04 12:12
Thank you both for looking into it. As I said, our best bet may be looking at the code of some existing bot which integrates with Stripe (but I don't know of any such bot). Second best option is digging into Stripe docs, or maybe one could get support elsewhere.

**Comment by Lonami** [comment] 2022-01-24 12:48
I'm going to close this issue, since I'm unlikely to look into this any time soon, and raw API behaviour cannot really be "fixed" or documented by Telethon (oftentimes, Telegram names are the only documentation there is).

**Closed by Lonami** 2022-01-24 12:48 UTC

**Comment by Kylmakalle** [comment] 2023-09-21 11:31
Still an issue. https://bugs.telegram.org/c/32465
