### ISSUE TITLE
Proxy not hide ip

### ISSUE THREAD

**Issue by rnyPlanet** [LonamiWebs/Telethon#1567] opened 2020-09-22 07:55 UTC
https://github.com/LonamiWebs/Telethon/issues/1503
a similar problem, tried a lot of options and nothing helped

**Comment by Lonami** [comment] 2020-09-22 08:11
Duplicate of #1503. There is no need to have two issues for the same problem open.

**Closed by Lonami** 2020-09-22 08:11 UTC
