### ISSUE TITLE
The @client.on(events.NewMessage(chats='XXXXX') Event does not trigger after few messages, if we minimize of maximize the cmd prompy , it process the message.

### ISSUE THREAD

**Issue by Ikram24817** [LonamiWebs/Telethon#1527] opened 2020-08-18 14:02 UTC
The @client.on(events.NewMessage(chats='XXXXX') Event does not trigger after few messages, if we minimize OR maximize the cmd prompt , where the .py file is running , then it processes the message.

I need the event to run when a new message is delivered in the telegram channel, it is fine but intermittently doesnt work, if we if we minimize OR maximize the cmd prompt , where the .py file is running , then it processes the message

Please help.

The Code is 
`api_id = 444444
api_hash = '2qwcsads434454512112bdsasadsad333e'

# use full phone number including + and country code
phone = '+919933333333'
username = '@XXXXXXXXXX'

client = TelegramClient(username, api_id, api_hash)

# assert client.connect()
print("Client Created")

@client.on(events.NewMessage(chats='XXXXX'))

async def myfunc(event):
    print('{}'.format(event))
    print('The Message is --------->')
    print('\n')

    print('{}'.format(event.raw_text))
    print('\n')
    print('{}'.format(event.message.message))
    print('{}'.format(event.message.date))
    if 'hello' in event.raw_text:
        event.reply('hi!')

client.start()
client.run_until_disconnected()`

**Comment by Ikram24817** [comment] 2020-08-18 17:14
Hi,
If we add  client.idle() to the events.NewMessage code , Will that work.

What will client.idle() do ?

Please help.
Ikram

**Comment by Lonami** [comment] 2020-08-18 19:58
This report is not clear at all. Telethon only uses the console via `logging` or when interactively running `start()`. Closing since it's unlikely that the terminal is the cause.

**Closed by Lonami** 2020-08-18 19:58 UTC
