### ISSUE TITLE
Signing in with telethon makes it kick me out of my account

### ISSUE THREAD

**Issue by GEOEGII555** [LonamiWebs/Telethon#4253] opened 2023-11-12 19:34 UTC
### Code that causes the issue

```python
import telethon
client = telethon.client.TelegramClient(...)
client.start()
client.run_until_disconnected()
```

### Expected behavior

Should just do nothing except for connecting to Telegram.

### Actual behavior

After 5 seconds, I get logged out from Telegram on all of my devices. I log back in, and it kicks me out again after some time, even if I stop Telethon.

At first I thought that it was a Telegram bug, but then I waited a day and it stopped. Stopped, until I tried to use Telethon again. After I tried using it again, the same stuff started happening - kicking me out of my account.

### Telethon version

1.32.0

### Python version

Python 3.11.6

### Operating system (including distribution name and version)

Windows 11 Pro

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-11-12 20:15
Duplicate of #4051. Nothing the library can do about it.

**Closed as completed by Lonami** 2023-11-12 20:15 UTC
