### ISSUE TITLE
Fatal error handling updates (this is a bug in Telethon, please report it)

### ISSUE THREAD

**Issue by simbadmorehod** [LonamiWebs/Telethon#4017] opened 2023-01-07 07:08 UTC
```

ERROR:telethon.client.updates:Fatal error handling updates (this is a bug in Telethon, please report it)
 Traceback (most recent call last):
   File "/home/donald/donald_project/donald/venv/lib/python3.8/site-packages/telethon/client/updates.py", line 282, in _update_loop
     diff = await self(get_diff)
   File "/home/donald/donald_project/donald/venv/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
     return await self._call(self._sender, request, ordered=ordered)
  File "/home/donald/donald_project/donald/venv/lib/python3.8/site-packages/telethon/client/users.py", line 84, in _call
     result = await future
telethon.errors.rpcerrorlist.DateEmptyError: Date empty (caused by GetDifferenceRequest)
```

**Comment by Lonami** [comment] 2023-01-07 12:13
Please follow the issue template. It makes it easier for me to make sure everything is in order.

Please install master with:

```
pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip
```

and configure `logging` with something like this:

```python
import logging
logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s', level=logging.WARNING)
logging.getLogger('telethon.messagebox').setLevel(logging.NOTSET + 1)
```

(You can configure it to your liking, but the `messagebox` level must be as low as possible. If you have multiple `TelegramClient`, please set a different `base_logger='name'` for each in their constructor).

This will print all updates being processed along with the current state of the `MessageBox` (which deals with the updates).

**This log will contain sensitive information**, so only share it with people you trust (or redact it before sharing it). You can [send it to me privately](https://t.me/Lonami) so that I and nobody else can analyze it (please link to this issue, so I know you're not spam).

With it I'll be able to reproduce the issue reliably locally, pinpoint the problem, and fix it.

**Comment by simbadmorehod** [comment] 2023-01-08 10:34
The task will not be easy, but I will try to do everything you ask.

**Comment by simbadmorehod** [comment] 2023-01-08 13:30
I can install in the main bot startup file:

```
import logging
logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s', level=logging.WARNING)
logging.getLogger('telethon.messagebox').setLevel(logging.NOTSET + 1)
```
Then I have a piece of code where I run several different clients `TelegramClient` apparently there I should set `base_logger='name'` argument when creating a client?

**Comment by Lonami** [comment] 2023-01-08 14:36
Yes. If you use multiple `TelegramClient` instances, each one of them needs their own `base_logger` name. Otherwise, the logs will be interleaved and I won't be able to correctly reproduce the issue.

**Comment by simbadmorehod** [comment] 2023-01-10 02:16
Okay, I will create a name as the id of the user that uses this client.

**Comment by Lonami** [comment] 2023-04-06 12:24
Closing as a duplicate of #3974. Please continue discussion there if needed.

**Closed as completed by Lonami** 2023-04-06 12:24 UTC

**Comment by omkarsing6458** [comment] 2023-10-03 01:31
telethon.client.updates: Fatal error handling updates (this is a bug in Telethon v1.28.5, please report it)


Please help me 🙏
