### ISSUE TITLE
Not receiving first message from the channel NewMessage

### ISSUE THREAD

**Issue by EnkhAmar** [LonamiWebs/Telethon#3943] opened 2022-10-04 03:26 UTC
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.tl import types as tTypes
from telethon.sync import TelegramClient, events

api_id = os.environ.get('API_ID')
api_hash = os.environ.get('API_HASH')
client = TelegramClient('anon', api_id=api_id, api_hash=api_hash)

logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s', level=logging.DEBUG)

@client.on(events.NewMessage(chats='CHANNEL_LINK'))
async def channel_listener(event:events.NewMessage.Event):
    message_obj:tTypes.Message = event.message
    msg = message_obj.message
    print("\n\n\n\nPRINT:"msg)
```

**Traceback**
```text

[DEBUG/2022-10-04 10:43:44,936] telethon.network.mtprotosender: Handling update UpdateShort
[DEBUG/2022-10-04 10:43:44,936] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2022-10-04 10:43:49,027] telethon.network.mtprotosender: Handling gzipped data
[DEBUG/2022-10-04 10:43:49,027] telethon.network.mtprotosender: Handling update Updates
[DEBUG/2022-10-04 10:43:49,027] telethon.network.mtprotosender: Receiving items from the network...




[DEBUG/2022-10-04 10:43:57,238] telethon.network.mtprotosender: Handling gzipped data
[DEBUG/2022-10-04 10:43:57,239] telethon.network.mtprotosender: Handling update Updates
[DEBUG/2022-10-04 10:43:57,239] telethon.network.mtprotosender: Receiving items from the network...
[DEBUG/2022-10-04 10:43:57,241] telethon.extensions.messagepacker: Assigned msg_id = 7150482475579864308 to CheckChatInviteRequest (1045328f0)
[DEBUG/2022-10-04 10:43:57,241] telethon.network.mtprotosender: Encrypting 1 message(s) in 40 bytes for sending
[DEBUG/2022-10-04 10:43:57,241] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2022-10-04 10:43:57,242] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2022-10-04 10:43:57,242] telethon.extensions.messagepacker: Assigned msg_id = 7150482475582172200 to MsgsAck (1045327d0)
[DEBUG/2022-10-04 10:43:57,242] telethon.network.mtprotosender: Encrypting 1 message(s) in 60 bytes for sending
[DEBUG/2022-10-04 10:43:57,242] telethon.network.mtprotosender: Encrypted messages put in a queue to be sent
[DEBUG/2022-10-04 10:43:57,242] telethon.network.mtprotosender: Waiting for messages to send...
[DEBUG/2022-10-04 10:43:57,452] telethon.network.mtprotosender: Handling RPC result for message 7150482475579864308
[DEBUG/2022-10-04 10:43:57,452] telethon.network.mtprotosender: Receiving items from the network...




PRINT: test message
```

From the log above, You can see from 10:43:44 to 10:43:49, I sent the first message, the telethon listened to the event but It did not print the message.
The second message sent at 10:43:57 and It printed the message text.

** System Report from my device **
```
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1
  Serial Number (system):	XXXXXXXXXXX
  Hardware UUID:	9E65D614-XXXX-XXXX-XXXX-XXXXXXXXXXX
  Provisioning UDID:	00008103-XXXXXXXXXXXXXXXXXXXXX
  Activation Lock Status:	Disabled
```

**Comment by Lonami** [comment] 2022-10-04 08:55
Closing as a duplicate of #3936.

**Closed as not planned by Lonami** 2022-10-04 08:55 UTC
