### ISSUE TITLE
resolve_bot_file_id returns None for valid file_id

### ISSUE THREAD

**Issue by JKarimi12** [LonamiWebs/Telethon#1613] opened 2020-10-28 08:07 UTC
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
import asyncio

from telegram.ext import Updater, MessageHandler, Filters
from telethon.utils import resolve_bot_file_id, get_input_location
from telethon import TelegramClient

import logging

logging.basicConfig()

api_id = 123
api_hash = 'my_api_hash'
token = 'my_bot_token'


def file_handler(update, context):
    file = update.effective_message.document
    file_size = file.file_size
    file_id = file.file_id
    file_name = file.file_name
    if file_size > 20000000:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        get_file_telethon(file_id, file_name, loop)
    else:
        update.effective_message.document.get_file().download()


def get_file_telethon(file_id, file_name, loop):
    bot = TelegramClient('bot', api_id, api_hash, loop=loop).start(bot_token=token)
    with bot:
        document = resolve_bot_file_id(file_id)
        location = get_input_location(document)
        loop.run_until_complete(bot.download_file(location[1], file_name))


updater = Updater(token, use_context=True)
dp = updater.dispatcher
dp.add_handler(MessageHandler(Filters.document, file_handler))
updater.start_polling()
updater.idle()

...

```

**Traceback**
```
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "**/venv/lib/python3.6/site-packages/telethon/utils.py", line 768, in _get_file_info
    if location.SUBCLASS_OF_ID == 0x1523d462:
AttributeError: 'NoneType' object has no attribute 'SUBCLASS_OF_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "**/venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
    handler.handle_update(update, self, check, context)
  File "**/venv/lib/python3.6/site-packages/telegram/ext/handler.py", line 145, in handle_update
    return self.callback(update, context)
  File **/bot.py", line 24, in file_handler
    get_file_telethon(file_id, file_name, loop)
  File "**/bot.py", line 33, in get_file_telethon
    location = get_input_location(document)
  File "**/venv/lib/python3.6/site-packages/telethon/utils.py", line 762, in get_input_location
    info = _get_file_info(location)
  File "**/venv/lib/python3.6/site-packages/telethon/utils.py", line 771, in _get_file_info
    _raise_cast_fail(location, 'InputFileLocation')
  File "**/venv/lib/python3.6/site-packages/telethon/utils.py", line 139, in _raise_cast_fail
    type(entity).__name__, target))
TypeError: Cannot cast NoneType to any kind of InputFileLocation.

```

**Comment by igerzog** [comment] 2020-10-29 01:05
`message.document.file_id` and `bot_file_id` are not the same thing. According [documentation](https://docs.telethon.dev/en/latest/modules/utils.html#telethon.utils.resolve_bot_file_id) for `resolve_bot_file_id` you should pass a Bot API-style `file_id` as an argument that could be gained with `pack_bot_file_id(file)` operation. If the `file_id` is not valid, `None` is returned instead.

```python
def get_file_telethon(file_id, file_name, loop):
    bot = TelegramClient('bot', api_id, api_hash, loop=loop).start(bot_token=token)
    with bot:
        document = resolve_bot_file_id(file_id)# `file_id` is not a valid Bot API-style `file_id`
        location = get_input_location(document)# so `document` is None 
        ...
```

To get a valid `bot_file_id` upload or send a document somewhere and then use `pack_bot_file_id`.

**Comment by Lonami** [comment] 2020-10-29 08:06
The thing is, this bot file ID should be equivalent to the one given by Telegram's HTTP bot API. However, they may've changed the format over time and Telethon has not been keeping up.

**Comment by Lonami** [comment] 2020-11-07 11:46
Looks like HTTP bot API file IDs have changed quite a bit since I last checked, and now they look like this:

```python
{'file_id': 'AgACAgQAAxkDAAINb1-mgzm1Aq0qm8NLeEB1x6oBqoqHAAKktTEbZJA5UR8JUmE_UfbItIa0J10AAwEAAwIAA20AA435AQABHgQ',
 'file_size': 294,
 'file_unique_id': 'AQADtIa0J10AA435AQAB',
 'height': 32,
 'width': 32}
```

In particular, the `file_unique_id` thing is new (might be something used by tdlib), and the `file_id` looks really long. Their decoded raw data looks like this:

```python
file_unique_id = b"\x01\x00\x00\x00\xb4\x86\xb4']\x00\x00\x00\x8d\xf9\x01\x00"
file_id = b"\x02\x00\x00\x02\x04\x00\x00\x00\x19\x03\x00\x00\ro_\xa6\x839\xb5\x02\xad*\x9b\xc3Kx@u\xc7\xaa\x01\xaa\x8a\x87\x00\x00\xa4\xb51\x1bd\x909Q\x1f\tRa?Q\xf6\xc8\xb4\x86\xb4']\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00m\x00\x00\x00\x8d\xf9\x01\x00\x1e\x04"
```

On the Telethon side, it looks like this:

```python
photo=Photo(
    id=5852867950372042148,
    access_hash=-3965893089195587297,
    file_reference=b'\x03\x00\x00\ro_\xa6\x83\xeaA\xfb\xd6=\xfa\\\xbb\xa0H\x17\xb9\x90\x16\x05f\xe7',
    date=datetime.datetime(2020, 11, 7, 11, 21, 29, tzinfo=datetime.timezone.utc),
    sizes=[
        PhotoSize(
            type='m',
            location=FileLocationToBeDeprecated(
                volume_id=400098100916,
                local_id=129421
            ),
            w=32,
            h=32,
            size=294
        ),
        PhotoStrippedSize(
            type='i',
            bytes=b'\x01  \xabE\x14W9\xec\x05\x14Q@\x05\x14Q@\x05\x14Q@\x1f'
        ),
    ],
    dc_id=4,
    has_stickers=False,
    video_sizes=[
    ]
),
```

With some quick and dirty investigation I figured:

```
4: dc id
36: id
44: access hash
52: volume id
72: local id
```

Part of the file reference is there, so it *might* be there but already have changed when Telethon fetched it. Probably there's more useful bits in there. Anyone is welcome to try and investigate what these parts mean.

**Comment by luckydonald** [comment] 2020-11-07 13:44
I've created https://pypi.org/project/tg-file-id, to solve the same issue, and because I need file_id parsing outside of telethon.
I've got that set up with some unittests and all, so maybe we could actually join forces.
The great thing about that is that it is checking the type of contents which denotes the length, and not trusting the length for the type. In fact they can contain variable length fields (urls and magic datacenter-internal refs), so that current implementation can fail in those cases.

I'll happily give you the required permissions on the repo directly.

**Comment by luckydonald** [comment] 2020-11-07 13:56
@Lonami Sorry for responding with that just as you already put some work into an partial solution of that, I actually got to know about it via your commit feed channel.

**Comment by Lonami** [comment] 2020-11-07 16:31
Cool, we could probably depend on that in Telethon and replace the methods with calls to that library.

**Comment by luckydonald** [comment] 2020-11-07 18:36
Alright, I'll do a pull request for that tomorrow.
Which would be the methods needing replacement?

Should we try to keep the methods in `utils.py` (i.e. keep them as a wrapper for compatibility) ?
Or can we migrate the lib to use the library, and remove the older methods for that?

**Comment by luckydonald** [comment] 2020-11-07 19:34
So far I identified the following functions


From the underlying functions I identified the following callers:
- [ ] _encode_telegram_base64
  - pack_bot_file_id
- [ ] _rle_encode
  - pack_bot_file_id
- [ ] _decode_telegram_base64
  - resolve_bot_file_id
  - resolve_inline_message_id
  - resolve_invite_link
- [ ] _decode_telegram_base64
  - resolve_bot_file_id
- [ ] _decode_telegram_base64 
  - resolve_bot_file_id
- [ ] _decode_telegram_base64
  - resolve_bot_file_id
- [ ] _rle_decode
  - resolve_bot_file_id


That means the following functions have to be kept compatible?
- [ ] pack_bot_file_id
- [ ] resolve_bot_file_id
- [ ] resolve_inline_message_id
- [ ] resolve_invite_link

**Comment by Lonami** [comment] 2020-11-07 20:16
Yes, only the public methods should remain, and those would be simple wrappers around your library.

**Comment by luckydonald** [comment] 2020-11-07 20:22
I wonder if we can do something with the Photosize subclasses in `resolve_bot_file_id`: 
- PhotosizeSourceLegacy, adds `secret` field
- PhotosizeSourceThumbnail, adds file_type, adds `thumbnail_type`  field
- PhotosizeSourceDialogPhotoSmall / PhotosizeSourceDialogPhotoBig, adds `dialog_id` and `dialog_access_hash` fields
- PhotosizeSourceStickersetThumbnail, adds `sticker_set_id` and `sticker_set_access_hash`  fields

https://github.com/luckydonald/telegram_file_id/blob/174e26e3d630e917b4c4d00deab40d6f2ab62344/tg_file_id/file_id.py#L656-L743

**Comment by luckydonald** [comment] 2020-11-07 20:25
So far we seem to use `volume_id` and `location_id` there.
```
location=types.FileLocationToBeDeprecated(
  volume_id=foto_size.volume_id,
  local_id=foto_size.location_local_id,
)
```

**Comment by Lonami** [comment] 2020-11-07 20:46
Shouldn't worry about those distinctions. Just need to behave like it did before, returning a `Photo` or a `Document`.

Something I noticed is the code doesn't have a license, so it would be nice if it did (and if the code is ported from madeline, possibly needs to respect that license or be talked about with the owner). I'm not sure how licenses on dependencies are to be handled, but first things first, it needs a license.

**Comment by luckydonald** [comment] 2020-11-07 21:16
As the original is not licensed I went with `GPL v3+` in the setup.py.

**Comment by danog** [comment] 2020-11-09 09:56
Just FYI, tg-file-decoder is licensed under APLGv3: https://github.com/danog/tg-file-decoder/blob/master/src/type.php#L5

I may have forgotten to add the LICENSE file, but I included the AGPLv3 license notice to all relevant files in the codebase.

**Comment by luckydonald** [comment] 2020-11-09 13:09
@danog 👍

**Comment by luckydonald** [comment] 2020-11-09 14:54
Well, the problem is to my understanding of AGPLv3 that it is not compatible to be used in a MIT project, so I guess that planned improvement is dead now.

**Comment by Lonami** [comment] 2020-11-09 15:15
Does that apply to having a library depend on it? (I haven't done much research into compatible licenses, so I'm not sure). Another option, if necessary, could be to dual license, but of course the owner has to agree to that.

Would this be different if it's an optional dependency so that it's end users the ones that choose to use them?

**Comment by Lonami** [comment] 2021-05-09 00:18
Closing since this is unlikely to be fixed.

**Closed by Lonami** 2021-05-09 00:18 UTC
