### ISSUE TITLE
Album text formatting

### ISSUE THREAD

**Issue by OrIX219** [LonamiWebs/Telethon#3065] opened 2021-05-29 17:00 UTC
When sending message with list of files(in message.media or through 'file' argument) library ignores provided formatting entities. I found out that instead it parses given text to get them.
Is this intentional? Or maybe different images in album can have their own captions and that's the reason? Can something be done with it?

**Comment by Lonami** [comment] 2021-05-29 18:54
Each image can have its own caption, so I'm not sure how the formatting entities should work there. I guess a list of a list of entities but that's weird.

**Comment by Lonami** [comment] 2022-01-24 12:53
Need to review sending albums for v2.

**Comment by Spongie832** [comment] 2022-11-11 11:16
just a little update
The problem is here even if you give to a "file" argument list with one element 
``

**Comment by Lonami** [comment] 2023-04-06 12:38
This is unlikely to happen in the near future so I will be closing the issue. We can reopen it if there's still interest once the time is right.

**Closed by Lonami** 2023-04-06 12:38 UTC
Labels: enhancement

**Comment by oluckyman** [comment] 2024-04-06 08:56
i'm trying to send an album with spoiler and caption with formatting entities.
<img width="406" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/642673/7501bc16-2a98-495b-889e-238c2fe342c8">
It works when I pass only one photo as `file` argument.
```
    await client.send_message(channel, message.message, formatting_entities=message.entities, file=files[0])
```
But if I pass array of photos:
```
    await client.send_message(channel, message.message, formatting_entities=message.entities, file=files)
```
then it sends photos without spoiler and without any formatting:
<img width="448" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/642673/c6d284ad-10ae-43a9-b3e8-ed5f3e586a86">

I understand that this is by design, but what's the workaround? how can I send an album with images hidden behind spoiler and with custom entities in the caption?

**Comment by ndkwa** [comment] 2024-07-07 15:17
same problem
