### ISSUE TITLE
Raise 'RPC results should only happen after a request was sent'

### ISSUE THREAD

**Issue by MuallimCh** [LonamiWebs/Telethon#5] opened 2016-10-02 10:58 UTC
I sometimes get this raise '**RPC results should only happen after a request was sent**' called from updates_thread_method in mtproto_sender.py

This raise when I call send_message couple or more times (say from a list) without a delay. What do you suggest.

**Comment by XyLoNaMiyX** [comment] 2016-10-02 11:05
Yes, I've just stumbled on the same problem. I'm not sure if we can safely ignore this error. I've thought of two options:

1. Keep an internal buffer, and if an RPC result is received when receiving updates, simply ignore it. Then it will be read if a "real" request (one we made) is used.
2. Simply ignore it. Some RPC results don't require a MtProtoRequest (which is why the error is rose, because _some_ do require a request, so it can be marked as `confirmed`). However, I'm not sure if we can simply happily do this, because it may be a result that confirms a request, yet I don't think it's the case: if we sent a request, the updates thread is (should have been) stopped.

**Comment by XyLoNaMiyX** [comment] 2016-10-02 11:34
Could you please test @MuallimCh? I'm not able (neither know how) to reproduce this error. I've tried sending a lot of messages very quick, and found a new bug (with the locks) which is now solved.

**Comment by MuallimCh** [comment] 2016-10-02 11:53
OK, I will tested it and report you.

**Comment by XyLoNaMiyX** [comment] 2016-10-02 11:58
Thanks a lot!

**Comment by MuallimCh** [comment] 2016-10-02 12:01
Yes. It fix, please consider close issue. Thx.

**Comment by XyLoNaMiyX** [comment] 2016-10-02 12:02
Awesome! ^^

**Closed by XyLoNaMiyX** 2016-10-02 12:02 UTC
