### ISSUE TITLE
telethon 1.16.0's force_file cause some TG's features to break

### ISSUE THREAD

**Issue by a-fruity-melon** [LonamiWebs/Telethon#1507] opened 2020-08-01 02:03 UTC
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**

I'm a maintainer of a downstream library named [`Pagermaid-Modify`](https://github.com/xtaodada/PagerMaid-Modify). The library provides a command `-sticker`, which allows users to save any static image as a sticker inside his/her own sticker pack.

This feature works fine for `telethon==1.15.0`, but fails on `telethon==1.16.0`. After a painful investigation, the library's maintainers finally found that `telethon==1.16.0`'s ~~**stream upload feature**~~ `force_file`'s behavior change will result in strange behaviors of Telegram's server, including but not limited to:

- Failure on getting the image's dimension, which directly breaks the whole sticker image's upload process;
- Failure on generating a thumbnail (I guess?) for the image, which results in a black screen if users click on the uploaded image. (Reproducible on some Android devices, and on macOS.)

There's no difference between the binary codes of images uploaded by these two versions of `telethon`, nor between file sizes and names.

![image](https://user-images.githubusercontent.com/52106595/89091204-51fba900-d3da-11ea-9f85-256f5378ad70.png)

[video here](https://t.me/s/share_tmp_file)

Currently, we're fixing this by locking `telethon`'s version:

https://github.com/xtaodada/PagerMaid-Modify/blob/6c005af10433f7c028cc127f17d67c64af61a64b/requirements.txt#L19

But this is not a long-term solution, and we're looking forward to having this fixed from upstream.

Any plan for fixing this?

**Comment by Lonami** [comment] 2020-08-01 12:27
The stream should not be affecting the results in any way. The code simply doesn't unconditionally read the file in memory.

The relevant commit is https://github.com/LonamiWebs/Telethon/commit/de17a19168d2a1c69c7bc431f46b2c47b61787d3, and note that reading from the stream and making the request is unchanged.

**Comment by penn5** [comment] 2020-08-04 10:09
Reproduced, also breaking sticker management in FTG.

**Comment by KenHV** [comment] 2020-08-04 10:14
Can confirm, happens on PPE based bots as well. Forcing Telethon 1.15 fixed it.

**Comment by Lonami** [comment] 2020-08-04 10:30
Can any of you provide a minimal code sample and provide a file that reproduces the issue? Or debug the requests being sent out to spot the differences.

**Comment by Nick80835** [comment] 2020-08-04 10:40
This issue is actually caused by https://github.com/LonamiWebs/Telethon/commit/e12f6c747fea4be9004be139eb51695b78ddd7ed

If you revert it, it works, not sure how that commit broke it.

**Comment by penn5** [comment] 2020-08-04 11:08
Log on 1.15.0: https://del.dog/ftgkang15.txt

Log on 1.16.0: https://del.dog/ftgkang16.txt

**Comment by penn5** [comment] 2020-08-04 11:11
> This issue is actually caused by [e12f6c7](https://github.com/LonamiWebs/Telethon/commit/e12f6c747fea4be9004be139eb51695b78ddd7ed)
> 
> If you revert it, it works, not sure how that commit broke it.

Then the issue could be fixed by making force_file a seperate parameter, or inferring its usage from whether the file is a webp (if fileext != webp, never set force_file)

**Comment by Lonami** [comment] 2020-08-04 11:14
> This issue is actually caused by e12f6c7

Shouldn't leaving `force_document=None` work, then?

**Comment by a-fruity-melon** [comment] 2020-08-09 14:38
@Nick80835 Thank you for the detailed investigation! Sorry for my misleading guess 😢

**Comment by Lonami** [comment] 2020-08-09 16:57
@a-fruity-melon does leaving `force_document` as `None` (the default, or do `force_document=False`) solve your issue? Technically one could argue it was a bug that "forcing a document for a `.webp` still sends a sticker", which now "works correctly", which is why I thought it was appropriated for a minor release.

**Comment by Lonami** [comment] 2020-08-10 14:20
Kinda silly but makes sense Telegram doesn't analyze things that were forced as a file.

**Closed** 2020-08-10 14:19 UTC

**Comment by a-fruity-melon** [comment] 2020-08-11 06:44
> @a-fruity-melon does leaving `force_document` as `None` (the default, or do `force_document=False`) solve your issue? Technically one could argue it was a bug that "forcing a document for a `.webp` still sends a sticker", which now "works correctly", which is why I thought it was appropriated for a minor release.

Yes, it does 🎉 and thank you for the quick response!
