### ISSUE TITLE
Unpredictable result of client.get_messages

### ISSUE THREAD

**Issue by aragentum** [LonamiWebs/Telethon#4025] opened 2023-01-19 13:17 UTC
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Description**

When I run the above code. Sometimes I get some kind of username (**Kuma**...) value and sometimes I don't. Why is this happening?

**Code that causes the issue**

```python
from telethon.sync import TelegramClient
from telethon.sessions import StringSession
from telethon.tl.types import User
...
async def get_messages(channel_username: str, msg_ids: list[int]):
    async with TelegramClient(StringSession(TLG_API_SESSION), int(TLG_API_ID), TLG_API_HASH) as client:
        for message in (await client.get_messages(channel_username, ids=msg_ids)):
            sender: User = await message.get_sender()
            sender_id = sender.id
            sender_username = sender.username
            print(f"{sender_id} | {sender_username}")

if __name__ == '__main__':
    for i in range(10):
        asyncio.run(get_messages('XXXX', [4736101]))

```

**Traceback**

![image](https://user-images.githubusercontent.com/48254535/213448918-3d4f4b95-5588-42e9-a5a8-2a98a429355d.png)

**Comment by Lonami** [comment] 2023-01-19 19:13
It's hard to tell what the problem is without knowing in which channel this occurs.

In any case, I am going to close this under the assumption that Telethon is fetching the sender whenever it can, and not all messages have a sender. I made the wrong decision to return the channel as the sender in channels, but changing that would be a breaking change.

**Closed as completed by Lonami** 2023-01-19 19:13 UTC
