### ISSUE TITLE
Issue:  module 'telethon.tl.types' has no attribute 'TypeMessageReactions'

### ISSUE THREAD

**Issue by Automated-blockchain** [LonamiWebs/Telethon#4121] opened 2023-05-31 09:49 UTC
### Code that causes the issue

```python
from telethon import TelegramClient, events, utils, Button, errors
```

### Expected behavior

It was working in the old version.

### Actual behavior

Now, it seems 'TypeMessageReactions' hasn't been defined in ../telethon/tl/type/__init__.py

### Traceback

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\CMP\myTelethonBot.py", line 18, in <module>
    from telethon import TelegramClient, events, utils, Button, errors
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\__init__.py", line 13, in <module>
    from .users import UserMethods  # Required for everything
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 7, in <module>
    from .. import errors, helpers, utils, hints
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\hints.py", line 5, in <module>
    from .tl import types, custom
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\tl\custom\__init__.py", line 7, in <module>
    from .message import Message
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\tl\custom\message.py", line 14, in <module>
    class Message(ChatGetter, SenderGetter, TLObject):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\tl\custom\message.py", line 203, in Message
    reactions: Optional[types.TypeMessageReactions] = None,
AttributeError: module 'telethon.tl.types' has no attribute 'TypeMessageReactions'

```

### Telethon version

1

### Python version

3.10.2

### Operating system

Windows

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-05-31 15:10
Hmm it should be there:

![image](https://github.com/LonamiWebs/Telethon/assets/6297805/87da2882-147a-4ef2-b477-cf1b90095807)

What does this generated file look like for you in your Telethon install?

**Comment by Lonami** [comment] 2023-06-17 11:08
Closing as I cannot reproduce the issue.

**Closed as completed by Lonami** 2023-06-17 11:08 UTC
