### ISSUE TITLE
Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 76bec211

### ISSUE THREAD

**Issue by lonamiIsLegend** [LonamiWebs/Telethon#4285] opened 2024-01-01 09:41 UTC
### Code that causes the issue

telethon regular code.

### Expected behavior

often when this kind of message appear it means that i need to update telethon. this is not the case now.

### Actual behavior

Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 76bec211

### Telethon version

v1

### Python version

3.7

### Operating system (including distribution name and version)

ubuntu

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2024-01-01 09:50
This can be considered a duplicate of #4240, which is pinned. There is nothing I can do if Telegram adds new types and doesn't bump the layer without publishing them anywhere.

The only solution is to downgrade until it is resolved.

**Closed as completed by Lonami** 2024-01-01 09:50 UTC
