### ISSUE TITLE
Reconnect on lost network interface

### ISSUE THREAD

**Issue by chstem** [LonamiWebs/Telethon#178] opened 2017-07-29 12:03 UTC
When loosing the network connection (e.g. on mobile devices when switching between different wifis or mobile data), using `client.reconnect()` does not work. I think one needs to drop and create a new socket in this case.

One workaround would be to periodically invoke some request (e.g. `GetStateRequest`). In case `TimeoutError` is raised, one can create a completely new instance of `TelegramClient`.

But I guess there already is some kind of ping between server and client, to test whether the connection is still alive? A better solution would be to have some subscribable event or callback which is triggered if this ping signal the connection is lost. Then each application could decide what to, e.g. wait and try reconnect or create a new client instance.

Also, some function like `client.is_connected()` would be nice.

**Comment by Lonami** [comment] 2017-07-29 13:33
> I think one needs to drop and create a new socket in this case.

[But](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_bare_client.py#L170) it [does](https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/mtproto_plain_sender.py#L19) exactly [do](https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/tcp_transport.py#L78) that [already](https://github.com/LonamiWebs/Telethon/blob/master/telethon/extensions/tcp_client.py#L49)?

> But I guess there already is some kind of ping between server and client

[Most likely](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py#L748), if you have updates enabled.

So… any further ideas?

**Comment by feodoran** [comment] 2017-07-29 14:22
You are right, it does. When I tested this yesterday it did not work for some reason. Sometimes you get `ConnectionError` instead of `TimeoutError`, maybe that was it.

>> But I guess there already is some kind of ping between server and client

> Most likely, if you have updates enabled.

This looks like, it just sending pings to let the server know, the client is still there. But it does not check the return value. I am looking for something that tells me "Hey, the connection just broke down, you won't receive any more updates!"

Also, according to the documentation the [ping](https://lonamiwebs.github.io/Telethon/methods/ping.html) should return a `Pong` instance, but I get `None`. Any ideas?

**Comment by Lonami** [comment] 2017-07-29 14:25
> but I get `None`. Any ideas?

Yep, `PingRequest` is a [special case](https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/mtproto_sender.py#L210). The server should never simply send a pong, but who knows. I've never had issues with that, so I've left it that way.

**Comment by feodoran** [comment] 2017-07-29 14:34
Ok, maybe not that important. I am more interested in how to know, that the connection failed?

**Comment by Lonami** [comment] 2017-07-29 14:40
By the way, I tried removing the "specialness" of the ping request, and it doesn't work. Guess it's because it's not quite a method… just a ping, so the server replies with "pong" and not a request result per se. Makes sense?

> I am more interested in how to know

You could enable the [`DEBUG` level](https://github.com/LonamiWebs/Telethon/wiki/Troubleshooting-issues) for logging, which is where Telethon logs everything. Maybe that could provide some more insight.

**Comment by feodoran** [comment] 2017-07-29 15:11
> so the server replies with "pong" and not a request result per se. 

Then why is there a [Type](https://lonamiwebs.github.io/Telethon/types/pong.html) and [Constructor](
https://lonamiwebs.github.io/Telethon/constructors/pong.html) defined?

> You could enable the DEBUG level for logging, which is where Telethon logs everything. Maybe that could provide some more insight.

Nothing. After connecting and disabling network connection, there are no DEBUG messages.

**Comment by Lonami** [comment] 2017-07-29 17:08
> Then why is there a [Type](https://lonamiwebs.github.io/Telethon/types/pong.html) and [Constructor](
https://lonamiwebs.github.io/Telethon/constructors/pong.html) defined?

Telegram is weird.

> Nothing.

Steps to reproduce? Remove and reconnect network? Do you have an example for me to try?

**Comment by feodoran** [comment] 2017-07-29 17:52
Here is the full script I used for testing:

```python
import telethon
from telethon import tl

import logging
logging.basicConfig(level=logging.DEBUG)

def init_client():
    global client
    client = telethon.TelegramClient(
        'test',
        api_id = 1234,
        api_hash = 'xxx'
    )
    print(client.__version__)
    client.connect()
    print('connected')
    if not client.is_user_authorized():
        login()
    # Listen for updates
    client.add_update_handler(update_handler)

def login():
    number = '+123456789'
    client.send_code_request(number)
    code = input('enter code:')
    res = client.sign_in(phone_number=number, code=code)
    print(res)

def update_handler(update_object):
    print(repr(update_object))
    
def check_connection():
    try:
        state = client.invoke(tl.functions.updates.GetStateRequest())
    except (TimeoutError, ConnectionError):
        print('TimeoutError, try reconnecting')
        try:
            client.reconnect()
            client._set_updates_thread(running=True)
        except OSError as error:
            print('OSError', error)

def ping():
    return client.invoke(tl.functions.PingRequest(telethon.helpers.generate_random_long()))

init_client()
```

After starting it, the last couple of lines are:

```
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Request result received
DEBUG:telethon.network.mtproto_sender:receive() released the lock
DEBUG:telethon.network.mtproto_sender:receive() acquired the lock
DEBUG:telethon.network.mtproto_sender:Trying to .receive() the request result...
```

If I then disable the network, I don't get any further messages. But if I keep it running, it repeats:

```
DEBUG:telethon.telegram_bare_client:Receiving updates timed out
DEBUG:telethon.telegram_bare_client:Updates thread released the lock
DEBUG:telethon.telegram_bare_client:Updates thread acquired the lock
DEBUG:telethon.telegram_bare_client:Trying to receive updates from the updates thread
DEBUG:telethon.network.mtproto_sender:send() acquired the lock
DEBUG:telethon.network.mtproto_sender:send() released the lock
DEBUG:telethon.network.mtproto_sender:receive() acquired the lock
DEBUG:telethon.network.mtproto_sender:Trying to .receive() the request result...
DEBUG:telethon.network.mtproto_sender:Handling pong
DEBUG:telethon.network.mtproto_sender:Pong confirmed a request
DEBUG:telethon.network.mtproto_sender:Request result received
DEBUG:telethon.network.mtproto_sender:receive() released the lock
DEBUG:telethon.network.mtproto_sender:receive() acquired the lock
DEBUG:telethon.network.mtproto_sender:Trying to .receive() the request result...
```

**Comment by Lonami** [comment] 2017-09-22 15:03
Since automatic reconnection is performed endlessly as of `v0.13.5` I'll close this issue and assume it has been fixed. Feel free to comment more here to follow the discussion after you have upgraded and tested.

**Comment by chstem** [comment] 2017-10-01 08:46
I tested this on a mobile device, so I can test switching between different network interfaces (wifi and mobile data). I found some issues:


1. Switching between network interfaces does not work at all: `ValueError: Number of retries reached 0.`
1. Reconnecting only worked on wifi. Using the mobile data interface I get: `ValueError: Number of retries reached 0.`
1. If I connect and then disable network, `client.is_connected()` returns always `True`, even after some request failed with `OSError: [Errno 101] Network is unreachable`.
1. `client.connect()` (after disabling and re enabling the same network interface) does not always work. I am not sure what causes this, but it seems to be related to trying to connect to a different interface and then switching back to the original one. But it might also be related to point 2.

**Comment by Lonami** [comment] 2017-10-01 08:48
Alright, thanks for reporting back. About the "number of retries reached 0", there's another issue open with that, and indeed, I think the cause is because it's been disconnected somewhere and it doesn't check that.

**Comment by chstem** [comment] 2017-10-01 08:53
Just in case: This was tested on 4685cda, since the latest commit (ce48c97) fails on `client.connect()`.

**Comment by Lonami** [comment] 2017-10-01 08:55
Indeed, last commit fails, I just patched that but want to do more work before pushing.

**Comment by Lonami** [comment] 2017-10-01 09:29
Fixed on https://github.com/LonamiWebs/Telethon/commit/06bb09b95c86362ade6608bfcd36b38140f9ca60.

**Comment by Lonami** [comment] 2017-11-13 09:34
Would you mind testing again after https://github.com/LonamiWebs/Telethon/commit/99512875a223d564c4de112f10f034f33cf78954 and https://github.com/LonamiWebs/Telethon/commit/07cb001854f614def335b670862e75ef4e29f59e?

**Comment by chstem** [comment] 2017-11-14 20:36
Brief test shows improvement, but there is still 1 problem: 

- I can connect and disable/re-enable the same network interface. 
- I can connect on mobile data and then switch between wifi and mobile data back-and-forth.
- But if I connect on wifi first and then try to switch to mobile data I keep getting `ValueError: Number of retries reached 0.`

(By "connect on ..." I here mean, which interface is active when creating the client object and signing in.)

**Comment by Lonami** [comment] 2017-11-14 20:58
Well of course retries will exhaust eventually. Did you try the PyPi version or master? I think I didn't push some changes regarding this "value error" ro PyPi. Can't remember.

**Comment by chstem** [comment] 2017-11-14 21:01
But the retries should also work eventually, they do for the first 2 points. I tested the current master.

**Comment by Lonami** [comment] 2017-11-14 21:03
Alright, thanks.

**Closed** 2018-06-14 14:33 UTC
