### ISSUE TITLE
telethon.client.updates: Fatal error handling updates

### ISSUE THREAD

**Issue by Mosesofmason** [LonamiWebs/Telethon#3930] opened 2022-09-18 14:54 UTC
Not sure which part of code caused this, but I see this traceback:

**Traceback**
```
telethon.client.updates: Fatal error handling updates (this is a bug in Telethon, please report it)
Traceback (most recent call last):
  File "telethon\client\updates.py", line 339, in _update_loop
  File "asyncio\tasks.py", line 481, in wait_for
  File "asyncio\queues.py", line 166, in get
RuntimeError: Task <Task pending name='Task-497' coro=<Queue.get() running at asyncio\queues.py:166> cb=[_release_waiter(<Future pendi...2B46A64F0>()]>)() at asyncio\tasks.py:416]> got Future <Future pending> attached to a different loop

```

**Comment by Lonami** [comment] 2022-09-18 18:15
Are you using different `asyncio` loops?

**Comment by Mosesofmason** [comment] 2022-09-20 02:16
It may be the reason. I may did something wrong. What is the correct way to integrate telethon event loops into another event loops?

**Comment by Lonami** [comment] 2022-09-20 08:35
Unless you have a solid reason to do otherwise, I'd say having a single loop for everything is the safest and simplest approach. If multiple loops are used, an object created in a loop generally cannot be used within other loops (think a lock, a task, or even the `TelegramClient`). You can configure Telethon to use a different loop in the `TelegramClient` constructor.

Closing under the assumption the problem is using two different loops and not related to Telethon.

**Closed as completed by Lonami** 2022-09-20 08:35 UTC
