### ISSUE TITLE
Proxy not hide ip

### ISSUE THREAD

**Issue by m9w** [LonamiWebs/Telethon#1503] opened 2020-07-25 09:11 UTC
```python
import socks
from telethon import TelegramClient, sync
client = TelegramClient('canadatest2', init.api_id, init.api_hash, proxy=(socks.SOCKS5,'161.35.70.249', 1080))
...
```
OS Win 10 LTSC 1809, Python 3.8
Telegram detect real IP through proxy. Proxy work. It show change lang in confirm message.

![image](https://user-images.githubusercontent.com/52008918/88452348-9f21cd00-ce66-11ea-8d04-b8dba18714e3.png)

**Comment by rnyPlanet** [comment] 2020-09-22 07:15
same problem. did you solve the problem?

**Comment by m9w** [comment] 2020-09-22 08:51
No. I'm wait. I think that problem in socks lib, I not found place in telethon code  where it send real ip address.

**Comment by Lonami** [comment] 2020-09-22 08:57
I have no interest in dealing with proxies myself, so I'll add a help wanted label to see if people want to help out. I can provide assistance if anyone needs help understanding the bits of the library required to solve this.

**Comment by rnyPlanet** [comment] 2020-09-23 16:17
> No. I'm wait. I think that problem in socks lib, I not found place in telethon code where it send real ip address.

Could you show it?

**Comment by rnyPlanet** [comment] 2020-09-24 06:38
@Lonami who wrote the part of the code related to the proxy? maybe the one who wrote and will help

**Comment by Lonami** [comment] 2020-09-24 06:41
I don't remember, and IIRC I'm the one who modified the code over time to adapt it to use `asyncio`.

**Comment by rnyPlanet** [comment] 2020-09-24 06:47
> I don't remember, and IIRC I'm the one who modified the code over time to adapt it to use `asyncio`.

show you the stack trace? and maybe this will help you understand what the problem is

**Comment by Lonami** [comment] 2020-09-24 07:03
What stack trace? Isn't the main problem here that the proxy is seemingly ignored?

**Comment by rnyPlanet** [comment] 2020-09-24 07:33
```
client = TelegramClient("anon", api_id, api_hash,
connection=connection.http.ConnectionHttp,
proxy=(socks.HTTP, 'ip', port, "log", "pass"))
...
```
stack trace if using socks.HTTP and connection.http.ConnectionHttp
```
2020-09-24 10:26:01,536 INFO: Connecting to 149.154.167.51:443/Http...
2020-09-24 10:26:01,655 WARNING: Attempt 1 at connecting failed: FileNotFoundError: [Errno 2] No such file or directory
2020-09-24 10:26:12,717 WARNING: Attempt 2 at connecting failed: timeout: _ssl.c:1106: The handshake operation timed out
2020-09-24 10:26:13,836 WARNING: Attempt 3 at connecting failed: OSError: [Errno 0] Error
2020-09-24 10:26:24,902 WARNING: Attempt 4 at connecting failed: timeout: _ssl.c:1106: The handshake operation timed out
2020-09-24 10:26:26,019 WARNING: Attempt 5 at connecting failed: OSError: [Errno 0] Error
2020-09-24 10:26:27,143 WARNING: Attempt 6 at connecting failed: OSError: [Errno 0] Error
Traceback (most recent call last):
  File "D:/..", line 166, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:/..", line 148, in main
    await client.start(phone=phone,
  File "Programs\Python\Python38-32\lib\site-packages\telethon\client\auth.py", line 139, in _start
    await self.connect()
  File "CPrograms\Python\Python38-32\lib\site-packages\telethon\client\telegrambaseclient.py", line 480, in connect
    if not await self._sender.connect(self._connection(
  File "Programs\Python\Python38-32\lib\site-packages\telethon\network\mtprotosender.py", line 125, in connect
    await self._connect()
  File "Programs\Python\Python38-32\lib\site-packages\telethon\network\mtprotosender.py", line 250, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)
```

if used without ConnectionHttp or connection.tcpfull.ConnectionTcpFull then it ignores the proxy.

maybe I'm doing something wrong? I searched for and tried different approaches for a very long time - unsuccessfully

**Comment by exzhawk** [comment] 2020-09-24 16:34
I did write the proxy part. https://github.com/LonamiWebs/Telethon/pull/37/files It seems they are still alive here https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/connection/connection.py#L54
However, I can't reproduce this issue. I've tried socks.SOCKS5 and socks.HTTP proxy. Both of them work well.

Versions:
Telethon git: c864ef, though I think v1.16.4 should be the same
pysocks: 1.7.1

Test code:

```python
import socks

from telethon import TelegramClient

API_ID = 1
API_HASH = '1'

# with TelegramClient('me', API_ID, API_HASH, proxy=(socks.SOCKS5, '127.0.0.1', 8088)) as client:
with TelegramClient('me', API_ID, API_HASH, proxy=(socks.HTTP, '127.0.0.1', 8089)) as client:
    client.loop.run_until_complete(client.send_message('me', 'Hello, myself!'))
```
The only difference I can tell is that your devices are "Desktop" and mines are "Unknown device".
![image](https://user-images.githubusercontent.com/7038938/94172275-e22f0980-fec4-11ea-9d14-6fbfda042808.png)

**Comment by rnyPlanet** [comment] 2020-10-03 13:37
solution: https://github.com/LonamiWebs/Telethon/issues/1337#issuecomment-560490965

**Comment by re1ad** [comment] 2020-11-13 01:03
```python
import asyncio
import socks
from telethon import TelegramClient
from telethon.tl.functions.account import GetAuthorizationsRequest


proxy = (socks.SOCKS5, proxy_ip, int(proxy_port), True, proxy_login, proxy_password)


async def auth():
    client = TelegramClient(
        session=phone,
        api_id=api_id,
        api_hash=api_hash,
        proxy=proxy
    )
    await client.connect()
    sessions = await client(GetAuthorizationsRequest())
    print(sessions)


if __name__ == '__main__':
    asyncio.set_event_loop(asyncio.SelectorEventLoop())
    loop = asyncio.get_event_loop()
    loop.run_until_complete(auth())
```

Try it

**Comment by knownamed** [comment] 2021-01-13 12:56
> ```python
> import asyncio
> import socks
> from telethon import TelegramClient
> from telethon.tl.functions.account import GetAuthorizationsRequest
> 
> 
> proxy = (socks.SOCKS5, proxy_ip, int(proxy_port), True, proxy_login, proxy_password)
> 
> 
> async def auth():
>     client = TelegramClient(
>         session=phone,
>         api_id=api_id,
>         api_hash=api_hash,
>         proxy=proxy
>     )
>     await client.connect()
>     sessions = await client(GetAuthorizationsRequest())
>     print(sessions)
> 
> 
> if __name__ == '__main__':
>     asyncio.set_event_loop(asyncio.SelectorEventLoop())
>     loop = asyncio.get_event_loop()
>     loop.run_until_complete(auth())
> ```
> 
> Try it

Hey bro, thank you! Can you explain how to get the client out of the function?

**Comment by Lonami** [comment] 2021-05-09 00:28
I'm cleaning up proxy-related issues, so closing in favour of the new issue.

**Closed by Lonami** 2021-05-09 00:28 UTC
Labels: help wanted

**Comment by rnyPlanet** [comment] 2021-06-24 04:02
> I did write the proxy part. https://github.com/LonamiWebs/Telethon/pull/37/files It seems they are still alive here https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/connection/connection.py#L54

 maybe you know why proxies work only with SelectorEventLoop?  what's so special about him

**Comment by rnyPlanet** [comment] 2021-06-30 18:32
> However, I can't reproduce this issue. I've tried socks.SOCKS5 and socks.HTTP proxy. Both of them work well.

do you have a problem with the proxy? (permanent reconnect)

**Comment by SacCrypt** [comment] 2022-06-04 08:57
I am facing the same problem, proxy server seems to be working fine, but telegram detects my ip everytime 
```
from telethon.sync import TelegramClient, events

api_id = ''
api_hash = ''

with TelegramClient('Socheen', api_id, api_hash, proxy = {
    'proxy_type': 'socks5', 
    'addr': '208.102.51.6',      
    'port': 58208,
    'rdns': True
}) as client:
    client.send_message('me', 'Hello, myself!')
    client.loop.run_until_complete(client.send_message('me', 'Hello, myself!'))
```

**Comment by Lau1Re** [comment] 2023-02-10 10:32
My client didn't hide ip either until I installed the following dependencies:
pip install async-timeout
pip install PySocks 
pip install python-socks

**After this, all works well**

**Comment by cheditx** [comment] 2023-07-30 06:33
Works for me too, after i installed all the libraries you named, and i used @re1ad proxy format code.

proxy = (socks.SOCKS5, proxy_ip, int(proxy_port), True, proxy_login, proxy_password)

**Comment by ongbanbanhbao** [comment] 2025-05-07 19:01
> My client didn't hide ip either until I installed the following dependencies: pip install async-timeout pip install PySocks pip install python-socks
> 
> **After this, all works well**

Thank you. It works for me!
