### ISSUE TITLE
file size bug and filename bug

### ISSUE THREAD

**Issue by addreeh** [LonamiWebs/Telethon#4212] opened 2023-09-26 08:22 UTC
### Code that causes the issue

```
@app.route('/send_media_topic/<group_id>/<topic_id>/<phone_number>/<file_size>', methods=['POST'])
async def send_media_topic(group_id, topic_id, phone_number, file_size):
    phone_number = "+" + phone_number
    file = (await request.files).get('file')
    if file:
        filename = file.filename
        content_type = file.content_type

        print(f"Filename: {filename}")
        print(f"Content Type: {content_type}")

        async with aiofiles.open(filename, 'wb') as f:
            await f.write(file.read())  # No se utiliza 'await' aquí

        await send_file_to_telegram_topic(filename, group_id, topic_id, phone_number, file_size)

        try:
            os.remove(filename)
            print(f"Archivo local {filename} eliminado.")
        except Exception as e:
            print(f"No se pudo eliminar el archivo local: {e}")

        return 'Archivo enviado a Telegram con éxito y archivo local eliminado', 200
    else:
        return 'Error al enviar el archivo', 400
    
async def send_file_to_telegram_topic(filename, group_id, topic_id, phone_number, file_size_file):
    print("TAMANO", file_size_file)
    try:
        string_session = get_string_session_from_database(phone_number)
        client = TelegramClient(StringSession(string_session), api_id, api_hash)

        def callback(current, total):
            print('Uploaded', current, 'out of', total,
                  'bytes: {:.2%}'.format(current / total))

        await client.connect()

        attributes = [types.DocumentAttributeFilename(file_name=str(filename))]

        await client.send_file(int(group_id), filename, caption=filename, reply_to=int(topic_id), silent=True, attributes=attributes, file_size=int(file_size_file), progress_callback=callback)
        print(f"{filename} enviado correctamente.")
    except Exception as e:
        print(f"No se pudo enviar el archivo {filename}.")
```

### Expected behavior

I expect that when I upload the file and when I get the file specs the size and name should be equal.

### Actual behavior

I specify the file size at send_media, but when i get the message info the size is different.
Also im trying to specify the file name, but when i try to download it the name is different.

### Traceback

SEND FILE:

Filename: geiser-fly-en-Nevada-estados-uni.jpg
Content Type: image/jpeg
TAMANO 176090
Executing <Task pending name='Task-152' coro=<MTProtoSender._send_loop() running at C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\network\mtprotosender.py:489> wait_for=<Future pending cb=[Task.task_wakeup()] created at C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py:427> created at C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\network\mtprotosender.py:268> took 0.421 seconds
Uploaded 131072 out of 176090 bytes: 74.43%
Executing <Task pending name='Task-152' coro=<MTProtoSender._send_loop() running at C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\network\mtprotosender.py:489> wait_for=<Future pending cb=[Task.task_wakeup()] created at C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py:427> created at C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\telethon\network\mtprotosender.py:268> took 0.140 seconds
Uploaded 176090 out of 176090 bytes: 100.00%
geiser-fly-en-Nevada-estados-uni.jpg enviado correctamente.
Archivo local geiser-fly-en-Nevada-estados-uni.jpg eliminado.

GET MESSAGES:

DENTRO MENSAJES
Mensaje de texto: geiser-fly-en-Nevada-estados-uni.jpg
Tamaño del archivo adjunto: 152499 bytes

### Telethon version

1.30.3

### Python version

Python 3.11.5

### Operating system (including distribution name and version)

Windows 11

### Other details

Im working with a flutter app and a quart server. Also in flutter the file size is different:
I/flutter (28748): /storage/emulated/0/Paisajes/geiser-fly-en-Nevada-estados-uni.jpg, 1, -1001964662427
I/flutter (28748): geiser-fly-en-Nevada-estados-uni.jpg 176090
I/flutter (28748): 176090

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-09-26 16:41
Are you sure `f.write()` is writing the entire file to disk?

What happens if you try with just the Telethon code and a local file?

What happens if you don't specify the file size in the function?

You also don't need to download the file. Telethon can send anything with a `read`.

**Comment by addreeh** [comment] 2023-09-27 08:07
I don't want to download the file, but I need to check the file size to know if the file was already sent to the group, because maybe I want to send the same file but is a different version with changes, so the size would be different and should be uploades to the chat.

f.write is writing the entire file:
![image](https://github.com/LonamiWebs/Telethon/assets/74270582/a23aed07-dcc6-48d8-962c-93f30bc2959e)

If i directly upload the file, I get also a different size to the original, left from flutter, right directly:
![image](https://github.com/LonamiWebs/Telethon/assets/74270582/c807329e-ff38-44d3-8a5f-69f33d0d97ef)


I mean file_size is ignoring, no matter if I put or not, the file always upload with a different size.

**Comment by Lonami** [comment] 2023-09-27 16:08
This code:
```python
async def main():
    file = "testfile.bin"
    if not os.path.isfile(file):
        with open(file, "wb") as fd:
            fd.write(os.urandom(176090))

    with open(file, "rb") as fd:
        blob = fd.read()

    print("size", len(blob))

    async with user:
        attributes = [types.DocumentAttributeFilename(file_name=file)]

        m = await user.send_file(
            "me",
            file,
            caption=file,
            silent=True,
            attributes=attributes,
            file_size=len(blob),
        )

        downloaded = await m.download_media(bytes)
        print("downloaded", len(downloaded))
        print("equal?", blob == downloaded)
```

Prints:

```
size 176090
downloaded 176090
equal? True
```

And shows:
![image](https://github.com/LonamiWebs/Telethon/assets/6297805/fb7e0e96-59d5-4848-8229-57bda7de51cf)

So I can't reproduce the issue.

Telegram will compress images and there is nothing you can do about that, unless you send them as documents.

Closing the issue unless you provide the faulty file and some smaller self-contained code I can just run to reproduce it.

**Closed as completed by Lonami** 2023-09-27 16:08 UTC

**Comment by addreeh** [comment] 2023-09-27 18:15
![geiser-fly-en-Nevada-estados-uni](https://github.com/LonamiWebs/Telethon/assets/74270582/442bbe26-cb52-4b1d-a871-e9995c042ece)
Thats the file, i cant send you the entire code because you will need to create a flutter environment project, i can send you the server code:

```
@app.route('/send_media_topic/<group_id>/<topic_id>/<phone_number>/<file_size>', methods=['POST'])
async def send_media_topic(group_id, topic_id, phone_number, file_size):
    phone_number = "+" + phone_number
    file = (await request.files).get('file')
    if file:
        filename = file.filename
        content_type = file.content_type

        print(f"Filename: {filename}")
        print(f"Content Type: {content_type}")
        print(f"Tamaño: ${file_size}")

        async with aiofiles.open(filename, 'wb') as f:
            await f.write(file.read())  # No se utiliza 'await' aquí

        await send_file_to_telegram_topic(filename, group_id, topic_id, phone_number, file_size)

        try:
            os.remove(filename)
            print(f"Archivo local {filename} eliminado.")
        except Exception as e:
            print(f"No se pudo eliminar el archivo local: {e}")

        return 'Archivo enviado a Telegram con éxito y archivo local eliminado', 200
    else:
        return 'Error al enviar el archivo', 400
    
async def send_file_to_telegram_topic(filename, group_id, topic_id, phone_number, file_size_file):
    print("TAMANO", file_size_file)
    try:
        string_session = get_string_session_from_database(phone_number)
        client = TelegramClient(StringSession(string_session), api_id, api_hash)

        def callback(current, total):
            print('Uploaded', current, 'out of', total,'bytes: {:.2%}'.format(current / total))

        await client.connect()

        attributes = [types.DocumentAttributeFilename(file_name=str(filename))]

        await client.send_file(int(group_id), filename, caption=filename, reply_to=int(topic_id), silent=True, attributes=attributes, file_size=int(file_size_file), progress_callback=callback)
        print(f"{filename} enviado correctamente.")
    except Exception as e:
        print(f"No se pudo enviar el archivo {filename}.")
```

From flutter the file information is right, indeed the file size, prints in server shows right values. 
If a upload the file as document it dont show as image in the chat right? 

Another question, is there anyway to specify the file name? i tried with attribute but when I download give a random name like that:
![image](https://github.com/LonamiWebs/Telethon/assets/74270582/7ce756f9-38f5-46ea-b419-fbe7dd4f213d)

**Comment by Lonami** [comment] 2023-09-27 19:09
With that photo, after downloading it, it's 152499, the same size you mentioned.

[As I said before](https://github.com/LonamiWebs/Telethon/issues/4212#issuecomment-1737693787):

> Telegram will compress images and there is nothing you can do about that, unless you send them as documents.

If you don't provide a file name, [Telethon will not use the file name because it could contain unsafe characters](https://github.com/LonamiWebs/Telethon/blob/6a36066d19aa61979d4fb490b45d9a2403c6531d/telethon/client/downloads.py#L824). You can of course download it to the `message.file.name` if you trust it.

So it seems like everything is working as intended.

Send as document if you want Telegram to not compress your image.

Provide the file name yourself if you want it to be downloaded exactly there.
