### ISSUE TITLE
unable to exit from one event loop once entered. message is keep firing the existing event first and then trigger the 2nd event function, which creates the result issue.

### ISSUE THREAD

**Issue by mayanrajesh** [LonamiWebs/Telethon#1729] opened 2021-03-14 21:35 UTC
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```client = telethon.TelegramClient('session',api_id,api_hash)
client.start()
# Handle all callback queries and check data inside the handler

def option1(message):
    if message == b'option1':
        @client.on(events.NewMessage(incoming=True))
        async def handler(event):
            request = event.raw_text
            response = Bot.respond(request)
            await event.respond(response)



def option2(message):
    if message == b'option2':
        @client.on(events.NewMessage())
        async def gene(event):
            request = event.raw_text
            response = Bot.respond(request)
            await event.respond(response)


def option3(message):
    @client.on(events.NewMessage())
    async def synonym(event):
        if message == b'option3':
            request=event.raw_text
            response = Bot.respond(request)
            await event.respond(response)

def bot_option():
    @client.on(events.NewMessage(pattern='/connect', incoming=True))
    async def main(event='/connect'):
        await client.send_message(event.chat, 'Select an option', buttons=[
            [Button.inline('option1', b'option1'), Button.inline('option2', b'option2')],
            [Button.inline('option3', b'option3')]

        ])

    @client.on(events.CallbackQuery())
    async def handler(event):
        
        if event.data == b'option1':
            await event.respond('Hi, How can I Help you?')
            option1(event.data)


        elif event.data == b'option3':
            await event.respond('Please enter option3.')
            option2(event.data)
            

        elif event.data == b'option2':
            await event.respond('Please enter option2.')
            option3(event.data)


    client.run_until_disconnected()
...

```

**Traceback**
```
Traceback (most recent call last):
  File "code.py", line 1, in <code>

```

**Comment by Lonami** [comment] 2021-03-14 21:42
You're creating a new event handler every time a new option is clicked. Please ask questions like this in StackOverflow or [the group](https://t.me/TelethonChat). I will close this as I think this is not a bug, but if you do provide a traceback and I think it's a bug I will reopen (more clarification would be helpful too).

**Closed by Lonami** 2021-03-14 21:42 UTC
