### ISSUE TITLE
Inlinebuilder.article was never awaited

### ISSUE THREAD

**Issue by New-dev0** [LonamiWebs/Telethon#1671] opened 2021-01-14 02:37 UTC
packages/telethon/client/updates.py:451: RuntimeWarning: coroutine 'InlineBuilder.article' was never awaited

**Comment by Lonami** [comment] 2021-01-14 07:11
Closing since this is not actionable without clear reproduction steps (code) and it's likely that such code is wrong.

**Closed by Lonami** 2021-01-14 07:11 UTC
