### ISSUE TITLE
Error on send message

### ISSUE THREAD

**Issue by 88ee55** [LonamiWebs/Telethon#350] opened 2017-10-17 07:19 UTC
telethon 0.15.2.1
i send '\U0001f3c5'
```
Unexpected error (<class 'struct.error'>): required argument is not an integer at

File "/usr/lib64/python3.5/site-packages/telethon/telegram_bare_client.py", line 448, in __call__    result = self._invoke(sender, call_receive, *requests)
File "/usr/lib64/python3.5/site-packages/telethon/telegram_bare_client.py", line 467, in _invoke sender.send(*requests)
File "/usr/lib64/python3.5/site-packages/telethon/network/mtproto_sender.py",line 86, in send    self._send_message(message)
File "/usr/lib64/python3.5/site-packages/telethon/network/mtproto_sender.py",line 128, in _send_message  + message.to_bytes()
File "/usr/lib64/python3.5/site-packages/telethon/tl/tl_message.py", line 16,in to_bytes body = GzipPacked.gzip_if_smaller(self.request)
File "/usr/lib64/python3.5/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller data = request.to_bytes()
File "/usr/lib64/python3.5/site-packages/telethon/tl/message_container.py", line 17, in to_bytes  ) + b''.join(m.to_bytes() for m in self.messages)
File "/usr/lib64/python3.5/site-packages/telethon/tl/tl_message.py", line 16, in to_bytes    body = GzipPacked.gzip_if_smaller(self.request)
File "/usr/lib64/python3.5/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller    data = request.to_bytes()
File "/usr/lib64/python3.5/site-packages/telethon/tl/functions/messages.py", line 3936, in to_bytes    self.peer.to_bytes(),
File "/usr/lib64/python3.5/site-packages/telethon/tl/types/__init__.py", line 9347, in to_bytes    struct.pack('<q', self.access_hash),
struct.error: required argument is not an integer
```

**Comment by Lonami** [comment] 2017-10-17 07:29
Strange, I just tried:
```python
client.send_message('lonami', '\U0001f3c5')
```

And it worked. So the issue is not on the message contents :)

**Comment by 88ee55** [comment] 2017-10-17 07:39
InputPeerUser(id, hash)
id and hash is string

all messages are sent, but sometimes an error occurs on one message (\U0001f3c5)

**Comment by Lonami** [comment] 2017-10-17 07:40
I'm 100% sure the message you're sending isn't related.
> id and hash is string

They **must** be integers.

**Comment by 88ee55** [comment] 2017-10-17 11:48
made an int (although all other messages were sent)
the same error is periodically obtained

**Comment by Lonami** [comment] 2017-10-17 11:50
Accident. Anyway it's impossible it's the same error as the error clearly says "argument is not an int". Just show me the whole code or a minimal working example, is it that hard.

**Comment by hoatle** [comment] 2017-10-23 11:27
I got the same problem with Telethon 0.15.3 under Python 3.6.3

code snippet:
```
def forward(client, update, to_ids):
    """
    Forward an update to channel ids
    // TODO(hoatle): make this work with group chat and peer chat, too
    See:
        - https://github.com/LonamiWebs/Telethon/wiki/Forwarding-messages
        - https://github.com/LonamiWebs/Telethon/wiki/Retrieving-an-entity
    :param client:
    :param update:
    :param to_ids:
    :return:
    """
    msg_id = update['message']['id']
    from_id = update['message']['to_id']['channel_id']

    for to_id in to_ids:
        LOGGER.debug(f'Sending msg_id: {msg_id} from {from_id} to {to_id}')
        client(ForwardMessagesRequest(
            from_peer=client.get_entity(PeerChannel(int(from_id))),
            id=[msg_id],
            to_peer=client.get_entity(PeerChannel(int(to_id)))
        ))

        LOGGER.debug(f'[x] msg_id: {msg_id} from {from_id} to {to_id} sent!')
```

error happened after for a while (2nd time I guess)


```
telegram-fwd-dev_1       | DEBUG      2017-10-23 11:01:40,409 fwd                            callback                             71  : free.1147798110: b'{"message": {"out": false, "mentioned": false, "media_unread": false, "silent": false, "post": true, "id": 3289, "from_id": null, "to_id": {"channel_id": 1147798110}, "fwd_from": null, "via_bot_id": null, "reply_to_msg_id": null, "date": "2017-10-23T11:01:03", "message": "", "media": {"photo": {"has_stickers": false, "id": 6300580413663455203, "access_hash": -5494130023323922852, "date": "2017-10-23T11:01:03", "sizes": [{"type": "s", "location": {"dc_id": 5, "volume_id": 852234057, "local_id": 222743, "secret": -4592117247075450104}, "w": 90, "h": 73, "bytes": "b\'\\\\xff\\\\xd8\\\\xff\\\\xe0\\\\x00\\\\x10JFIF\\\\x00\\\\x01\\\\x01\\\\x01\\\\x00H\\\\x00H\\\\x00\\\\x00\\\\xff\\\\xdb\\\\x00C\\\\x00\\\\x0e\\\\n\\\\x0b\\\\r\\\\x0b\\\\t\\\\x0e\\\\r\\\\x0c\\\\r\\\\x10\\\\x0f\\\\x0e\\\\x11\\\\x16$\\\\x17\\\\x16\\\\x14\\\\x14\\\\x16, !\\\\x1a$4.763.22:ASF:=N>22HbINVX]^]8EfmeZlS[]Y\\\\xff\\\\xdb\\\\x00C\\\\x01\\\\x0f\\\\x10\\\\x10\\\\x16\\\\x13\\\\x16*\\\\x17\\\\x17*Y;2;YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\\\\xff\\\\xc0\\\\x00\\\\x11\\\\x08\\\\x00I\\\\x00Z\\\\x03\\\\x01\\"\\\\x00\\\\x02\\\\x11\\\\x01\\\\x03\\\\x11\\\\x01\\\\xff\\\\xc4\\\\x00\\\\x1a\\\\x00\\\\x00\\\\x02\\\\x03\\\\x01\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x03\\\\x04\\\\x00\\\\x01\\\\x02\\\\x05\\\\x06\\\\xff\\\\xc4\\\\x005\\\\x10\\\\x00\\\\x02\\\\x02\\\\x01\\\\x03\\\\x01\\\\x05\\\\x04\\\\t\\\\x04\\\\x03\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x01\\\\x02\\\\x03\\\\x11\\\\x00\\\\x04\\\\x12!1\\\\x05\\\\x13\\"AQ\\\\x142a\\\\xd1\\\\x06#Rq\\\\x81\\\\x91\\\\xa1\\\\xc1\\\\xf0\\\\x16b\\\\xe1\\\\xf1BC\\\\xb1\\\\xff\\\\xc4\\\\x00\\\\x18\\\\x01\\\\x00\\\\x03\\\\x01\\\\x01\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x01\\\\x03\\\\x02\\\\x04\\\\xff\\\\xc4\\\\x00%\\\\x11\\\\x00\\\\x02\\\\x02\\\\x01\\\\x03\\\\x04\\\\x01\\\\x05\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x01\\\\x02\\\\x11!\\\\x03\\\\x121\\\\x13\\\\x142a\\\\x04\\"3A\\\\xb1\\\\xf0\\\\xff\\\\xda\\\\x00\\\\x0c\\\\x03\\\\x01\\\\x00\\\\x02\\\\x11\\\\x03\\\\x11\\\\x00?\\\\x00\\\\xf7\\\\xdd\\\\xa3\\\\xad]\\\\x0e\\\\x9b\\\\xbd*\\\\\\\\\\\\x96\\\\n\\\\xabug\\\\x16\\\\xd1v\\\\xb7\\\\xb5\\\\xc0\\\\xec\\\\xbaw2F\\\\xc02)\\\\xbe\\\\x0fC\\\\x8d\\\\xeb\\\\xe2\\\\x82m+&\\\\xa5KGb\\\\xeb\\\\xa8\\\\xf8\\\\xe2\\\\xda8\\\\xfb?N\\\\x86\\\\x18G\\\\xbc\\\\xd6w\\\\xd9,x\\\\xf5\\\\xfb\\\\xc6o\\\\xe9\\\\xdb\\\\xec\\\\x93S\\\\xdfw\\\\x81\\\\x88\\\\xf5l\\\\xee\\\\x14\\\\xe9g[5\\\\xb8\\\\x81C\\\\xe3\\\\xd7\\\\x1a\\\\xc5L\\\\xdaX\\\\xa9\\\\xec/\\\\x904}3gW\\\\x00f^\\\\xf0\\\\x16^\\\\xa0\\\\x0b\\\\xcc\\\\x15\\\\x0f\\\\x93\\\\x17\\\\x8bY\\\\x04\\\\xa1\\\\n1\\\\xf1\\\\x8b\\\\x16\\\\xa4\\\\x7f?\\\\xc8\\\\xc8\\\\xba\\\\xd8\\\\x186\\\\xd7$\\\\x80Mm7B\\\\xfeG\\\\x00\\\\x18\\\\xc9\\\\x80\\\\xf6\\\\xa8\\\\x8a\\\\x16\\\\x0cH\\\\x14O\\\\x1e\\\\xb9gS\\\\x10\\\\xbbc\\\\xc7\\\\xf6\\\\x9ct\\\\xd8\\\\x9c\\\\x92\\\\xe4Q\\\\xfbU\\\\x04\\\\xf2E\\\\x1c\\\\x12HP\\\\xd1+]s\\\\\'\\\\xb6\\\\x15\\\\n\\\\xf7\\\\xbay\\\\xa3Rkq\\\\x18I`\\\\xd0I#<\\\\x91)b|F\\\\x88\\\\xcc\\\\xc7\\\\xa7\\\\xec\\\\xe0\\\\xdb\\\\x96%\\\\x05y\\\\x16\\\\x0f\\\\xe7\\\\x97]:\\\\xf1g;\\\\xea_\\\\x92:\\\\x16.\\\\xbc\\\\xf2\\\\xf3\\\\x11\\\\xc8\\\\xb2\\\\x02P\\\\xd8\\\\x06\\\\xae\\\\xb3y\\\\xcet\\\\x81\\\\xd4\\\\x1a\\\\x8f\\\\xdeU\\\\xb3V\\\\xc2\\\\xf1s C\\\\xe20\\\\x82<\\\\x8a\\\\x91\\\\xcd\\\\xff\\\\x00\\\\xacfuf@\\\\x15\\\\x15\\\\xf9\\\\x16\\\\x1b\\\\xd3\\\\x00\\\\x04\\\\xd6/L\\\\x95\\\\xd7\\\\x96\\\\xfcFR5D\\\\xe5w\\\\x82\\\\xcb\\\\x13\\\\x1d\\\\xee\\\\x882Y6\\\\x86\\\\xbf\\\\x97\\\\x96K\\\\x16\\\\xf7\\\\xb4\\\\xf4:\\\\xd8\\\\xe6\\\\xf2\\\\x87zov\\\\x99N\\\\xee\\\\xbe!XD\\\\x85YI\\\\x92\\\\x15V<W^0t\\\\x84\\\\xad\\\\xff\\\\x000me\\\\x95\\\\xb7\\\\xc06\\\\x8e\\\\x01\\\\xe8\\\\x0f\\\\xaeP.\\\\xa4Si\\\\x81<\\\\n\\\\x1f\\\\xe7\\\\x0f\\\\xdcDM\\\\xec\\\\x19b\\\\x08\\\\x81\\\\xb0\\\\x8a\\\\r\\\\xee\\\\xe9\\\\xe7\\\\x8a\\\\xd0\\\\xf6\\\\xc8\\\\x01\\\\\'\\\\xc5RBP\\\\xb7F\\\\x1d9\\\\xc8w\\\\x90>\\\\xb2\\\\x10\\\\xc0\\\\x92k\\\\xccW\\\\xcf\\\\x0f\\\\xdc\\\\xc7\\\\xf6\\\\x17\\\\xee\\\\xac\\\\x82\\\\x08\\\\x85R\\\\x0e/\\\\xf5\\\\xeb\\\\x86\\\\xe4\\\\x1bX\\\\xaf6XO\\\\x15\\\\x13\\\\xc5\\\\x81\\\\xd2\\\\xfat\\\\xcd\\\\x91#HV9Px}\\\\x05\\\\xff\\\\x00\\\\xe7\\\\xae\\\\x1c\\\\xc3\\\\x19]\\\\xa5\\\\x16\\\\xbd+-cD6\\\\xaa\\\\x01\\\\xe9\\\\x8fr\\\\r\\\\x8c\\\\x91\\\\xa9U\\\\xa6\\\\xe4\\\\xe6\\\\xf2d\\\\xc9\\\\x94&\\\\n\\\\x19\\\\xd2d\\\\x0c\\\\xbb\\\\x94\\\\xfd\\\\x96\\\\x14G\\\\xe1\\\\x85\\\\xc5\\\\xb5\\\\x9bb\\\\x85\\\\xe6.\\\\xe8\\\\x12\\\\x99\\\\x8a\\\\x0eH\\\\x1eX\\\\xd6L\\\\xc9\\\\xd6Frg%\\\\xfbE\\\\xa33\\\\xbc\\\\xd3\\"F\\\\xaa\\\\xac\\\\x80!<5\\\\xd5\\\\x8e\\\\xb7\\\\xc6\\\\x0fM\\\\xda\\\\xf2\\\\xce\\\\x04\\\\x91i\\\\xc3i\\\\xb7\\\\x1d\\\\xf3;\\\\x85\\\\xda\\\\x07^?\\\\x1c\\\\xd7N\\\\\\\\\\\\x98\\\\xebF\\\\xe8\\\\xec3\\\\x05RX\\\\xd0\\\\x1c\\\\xe2Z\\\\x89\\\\x06\\\\xabM\\\\x0c\\\\xda}A\\\\x8e>\\\\xf3v\\\\xf0\\\\x0f\\\\x88\\\\x0b\\\\xb1\\\\x85\\\\x8d\\\\x1e}\\\\xcd##DHh\\\\xca\\\\xdf+^y\\\\xadTe\\\\xa2EKP\\\\x18{\\\\xa5\\\\x87\\\\x1f\\\\x86.\\\\rs\\\\xcf\\\\x02\\\\xdb\\\\xa2\\\\xb5\\\\x1e\\\\xd9\\\\\'\\"\\\\xfc\\\\xf1\\\\x85\\\\xd5@\\\\x8aGxN\\\\xda&\\\\xc1\\\\xbe\\\\x7f\\\\xd8\\\\xc0\\\\xac-\\\\xb7iil\\\\xd7\\\\xfc\\\\x9f\\\\x8f\\\\xc6\\\\xf2\\\\xfd\\\\x92a\\\\xff\\\\x00e\\\\xd7#\\\\xeb\\\\x1f\\\\xe7\\\\x89\\\\xaa4\\\\x9d\\\\x8c.\\\\xaa\\\\x16\\\\x16\\\\xafc\\\\xa7C\\\\x8b\\\\xea\\\\xcfzP\\\\xc7\\\\xab0\\\\x8eE\\\\x05&\\\\xf2\\\\x9bI9\\\\x1c\\\\xca,\\\\x0e\\\\x08w\\\\x1e\\\\x7f~Y\\\\xd2\\\\xce\\\\n\\\\x95\\\\x91M\\\\n\\\\xf1\\\\x17\\\\xf9\\\\xe0\\\\x9d\\\\t\\\\xab\\\\xc3\\\\r\\\\xa3FH\\\\x89i\\\\xcc\\\\xe1\\\\x8d\\\\x86\\"\\\\xab\\\\x18\\\\xcc$a9\\\\x1dk\\\\x9eNo\\\\x06\\\\xed\\\\xd8\\\\xd2\\\\xa5D\\\\xc0\\\\xcf!D4\\\\x85\\\\xcf\\\\xd9\\\\x15\\\\xcf\\\\xe7\\\\xc6\\\\x1b2\\\\xc6\\\\x85\\\\x9f\\\\xd3\\\\x10>\\\\x04\\\\xbb\\\\xb8\\\\xe5\\\\x8c6\\\\xad\\\\x11e#\\\\xc5\\\\xb5\\\\xa8W\\\\xa7\\\\xc4`5\\\\x1d\\\\xce\\\\x9bN\\\\xc8\\\\x90D\\\\xda:=\\\\xe8\\\\xdd\\\\xca\\\\xfcx\\\\xeb\\\\x93\\\\xb3\\\\xb5\\\\xc3[&\\\\xa1=\\\\x9d\\\\x91\\\\xa2j\\\\\'\\\\x8e\\\\x96h\\\\x1b\\\\xf3\\\\xc2\\\\x89\\\\x80\\\\xedOex\\\\x8fv\\\\xd0\\\\xef\\\\x04\\\\xf4&\\\\xe8\\\\xf1\\\\x95\\\\xa6\\\\x9d2\\\\t\\\\xc6QM~F\\\\xf4\\\\xae\\\\xb2i\\\\xa2x\\\\xec\\\\xc6T\\\\x15\\\\\'\\\\xccW\\\\x19s\\\\x97\\\\n\\\\xbd\\\\xdd^\\\\xe1w\\\\xe9\\\\xe7\\\\x95\\\\xa7VH\\\\xf6\\\\x14TE\\\\xf0\\\\xa0S~\\\\x11\\\\xd3\\\\xfdf\\\\xa6\\\\xbe\\\\xef\\\\x83G\\\\xd7%\\"\\\\xf1\\\\xe0\\\\x0c\\\\xfbn2\\\\xceWkX\\\\x03\\\\xcf\\\\x03\\\\xedR\\\\xc9&\\\\xd8c\\\\x04W\\\\xbc}\\\\xdf\\\\xcf\\\\xf6\\\\xc5dhc\\\\x8b\\\\xbd\\\\xd6\\\\xce\\\\xa5\\\\x0f@\\\\xa7\\\\xdf\\\\xfd\\\\xcf\\\\xdd\\\\xd39z\\\\xbe\\\\xdcy~\\\\xa7J;\\\\x88\\\\xfa\\\\x06=O\\\\xcb)\\\\x18n\\\\xe0\\\\x86\\\\xa6\\\\xaa\\\\x878\\\\xfd\\\\x9dy\\\\xfbJ\\\\r0G\\\\xd4s\\\\xa9\\\\x00\\\\x8d\\\\x89\\\\xfc\\\\xe38]\\\\xa3\\\\xda\\\\xba\\\\x8dK<2Fc7\\\\xc0\\\\x16(|}p\\\\x1aMP\\\\xd0k\\\\x1aFU\\\\x91\\\\xf6\\\\x90<\\\\xc5\\\\xfa\\\\xe2\\\\xda\\\\xb9\\\\xa5\\\\x9d\\\\xdayV\\\\xf7\\\\x9e\\\\xbeD\\\\xe5\\\\xe1\\\\xa4\\\\x93VsO^RN\\\\xb1\\\\xeb\\\\xd1\\\\xd9\\\\xfa&X\\\\xeb\\\\xa7\\\\x04\\\\x92;\\\\xbf\\\\xdcg\\\\xab\\\\xcf1\\\\xf4a\\\\x99\\\\xf5,\\\\xcc\\\\xea\\\\xdfUB\\\\xba\\\\x8a#\\\\xaez|\\\\x96\\\\xb7\\\\x99\\\\xd5\\\\xf1\\\\xbe\\\\xda&Q\\\\x00\\\\xf5\\\\xcb\\\\xc9\\\\x91.a#H\\\\xefb*\\\\xd9\\\\xb3B\\\\xaf)\\\\xa2\\\\x8d\\\\xdc; .\\\\xa2\\\\x83W a2ab\\\\xa4P\\\\x141n\\\\xd0\\\\x1a\\\\x83\\\\xa6\\\\xad.\\\\xce\\\\xf0\\\\x9e\\\\xaf\\\\xd0\\\\x0ck&\\\\x00\\\\xd5\\\\xaa<\\\\x9c\\\\xdd\\\\x89\\\\xaf\\\\x9d\\\\xb7H\\\\xd1\\\\x17?\\\\xdc~Y\\\\x85\\\\xfa;\\\\xafGV\\\\x06\\\\x02T\\\\xdd\\\\x16?,\\\\xf5\\\\xf92\\\\xabVIQ\\\\x0e\\\\xda\\\\r\\\\xdeO\\\\x1f/\\\\xd1\\\\xde\\\\xd0\\\\x91\\\\xcb\\\\x1e\\\\xe0Y\\\\xba\\\\x0ch~\\\\x99?\\\\xa7{D\\\\xc4\\"f\\\\x88\\\\xa06\\\\x06\\\\xff\\\\x00?\\\\xcb=\\\\x86Lk^K\\\\x01\\\\xdbB\\\\xef\\\\\'\\\\x0f\\\\xb0{&^\\\\xce\\\\x92W\\\\x98.\\\\xe6\\\\x14\\\\n\\\\xbd\\\\xf1\\\\xc7\\\\xc3;\\\\x992d\\\\xe5\\\\\'\\\\\'l\\\\xb4 \\\\xa0\\\\xa9\\\\x1f\\\\xff\\\\xd9\'"}, {"type": "m", "location": {"dc_id": 5, "volume_id": 852234057, "local_id": 222744, "secret": -6555946374391176648}, "w": 320, "h": 259, "size": 23271}, {"type": "x", "location": {"dc_id": 5, "volume_id": 852234057, "local_id": 222745, "secret": 7815526929650056270}, "w": 506, "h": 410, "size": 47687}]}, "caption": null, "ttl_seconds": null}, "reply_markup": null, "entities": [], "views": 1, "edit_date": null, "post_author": null}, "pts": 9273, "pts_count": 1}'
telegram-fwd-dev_1       | DEBUG      2017-10-23 11:01:40,410 fwd                            forward                              37  : Sending msg_id: 3289 from 1147798110 to 1084620412
telegram-fwd-dev_1       | Traceback (most recent call last):
telegram-fwd-dev_1       |   File "telegram_fwd.py", line 99, in <module>
telegram-fwd-dev_1       |     main()
telegram-fwd-dev_1       |   File "telegram_fwd.py", line 95, in main
telegram-fwd-dev_1       |     listen_to_topics()
telegram-fwd-dev_1       |   File "telegram_fwd.py", line 79, in listen_to_topics
telegram-fwd-dev_1       |     channel.start_consuming()
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1756, in start_consuming
telegram-fwd-dev_1       |     self.connection.process_data_events(time_limit=None)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 716, in process_data_events
telegram-fwd-dev_1       |     self._dispatch_channel_events()
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 518, in _dispatch_channel_events
telegram-fwd-dev_1       |     impl_channel._get_cookie()._dispatch_events()
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1385, in _dispatch_events
telegram-fwd-dev_1       |     evt.body)
telegram-fwd-dev_1       |   File "telegram_fwd.py", line 72, in callback
telegram-fwd-dev_1       |     forward(client, json.loads(body), channel_ids)
telegram-fwd-dev_1       |   File "telegram_fwd.py", line 41, in forward
telegram-fwd-dev_1       |     to_peer=client.get_entity(PeerChannel(int(to_id)))
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 460, in __call__
telegram-fwd-dev_1       |     sender, call_receive, update_state, *requests
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 480, in _invoke
telegram-fwd-dev_1       |     sender.send(*requests)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 86, in send
telegram-fwd-dev_1       |     self._send_message(message)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 128, in _send_message
telegram-fwd-dev_1       |     + bytes(message)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/tl_message.py", line 16, in __bytes__
telegram-fwd-dev_1       |     body = GzipPacked.gzip_if_smaller(self.request)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller
telegram-fwd-dev_1       |     data = bytes(request)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/message_container.py", line 17, in __bytes__
telegram-fwd-dev_1       |     ) + b''.join(bytes(m) for m in self.messages)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/message_container.py", line 17, in <genexpr>
telegram-fwd-dev_1       |     ) + b''.join(bytes(m) for m in self.messages)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/tl_message.py", line 16, in __bytes__
telegram-fwd-dev_1       |     body = GzipPacked.gzip_if_smaller(self.request)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/gzip_packed.py", line 22, in gzip_if_smaller
telegram-fwd-dev_1       |     data = bytes(request)
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/functions/messages.py", line 939, in __bytes__
telegram-fwd-dev_1       |     bytes(self.from_peer),
telegram-fwd-dev_1       |   File "/usr/local/lib/python3.6/site-packages/telethon/tl/types/__init__.py", line 9055, in __bytes__
telegram-fwd-dev_1       |     struct.pack('<q', self.access_hash),
telegram-fwd-dev_1       | struct.error: required argument is not an integer
```

**Comment by Lonami** [comment] 2017-10-23 16:04
I guess `access_hash` was set to `None` somehow again. I don't have a way to reproduce this issue yet though.

**Comment by hoatle** [comment] 2017-10-23 16:39
This is my current workaround:

```
def forward(client, update, to_ids):
    """
    Forward an update to channel ids
    See:
        - https://github.com/LonamiWebs/Telethon/wiki/Forwarding-messages
        - https://github.com/LonamiWebs/Telethon/wiki/Retrieving-an-entity
    :param client:
    :param update:
    :param to_ids:
    :return:
    """
    msg_id = update['message']['id']
    from_id = update['message']['to_id']['channel_id']

    #  workaround, this could be very expensive, need to check this to make sure it's fast and cached
    _, entities = client.get_dialogs(limit=None)

    for to_id in to_ids:
        LOGGER.debug(f'Sending msg_id: {msg_id} from {from_id} to {to_id}')
        #  bug:
        #  - https://github.com/LonamiWebs/Telethon/issues/354
        #  - https://github.com/LonamiWebs/Telethon/issues/350
        # client(ForwardMessagesRequest(
        #     from_peer=client.get_entity(PeerChannel(int(from_id))),
        #     id=[msg_id],
        #     to_peer=client.get_entity(PeerChannel(int(to_id)))
        # ))
        client(ForwardMessagesRequest(
            from_peer=_find_entity(from_id, entities),
            id=[msg_id],
            to_peer=_find_entity(to_id, entities)
        ))

        LOGGER.debug(f'[x] msg_id: {msg_id} from {from_id} to {to_id} sent!')
```

**Comment by Ranc58** [comment] 2017-10-23 17:06
I have some problem with sending messages to chats:

dialogs, entities = client.get_dialogs()
```
for entity in entities:
    if 'megagroup' in entity.to_dict():
        try:
            client.send_message(entity, reminder_message)
            print(entity.to_dict()['title'], 'reminder sent')
        except Exception as e:
            print(entity.to_dict()['title'], e)
```
Yes, `access_hash` is `None`.
And each time the error appears on different chats. 
I tried to do it with `while` and on the second iteration all chats have this error `required argument is not an integer`.

**Comment by Ranc58** [comment] 2017-10-23 17:36
Have some problem. Yes, `access_hash` is `none`.
```
dialogs, entities = client.get_dialogs()
for entity in entities:
    if 'megagroup' in entity.to_dict():
        peer = client.get_entity(entity)
        client(SendMessageRequest(peer, reminder_message))
        print(peer.__dict__['title'])
```

**Comment by 88ee55** [comment] 2017-10-25 08:56
hash set none in method get_input_entity
```
        try:
            # First try to get the entity from cache, otherwise figure it out
            return self.session.entities.get_input_entity(peer)
        except KeyError:
            pass
```
this return hash none

PS save_entities = False

**Comment by Lonami** [comment] 2017-11-13 09:48
Actually this issue is just #354 which should be fixed now. By the way @88ee55:
> PS save_entities = False

Not sure how well the library behaves with that, I haven't really used it on a real use case which that flag set to `False`. That basically means `self.session.entities.get_input_entity` won't remember the ID/hash pair, depending on your code, it may or may not work.

**Closed by Lonami** 2017-11-13 09:48 UTC
Labels: waiting-for-submitter
