### ISSUE TITLE
Bug report: Incorrect parameters for MessageEntityMention 

### ISSUE THREAD

**Issue by SMSadegh19** [LonamiWebs/Telethon#3153] opened 2021-09-07 23:38 UTC
Parameters of MessageEntityMention (offset and length) is not correct sometimes!
For example username of mentioned user is `@username`.
the output of `msg.message[offset:offset+length]` sometimes is `@username` or `username` or `username ` or `username\n` or `sername\n\n`.

I don't know why? is it telethon bug?
or people client bug that sends parameters incorrectly?
sometimes maybe a message were edited and entities not been updated.

**Comment by Lonami** [comment] 2021-09-08 12:42
Please provide the `raw_text` and entities that fail. Duplicate of #3106.

**Closed by Lonami** 2021-09-08 12:42 UTC
