### ISSUE TITLE
Current rate limits.

### ISSUE THREAD

**Issue by DeForzo** [LonamiWebs/Telethon#4009] opened 2022-12-28 11:33 UTC
I have looked and searched everywhere to find a simple answer to the question: What are telegrams limits in regards to DM'ing people who are not mutual contacts. 
So I used this library to message people with 30 seconds in between, and after 5 people the well known peer flood error came up.
What is the correct waiting time? Is it 9800 seconds?

**Comment by Lonami** [comment] 2022-12-28 17:45
Limits are unknown and vary under many conditions. Spamming will get the account banned. This is not a bug in Telethon or something I can "fix" so I'm closing the issue.

**Closed as completed by Lonami** 2022-12-28 17:45 UTC
