### ISSUE TITLE
Getting a delay from new message event

### ISSUE THREAD

**Issue by prog-mlml** [LonamiWebs/Telethon#4229] opened 2023-11-01 00:34 UTC
### Code that causes the issue

            SessionName = LilithBO.GetTelegramExtractorObject().GetUserName()
            Client = TelegramClient(session=SessionName,
                                    api_id=LilithBO.GetTelegramExtractorObject().GetApiId(),
                                    api_hash=LilithBO.GetTelegramExtractorObject().GetApiHash()).start(
                phone=LilithBO.GetTelegramExtractorObject().GetPhone())
                
            @Client.on(events.NewMessage(chats=LilithBO.GetTelegramExtractorObject().GetChats()))
            async def TelegramExtractHandleNewMessage(event):

### Expected behavior

When I receive a message from a channel I'm participating in, I would like to receive the message posted immediately.

### Actual behavior

I am receiving the message, but with a delay that can take up to 1 minute

### Telethon version

1.32.0

### Python version

3.11.6

### Operating system (including distribution name and version)

Windows Server 2022

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-11-01 09:19
This is a duplicate of older issues. The TLDR is Telegram is the one who decides how and when to deliver updates.

**Closed as completed by Lonami** 2023-11-01 09:19 UTC
