### ISSUE TITLE
Memory continues to soar after logging in

### ISSUE THREAD

**Issue by xyco66** [LonamiWebs/Telethon#4258] opened 2023-11-22 11:22 UTC
### Describe your suggested feature

I spent half a month reviewing many Github and Telethon documents and couldn't solve this problem with many environments. I am seeking help.

I have 4 accounts, each account has 100 groups. My example is just to stay logged in. Just a login and it will, the memory will increase by 0.03-0.3M every second until the 16G memory is filled up after a few hours.  

This problem is encountered on Windows, but not on Linux. If the account does not have too many groups, it will not appear. I have tried reinstalling python and telethon environments on multiple computers, but it still cannot be solved. I have tried telethon 1.28 - 1.32.1. In addition, there will be a warning Server replied with a wrong session ID. I have already configured Python and Telthon environments on more than 3 computers for testing (the session is also newly generated)

For help I purchased a server with 4 test accounts and simple test code. I hope someone can help me find the problem.

I can provide you with the cloud server address-account number and password

i am willing to pay money ！ My telegram: https://t.me/xyco66

If in doubt, I can buy a new windows2022 server and you can configure the environment yourself

I will wait online, please help me, I am willing to pay you what you want

telegram :@xyco66

I really can't find the problem anymore

Example 1
```

import threading
import asyncio
import os
from telethon import TelegramClient

api_id = '6'
api_hash = 'eb06d4abfb49dc3eeb1aeb98ae0f581e'

def start_client(session_file):
    asyncio.new_event_loop().run_until_complete(perform_qr_login(session_file))

async def perform_qr_login(session_file):
    client = TelegramClient(session_file, api_id, api_hash)
    await client.connect()
    try:
        me = await client.get_me()
        print(f"login ok{session_file}")
        print(me)
    except Exception as e:
        print(f"login {session_file} error: {e}")
    await client.run_until_disconnected()

session_files = [file for file in os.listdir('.') if file.endswith('.session')]
threads = [threading.Thread(target=start_client, args=(session_file,)) for session_file in session_files]
for thread in threads:
    thread.start()

for thread in threads:
    thread.join()

```

-----

Example 2
 
```
import asyncio
import os
from telethon import TelegramClient

api_id = '6'
api_hash = 'eb06d4abfb49dc3eeb1aeb98ae0f581e'
async def perform_qr_login(client):
    await client.connect()
    try:
        me = await client.get_me()
        print("login ok")
        print(me)
    except:
        pass
    await client.run_until_disconnected()
async def main():
    # Get all sessions in the current directory
    session_files = [file for file in os.listdir('.') if file.endswith('.session')]
    if session_files:
        tasks = []
        for session_file in session_files:
            client = TelegramClient(session_file, api_id, api_hash)
            print(f"login {session_file}...")
            task = perform_qr_login(client)
            tasks.append(task)
        # Run all tasks
        await asyncio.gather(*tasks)
    else:
        print("There are no sessions in the current directory")

if __name__ == "__main__":
    asyncio.run(main())
```

This simple was able to run on the test windows server I deployed

What I need to do is a simple login test that requires memory to not grow rapidly

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment] 2023-11-22 17:18
Closing as duplicate of #4213.

**Closed as completed by Lonami** 2023-11-22 17:18 UTC
Labels: enhancement
