### ISSUE TITLE
get_dialogs(limit=None), but it does not return all dialogs

### ISSUE THREAD

**Issue by kingzez** [LonamiWebs/Telethon#711] opened 2018-03-20 09:35 UTC
`__version__ = '0.17.4.3'`

and run your code(https://github.com/LonamiWebs/Telethon/issues/497#issuecomment-357630240)
```
dialogs = client.get_dialogs(limit=None)
print('total:', dialogs.total, '; have:', len(dialogs))
```
the result is 
total: 375 ; have: 160

**Comment by Lonami** [comment] 2018-03-20 09:36
> `__version__ = '0.17.4.3'`

You should upgrade before testing to confirm that it's still relevant.

**Comment by Lonami** [comment] 2018-03-24 12:11
I'm closing this until you try with the latest version, since I can't reproduce.

**Closed by Lonami** 2018-03-24 12:11 UTC

**Comment by SmartManoj** [comment] 2019-01-15 17:33
Version: 1.4.3
total: 478 ; have: 224

**Comment by Lonami** [comment] 2019-01-15 18:52
@SmartManoj you may want to figure out why it "doesn't work" yourself because I'm clueless. Here's the code using raw calls:
https://github.com/LonamiWebs/Telethon/blob/09e58c4e53ec7fef4322dc0e78cfe6c27d786279/telethon/client/dialogs.py#L15-L129

You may want to do the same but yourself and figure out how it can be wrong.

**Comment by SmartManoj** [comment] 2019-01-16 12:06
> @Lonami
> Version: 1.4.3
> total: 478 ; have: 224

PS : In telegram x, at bottom it shows 472 chats

**Comment by Lonami** [comment] 2019-01-17 09:37
Note that the `total` is a number the API returns, so Telegram X may be counting them differently.

**Comment by SmartManoj** [comment] 2019-04-13 13:34
@Lonami  
In Version 1.6.2 , working fine
total: 583 ; have: 583

**Comment by Lonami** [comment] 2019-04-13 15:42
Nice, maybe https://github.com/LonamiWebs/Telethon/commit/968da5f72dfd3e9b114733b80ebe3275f918da15 fixed it, or maybe it was just server side. Who knows.

**Comment by SmartManoj** [comment] 2020-01-19 07:19
total: 1248 ; have: 1147
v1.10.9

**Comment by SmartManoj** [comment] 2020-01-19 07:20
![image](https://user-images.githubusercontent.com/7231077/72676717-3a05ad00-3aba-11ea-8c6b-e24e89af7824.png)

**Comment by Lonami** [comment] 2020-01-19 10:04
@SmartManoj can you install 1.6.2 and see what results you get? I have checked the implementation of `iter_dialogs` more than anything else, and I doubt there is much more I can do about it. I also doubt official clients are able to fetch them all, and if they do, I would love to be shown how they do it.
