### ISSUE TITLE
telethon.errors.rpcerrorlist.UserIdInvalidError #1239

### ISSUE THREAD

**Issue by bilalahmed-125** [LonamiWebs/Telethon#1496] opened 2020-06-30 05:04 UTC
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [ ] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
...

```

**Traceback**
```
Traceback (most recent call last):
  File "code.py", line 1, in <code>

```

**Comment by bilalahmed-125** [comment] 2020-06-30 05:06
This is the error I'm facing while adding members to group from multi accounts.

Traceback (most recent call last):
  File "C:/Users/Hp/PycharmProjects/Telegram Group Members/Test.py", line 138, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "C:\Users\Hp\PycharmProjects\Telegram Group Members\venv\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\Hp\PycharmProjects\Telegram Group Members\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Hp\PycharmProjects\Telegram Group Members\venv\lib\site-packages\telethon\client\users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.UserIdInvalidError: Invalid object ID for a user. Make sure to pass the right types, for instance making sure that the request is designed for users or otherwise look for a different one more suited (caused by InviteToChannelRequest)

**Comment by Lonami** [comment] 2020-06-30 08:39
The checklist items should be checked before posting an issue:
* It's not an issue of the library.
* It's a duplicate of #1237, which you bumped.
* You need to make sure to be using the latest version.
* Additionally, the code you posted is impossible to cause such issue.

Closing as duplicate and not a bug.

**Closed by Lonami** 2020-06-30 08:39 UTC
