### ISSUE TITLE
Downloading is too slow through  Telethon 

### ISSUE THREAD

**Issue by themeswordpress** [LonamiWebs/Telethon#4219] opened 2023-10-03 16:39 UTC
### Code that causes the issue

Dears,

First, Thank you so much for this amazing tool 

I noticed that downloading file through Telethon is too slow 

for example, in same server same network downloading for the file 1 GB takes 10 minutes but in telethon took more than 45 minutes 

Why ??

and is there any workaround? 

BR

### Expected behavior

Downloading is too slow through  Telethon 

### Actual behavior

Downloading is too slow through  Telethon 

### Telethon version

1.30.3

### Python version

3.10

### Operating system (including distribution name and version)

ubuntu 22

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-10-03 17:38
I appreciate the kind words, but this is a duplicate of #4110 and probably a few others. There are no plans for more complicated downloading methods built-in because the bottleneck will always be flood wait errors if we go too fast.

**Closed as completed by Lonami** 2023-10-03 17:38 UTC

**Comment by themeswordpress** [comment] 2023-10-03 18:17
so there is no workaround ? to fix this issue  ?

**Comment by Lonami** [comment] 2023-10-03 18:18
My comment in the linked issue has the one and only recommendation I will suggest to improve the download speed.
