### ISSUE TITLE
telethon.errors.common.TypeNotFoundError

### ISSUE THREAD

**Issue by manojsitapara** [LonamiWebs/Telethon#3019] opened 2021-04-05 10:25 UTC
I am getting following error when new message recieved.

I don't know what is actually causing this error. Can someone please guide me to fix this issue? sometimes it is working and sometimes it completely stopped working.

here is error stack information

`Unhandled error while processing msgs
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 540, in _recv_loop
    await self._process_message(message)
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 555, in _process_message
    await handler(message)
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 644, in _handle_gzip_packed
    message.obj = reader.tgread_object()
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 142, in tgread_object
    return clazz.from_reader(self)
  File "/usr/local/lib/python3.9/site-packages/telethon/tl/types/__init__.py", line 26389, in from_reader
    _update = reader.tgread_object()
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 142, in tgread_object
    return clazz.from_reader(self)
  File "/usr/local/lib/python3.9/site-packages/telethon/tl/types/__init__.py", line 24053, in from_reader
    _webpage = reader.tgread_object()
  File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 140, in tgread_object
    raise error
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 5f07b4bc. Most likely, a TLObject was trying to be read when it
 should not be read. Remaining bytes: b"\xbc\xb4\x07_\x17\x00\x00\x00\x8aB\x80X\xb1\xc2@\x0f\x17https://amzn.to/2PWI8tw8amazon.in/Andrew-Scott-Mens-Nylon-Sneakers/dp/B07B9XQ8HR\x00\x00\x00\x00\x00\x00
\x00\x05photo\x00\x00\x06Amazon\x00!Andrew Scott Men's Nylon Sneakers\x00\x00)\xdd\x88\x92\x00\x00\x00\x00\xec\xab1\x1b\x1d\xec\\S\xb1\x05\xd14\xa9\x08\xb3\x11W\xb8j\x15\xc4\xb5\x1c\x03\x00\x00\x00\x
1b\xb6\xbfw\x01s\x00\x00v\x90\xd6S\x04\x00\x00\x00\x7f\x97}']\x00\x00\x00\xd6\xea\x06\x00\xe2Yh\x8c@L\xc6#Z\x00\x00\x00A\x00\x00\x00\xae\x04\x00\x00\x1b\xb6\xbfw\x01m\x00\x00v\x90\xd6S\x04\x00\x00\x00
\x7f\x97}']\x00\x00\x00\xd5\xea\x06\x00\xd0\xc1\x8f\x11\xf1~\xecu@\x01\x00\x00\xe8\x00\x00\x00\x99+\x00\x00\x1b\xb6\xbfw\x01x\x00\x00v\x90\xd6S\x04\x00\x00\x00\x7f\x97}']\x00\x00\x00\xd4\xea\x06\x00\x
04\x84n\xa1\x8bT\x18\xf2\x8b\x01\x00\x00\x1e\x01\x00\x00\xb5%\x00\x00[\x1b\x01\x00\x01\x00\x00\x00)\xd4j`

**Comment by Lonami** [comment] 2021-04-05 13:05
Duplicate of #3010, #1724, #1429, #1291, and probably more.

**Closed by Lonami** 2021-04-05 13:05 UTC

**Comment by Hnjjjn** [comment] 2023-04-02 21:56
> I am getting following error when new message recieved.
> 
> I don't know what is actually causing this error. Can someone please guide me to fix this issue? sometimes it is working and sometimes it completely stopped working.
> 
> here is error stack information
> 
> `Unhandled error while processing msgs
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 540, in _recv_loop
>     await self._process_message(message)
>   File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 555, in _process_message
>     await handler(message)
>   File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 644, in _handle_gzip_packed
>     message.obj = reader.tgread_object()
>   File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 142, in tgread_object
>     return clazz.from_reader(self)
>   File "/usr/local/lib/python3.9/site-packages/telethon/tl/types/__init__.py", line 26389, in from_reader
>     _update = reader.tgread_object()
>   File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 142, in tgread_object
>     return clazz.from_reader(self)
>   File "/usr/local/lib/python3.9/site-packages/telethon/tl/types/__init__.py", line 24053, in from_reader
>     _webpage = reader.tgread_object()
>   File "/usr/local/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 140, in tgread_object
>     raise error
> telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 5f07b4bc. Most likely, a TLObject was trying to be read when it
>  should not be read. Remaining bytes: b"\xbc\xb4\x07_\x17\x00\x00\x00\x8aB\x80X\xb1\xc2@\x0f\x17https://amzn.to/2PWI8tw8amazon.in/Andrew-Scott-Mens-Nylon-Sneakers/dp/B07B9XQ8HR\x00\x00\x00\x00\x00\x00
> \x00\x05photo\x00\x00\x06Amazon\x00!Andrew Scott Men's Nylon Sneakers\x00\x00)\xdd\x88\x92\x00\x00\x00\x00\xec\xab1\x1b\x1d\xec\\S\xb1\x05\xd14\xa9\x08\xb3\x11W\xb8j\x15\xc4\xb5\x1c\x03\x00\x00\x00\x
> 1b\xb6\xbfw\x01s\x00\x00v\x90\xd6S\x04\x00\x00\x00\x7f\x97}']\x00\x00\x00\xd6\xea\x06\x00\xe2Yh\x8c@L\xc6#Z\x00\x00\x00A\x00\x00\x00\xae\x04\x00\x00\x1b\xb6\xbfw\x01m\x00\x00v\x90\xd6S\x04\x00\x00\x00
> \x7f\x97}']\x00\x00\x00\xd5\xea\x06\x00\xd0\xc1\x8f\x11\xf1~\xecu@\x01\x00\x00\xe8\x00\x00\x00\x99+\x00\x00\x1b\xb6\xbfw\x01x\x00\x00v\x90\xd6S\x04\x00\x00\x00\x7f\x97}']\x00\x00\x00\xd4\xea\x06\x00\x
> 04\x84n\xa1\x8bT\x18\xf2\x8b\x01\x00\x00\x1e\x01\x00\x00\xb5%\x00\x00[\x1b\x01\x00\x01\x00\x00\x00)\xd4j`

![Screenshot_٢٠٢٣٠٤٠٢-١٩٠٦٠٢_Opera.jpg](https://user-images.githubusercontent.com/127774985/229379626-c2c61519-8b4f-4f01-86d1-1315bba82bd0.jpg)

[]()[]()[]()bbbbbbnbb

**Comment by Samjith888** [comment] 2023-04-17 17:26
Getting the same error. 
`ERROR:telethon.network.mtprotosender:Unhandled error while receiving data`

Tried reinstalling telethon, but this didn't solved the issue. @Lonami Not able to find any fix in the links which you suggested above.

**Comment by Lonami** [comment] 2023-04-17 20:40
Please open a new issue, following the template, along with (minimal) code, reproduction steps, and system information.
