### ISSUE TITLE
Process not terminated with SIGINT on Windows

### ISSUE THREAD

**Issue by vzts** [LonamiWebs/Telethon#947] opened 2018-08-06 21:47 UTC
Currently on Windows, because of the bug in Python, SIGINT signals are not caught properly inside asyncio and thus the process can only be terminated with SIGKILL or other signals, which is resulting an ungraceful termination and we cannot do anything after the termination.

### Steps to reproduce

In test.py:
```python
from telethon import TelegramClient 
from telethon import events

  client = TelegramClient("test", some_api_id, some_api_hash).start()

   @client.on(events.NewMessage()) 
async def handler(event): 
      await event.reply("Hello!")   

client.run_until_disconnected() 
print("hi")  // this never gets called
```

Run `python test.py`, process cannot be terminated with "CTRL+C"(SIGINT)

### Reference for bug in asyncio of Python on Windows
https://github.com/python/asyncio/issues/407

### Version
OS: tried on both Windows 7 & 10 x64,
Python: tried on v3.6.6 and v3.7.0 x64
Telethon: latest version on PIP 1.1.1

**Comment by Lonami** [comment] 2018-08-06 21:50
The workaround is [rather ugly](https://stackoverflow.com/a/24775107/4759433)…

```python
def wakeup():
    loop.call_later(0.1, wakeup)

loop = asyncio.SelectorEventLoop()
loop.call_later(0.1, wakeup)
```

And you're saying you're using Python 3.6.6 and 3.7.0, so the:
> A fix has supposedly [made its way into Python 3.5](https://code.google.com/p/tulip/issues/detail?id=191), so hopefully my workaround will be made obsolete by that Python version.

Is either not working at all or didn't make it in? I wonder if there is a better way. I really would rather not have to do this.

**Comment by Lonami** [comment] 2018-08-06 21:53
Perhaps we need to revert this code I [borrowed from PTB](https://github.com/python-telegram-bot/python-telegram-bot/blob/f8a17cddcbe374b95fbc834de5c6f3319a87592b/telegram/ext/updater.py#L499-L514) for updates a while ago:

```python
import signal

stop_signals=(signal.SIGINT, signal.SIGTERM, signal.SIGABRT)
for sig in stop_signals:
    signal.signal(sig, signal_handler)
```

**Comment by vzts** [comment] 2018-08-06 21:53
Yeah, totally agreed... Just wanted to share the symptom that I had just suffered from.
I wish there could be a better way. Maybe there's one.

**Comment by vzts** [comment] 2018-08-06 21:58
Guess it just didn't make it in. As you can see from the comment on the workaround answer.
Oh okay, that's cool. That can be a temporary fix before the bug on python gets fixed.
I'll try with that one. I think we can revert that back if you agree, with the comment telling the purpose.
Thanks for looking into this.

**Comment by vzts** [comment] 2018-08-07 00:17
This is rather tricky... I've been looking into this for a few hours. But no luck, I still don't really know where to stab those code in. Below is what I just did:

Simply adding signal handler on the main thread just didn't work. (with `signal.signal`)
Adding signal handler on the event loop where the connection is handled raises NotImplementedError. (with `add_signal_handler`)

It seems that signal handling in asyncio on windows is just not implemented.
I think we need to revert back the whole `idle()` functionality if we want to overcome the issue.
I've also tried to do this, but back-tracking all the history commits was too difficult.
Could you give me an example of the `idle()` function with the current code?

Or maybe I should just resort to other operating system than Windows.
But I think this is a very basic functionality and also involves some issues with saving the session(if the process gets killed with other than sigint, it seems to corrupt the session and thus making the second execution not run properly(it stucks at `.start()`)), so if the telethon is going to support Windows, this issue definitely should be addressed IMHO.

https://bugs.python.org/issue23057
Here is the bug tracker for the given bug btw. So before the actual bug gets fixed, I'd really love to add a workaround for this one. Please tell me what you think and your suggestions if you have any. Thanks in advance.

**Comment by vzts** [comment] 2018-08-07 00:30
https://vorpus.org/blog/control-c-handling-in-python-and-trio
This article seems to thoroughly address the issue. I'm going to read through this one and let you know. Maybe we should look into how trio has solved the problem.

**Comment by vzts** [comment] 2018-08-07 00:31
I have looked into that, but it doesn't seem to work well with the current code.

**Comment by Lonami** [comment] 2018-08-07 23:27
Seen that article before, I really look up to the Trio team, their ideas are wonderful. Yes, the code has changed quite a bit and cherry picking the commit I mentioned would be a waste of time, better to copy paste the relevant parts and adapt.

**Comment by Lonami** [comment] 2018-08-14 14:56
Can't reproduce the issue under Windows 10 and Python 3.6.5.  <kbd>Ctrl+C</kbd> works as expected.

**Comment by vzts** [comment] 2018-08-15 02:52
Hmm.. Sorry, I haven't had any spare time to look into this. I just let my client to switch to linux and everything worked fine. What architecture did you use for testing? 32bit or 64bit? I used 64bit for testing and windows seems to handle the signal differently on different architecture.

**Comment by Lonami** [comment] 2018-08-15 06:36
Yes, I used 64 bit for testing. I don't mind keeping it open for another while to remind me.

**Comment by Lonami** [comment] 2018-10-05 12:30
https://github.com/LonamiWebs/Telethon/compare/096424ea7809e5512a932c79eff6676695c1d27e...dc7713645329c26b83c38fa0350a69031d81c638 introduced many changes and maybe `asyncio.open_connection()` handles things differently, so I'm closing the issue for now.

**Closed by Lonami** 2018-10-05 12:30 UTC
Labels: can't reproduce
