### ISSUE TITLE
event.answer(url) not working when handled with bot.add_event_handler 

### ISSUE THREAD

**Issue by pdisk** [LonamiWebs/Telethon#4002] opened 2022-12-17 16:49 UTC
`event.answer(url="t.me/botname/start?=hi")` not working when handled with `client.add_event_handler()` to assign event handlers
its working fine when I use `@client.on(event) `(decorator method) instead of `add_event_handler()`

**Traceback**
```
File "C:\Users\..\Python310\lib\site-packages\telethon\client\updates.py", line 467, in _dispatch_update
    await callback(event)
  File "C:\Users\..\event_handlers.py", line 213, in upl
    await e.answer(url=f"https://t.me/{await bot_username(client)}?start=hi")
  File "C:\Users\...\telethon\events\callbackquery.py", line 244, in answer
    return await self._client(
  File "C:\Users\...\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\...\Python310\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.QueryIdInvalidError: The query ID is invalid (caused by SetBotCallbackAnswerRequest)

```

**Comment by Lonami** [comment] 2022-12-17 21:02
`@client.on(...)` simply calls `client.add_event_handler()`:

https://github.com/LonamiWebs/Telethon/blob/508071556579ec1beb51e23b1ccfba13c87ed924/telethon/client/updates.py#L100-L125

Could you post a small code sample needed to reproduce the issue? What steps should I take while running the code to see the behavior you describe?

**Comment by pdisk** [comment] 2023-01-12 13:30
It was because the code was taking a little too much time due to the

**Comment by pdisk** [comment] 2023-01-12 13:32
It's Working when i made a test code but its not working in production with as many as 5bots with 800k users all running on same code 

Maybe its cuz the event is taking too much time to get processed idk

**Comment by Lonami** [comment] 2023-01-14 11:49
I am unable to reproduce this issue (I tried with your URL, and also `t.me/botname?start=hi`, as well as with `https://` before both, but it kept failing with `URL_INVALID`).

I am going to close this under the assumption that the problem was in fact a timeout as you point out (I do get the error you describe if I put a normal `answer('text')`, with a long `asyncio.sleep` just before).

If you manage to reproduce this issue again, have a way for me to reliably trigger the error, and are certain it's not timing out (by noticing that the time between click and response is fast enough), let me know, and we can reopen the issue.

**Closed as completed by Lonami** 2023-01-14 11:49 UTC
