### ISSUE TITLE
error when tring to use client.send_file for multiple photos

### ISSUE THREAD

**Issue by ram-sh** [LonamiWebs/Telethon#1408] opened 2020-03-18 06:19 UTC
Hello,

Using Python 3.7.5 and Telethon 1.11.3.

following the example from [Telethon documentation](https://docs.telethon.dev/en/latest/modules/client.html) 

```
# Albums
await client.send_file(chat, [
    '/my/photos/holiday1.jpg',
    '/my/photos/holiday2.jpg',
    '/my/drawings/portrait.png'
])
```

when trying to send more than one photo using client.send_file i get "Media invalid (caused by SendMultiMediaRequest)" error.

when sending a single photo there is no error:
`await client.send_file(contact, 'http://s3.amazonaws.com/tn1.app/0.png')`

the error occurs when trying to send more than one photo:
`await client.send_file(contact, ['http://s3.amazonaws.com/tn1.app/0.png', 'http://s3.amazonaws.com/tn1.app/2.png'])`

thanks much in advance!
RS

**Comment by Lonami** [comment] 2020-03-18 08:13
Telegram doesn't support sending albums from URLs.

**Comment by ram-sh** [comment] 2020-03-19 14:06
thank you.

**Comment by AlirezaH320** [comment] 2020-08-03 11:29
> Telegram doesn't support sending albums from URLs.

@Lonami I know that Bot API supports it, are you sure that MTProto doesn't support it?

**Comment by Lonami** [comment] 2020-08-03 12:12
I have tried it and it does not work when I tried. Bot API may be downloading and re-uploading behind the scenes which Telethon won't do.

**Comment by ToffeeNeko** [comment] 2021-11-23 18:35
Seems that this problem occur again:

when sending a single photo there is no error:
`await client.send_file(contact, 'http://s3.amazonaws.com/tn1.app/0.png')`

the error occurs when trying to send more than one photo:
`await client.send_file(contact, ['http://s3.amazonaws.com/tn1.app/0.png', 'http://s3.amazonaws.com/tn1.app/2.png'])`

But the error message sent to me is "Media invalid (caused by UploadMediaRequest)" instead of "Media invalid (caused by SendMultiMediaRequest)". 

Could anyone please check what's goion wrong? Thanks so much.

**Comment by mzzsfy** [comment] 2022-03-03 10:06
I queried history, bugs may be here, I am not familiar with Python, can I fix this function as soon as possible?

https://github.com/LonamiWebs/Telethon/commit/72fc8f680817ea067b85c06c2d9223b219fd8f06

**Comment by Lonami** [comment] 2023-04-06 12:39
Closing. Please ping back if the issue still occurs in the current git version.

**Closed by Lonami** 2023-04-06 12:39 UTC
Labels: bug

**Comment by yarodevuci** [comment] 2024-06-28 06:35
Still happens, what was the solution?

**Comment by yarodevuci** [comment] 2024-06-28 06:36
@ram-sh what was the solution?

**Comment by yarodevuci** [comment] 2024-06-28 06:43
@Lonami

**Comment by yarodevuci** [comment] 2024-06-28 06:43
```
            async with bot.action(chat_id, 'document') as action:
                await bot.send_file(chat_id, media_group_urls, progress_callback=action.progress)
```

Media invalid (caused by SendMultiMediaRequest)

What is the limit of image url in the array can be?
