### ISSUE TITLE
client.get_participants(target_group)

### ISSUE THREAD

**Issue by shivaneway** [LonamiWebs/Telethon#3734] opened 2022-02-19 05:45 UTC
**Hi,
 client.get_participants(target_group)  didn't support in development version. Please help to resolve it. I have upgrade master.zip. Waiting for long time for this issue, please provide solution.**

I have upgraded into python3 -m pip install --upgrade https://github.com/LonamiWebs/Telethon/archive/master.zip

Collecting https://github.com/LonamiWebs/Telethon/archive/master.zip
  Downloading https://github.com/LonamiWebs/Telethon/archive/master.zip
     - 545.5 kB 731.9 kB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: rsa in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from Telethon==1.24.0) (4.8)
Requirement already satisfied: pyaes in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from Telethon==1.24.0) (1.6.1)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\admin\appdata\local\programs\python\python39\lib\site-packages (from rsa->Telethon==1.24.0) (0.4.8)

**Comment by shivaneway** [comment] 2022-02-19 05:59
**Even I have removed the aggressive=True, I have below error in development version.**

Traceback (most recent call last):
  File "F:\Freelancer\Passy\Scraper\scraper\script.py", line 53, in <module>
    **all_participants = client.get_participants(target_group)**
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\chats.py", line 224, in _load_next_chunk
    participants = results[i]
TypeError: 'ChannelParticipants' object is not subscriptable

**Comment by vishalsharma9411** [comment] 2022-02-19 12:22
Msg me on telegram @vishalsarma

**Comment by vishalsharma9411** [comment] 2022-02-19 12:56
i have upgraded into masterzip and removed aggresive true and also in devlupment virstion but i am getting errors now i am getting this error sir

from telethon.tl.functions.messages import GetDialogsRequest
ModuleNotFoundError: No module named 'telethon.tl'

**Comment by shivaneway** [comment] 2022-02-19 13:06
> i have upgraded into masterzip and removed aggresive true and also in devlupment virstion but i am getting errors now i am getting this error sir
> 
> from telethon.tl.functions.messages import GetDialogsRequest ModuleNotFoundError: No module named 'telethon.tl'

**Make sure did you import like this

from telethon.sync import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import InputPeerEmpty**

**Comment by vishalsharma9411** [comment] 2022-02-19 13:25
i have uninstall the telethon and reinstall it now it giving this error  i have upgraded into masterzip and removed aggresive true and also in devlupment virstion

    participants = results[i]
TypeError: 'ChannelParticipants' object is not subscriptable

**Comment by shivaneway** [comment] 2022-02-19 13:30
Hi Lonami, 
    Now all are having this same issue, provide solution to resolve this issue in development version. Thank you!

Regards,
Shivaneway

**Comment by vishalsharma9411** [comment] 2022-02-19 13:50
yeah sir Lonami please have a look sir

**Comment by AtlantisDe** [comment] 2022-02-19 17:46
+1

**Comment by Lonami** [comment] 2022-02-20 08:51
Duplicate of #928. Please follow the issue template.

**Closed** 2022-02-20 08:50 UTC

**Comment by vishalsharma9411** [comment] 2022-02-20 10:29
> Duplicate of #928. Please follow the issue template.

sir its not solved there tooo and you closed that template without solving sir its not solved there

**Comment by Lonami** [comment] 2022-02-21 08:27
The issue will be solved in the development version once the next version is released.
