### ISSUE TITLE
Unable to recieve api access code while running on AWS EC2 instance

### ISSUE THREAD

**Issue by selfishhari** [LonamiWebs/Telethon#1448] opened 2020-04-29 16:35 UTC
**Checklist**
* [ maybe] The error is in the library's code, and not in my own.
* [yes ] I have searched for this issue before posting it and there isn't a duplicate.
* [yes ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

I am facing this only in amazon EC2 instance. I am prompted to input my phonenumber, followed by code that I recieve. **However I never got the code on my phone.** Even after several tries. But the exact same process and a fresh local instance of Ubuntu is running fine. As in I am able to recieve the code.
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Code that causes the issue**
```python
from telethon.sync import TelegramClient

client = TelegramClient('anon', API_ID,  API_HASH)

with client as client:
    client.loop.run_until_complete(client.send_message('me', 'Hello, myself!'))

...

```

**Output**
```
Please enter your phone (or bot token): 91xxxxxxxxxx
Please enter the code you received: 

```

The exact same code runs well in my local machine with Ubuntu OS.

**Comment by Lonami** [comment] 2020-04-29 17:01
This is being reported a lot lately and unfortunately I don't think there is anything we can do. Quoting [a message on the official chat](https://t.me/TelethonChat/207473):

> apparently it mostly fails for indian users, but works if they try at 3:00 am local time

**Comment by selfishhari** [comment] 2020-04-29 22:01
I found a workaround:

Since it runs on local machine. I copied the generated session file from local machine to my cloud working directory. All seems to be working fine after that. :)

**Comment by Lonami** [comment] 2020-04-29 22:34
Yeah I guess I'll close this since it's not really actionable. At least people searching for the issue will come across this workaround.

**Comment by phanirithvij** [comment] 2020-07-06 19:20
Quoting https://t.me/TelethonChat/230667
> Where is the session file located on a windows machine and where should it be in a linux machine?
> ...
> in the same directory where your py file is
> the file you execute

**Comment by Lonami** [comment] 2020-07-28 17:06
Reopening because there *might* be a way to solve this, but I have no idea how.

**Comment by spencescu** [comment] 2020-07-30 13:43
I have the same issue - code runs fine on my local machine (in Greece) but when I installed the code in AWS I do not receive a login code. However, if using a telegram account with a US phone number it works perfectly OK. 
So the issue is caused by the telegram account country != country where the code runs

**Comment by intereal** [comment] 2020-08-10 03:49
@spencescu @selfishhari, can you give logs about this issue? For debugging, append this at file begging:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by Lonami** [comment] 2020-08-10 08:55
There are some extra logs in the linked #1504.

**Comment by osamajameelahmad** [comment] 2020-09-10 12:30
Hello @selfishhari 
I am facing a similar problem I copied the session file from my local pc to aws ec2 but after few hours session terminates due to security reasons by telegram of usage of the session on 2 different IPs.

I have spent hours on finding the fix do you have any fix for this problem?

Osama

**Comment by LeonardoRick** [comment] 2020-09-25 23:19
Happening with me too. I don't know if it's worth mention but I used python-telegram library a couple times and I had no problem with that. I was having a problem to receive updates from all channels over that API, and telethon solved that for me. But at that time I never had a problem with receveing telegram access code. Do you guys think it's worth to see how it's maded there?

**Comment by osamajameelahmad** [comment] 2020-09-26 07:01
I have added some logs inside the telethon library and checked printed the response of the send_otp API call it turns out on AWS-EC2 the response says my mobile number not even registered on telegram but it works perfectly on my local my this issue is still not resolved.

**Comment by LeonardoRick** [comment] 2020-09-26 15:58
I don't think it's a country problem. I'm from Brazil and my EC2 instance is on my region. What else could cause your phone to appear as not registered?

**Comment by LorenzHW** [comment] 2020-09-27 19:58
Same problem for AWS lambda functions. In my case it does not matter whether I send the code to a European number or to an American one. It is never received. The session file also does not seem to be the issue, since I store the session information inside DynamoDB which will get accessed as well when I execute the code locally (when executing the code locally everything works as expected).

**Comment by LeonardoRick** [comment] 2020-09-30 02:58
@selfishhari, I tried your temporary workaround and I'm receveing this error now:
`Error: telethon.errors.rpcerrorlist.AuthKeyDuplicatedError: The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used. Use the same session exclusively, or use different sessions (caused by InvokeWithLayerRequest)`
Did you ever get this error?

**Comment by giltal1** [comment] 2020-10-04 11:28
Found the bug source!

Apparently, there is a bug when using IPv6 which prevents the verification code from being sent. the issue was addressed on v1.16.1 but seems like it doesn't help
https://docs.telethon.dev/en/latest/misc/changelog.html#bug-fixes-v1-16-1

My solution to the problem is to add False to the ipv6 flag like this:
`client = TelegramClient(session_file_path, API_ID, API_HASH, use_ipv6=False)`

**Comment by Lonami** [comment] 2020-10-04 12:20
No IPv6 is the default, though:

https://github.com/LonamiWebs/Telethon/blob/3e188d0344651e83ee7a73f6506d0214035cfa1f/telethon/client/telegrambaseclient.py#L216

**Comment by LeonardoRick** [comment] 2020-10-13 03:23
@giltal1 It worked for me too. I don't know if it's consistent but this simple change maded it sent the code for the first time

**Comment by LeonardoRick** [comment] 2020-10-16 22:35
@LorenzHW pyrogram uses GNU Lesser General Public License which I think do not allow comercialization. Telethon is the most complete free to use Telegram API written in python and would be awsome to go on on this issue. Is there a way to see what [pyrogram](https://github.com/pyrogram/pyrogram/) or [python-telegram](https://github.com/alexander-akhmetov/python-telegram) does so we could do the same here?

**Comment by delivrance** [comment] 2020-10-16 22:47
> @LorenzHW pyrogram uses GNU Lesser General Public License which I think do not allow comercialization. Telethon is the most complete MIT Telegram API written in python and would be awsome to go on on this issue. Is there a way to see what [pyrogram](https://github.com/pyrogram/pyrogram/) or [python-telegram](https://github.com/alexander-akhmetov/python-telegram) does so we could do the same here?

Hi, @Lonami pinged me about this. It's true that pyrogram is currently licensed

**Comment by delivrance** [comment] 2020-10-16 22:51
> @LorenzHW pyrogram uses GNU Lesser General Public License which I think do not allow comercialization. Telethon is the most complete MIT Telegram API written in python and would be awsome to go on on this issue. Is there a way to see what [pyrogram](https://github.com/pyrogram/pyrogram/) or [python-telegram](https://github.com/alexander-akhmetov/python-telegram) does so we could do the same here?

Hi, @Lonami pinged me about this. It's true that pyrogram is currently licensed under LGPL, but this doesn't mean you can't use it commercially. In fact, you can use and integrate Pyrogram into your own code — either open source, under the same or a different license, or even proprietary with any purpose whatsoever — without being required to release the source code of your own applications. However, any derivative work or modification to the library *itself* is required to be published for free under the same LGPLv3+ license.

**Comment by yekrangian** [comment] 2020-10-17 08:51
@selfishhari in the past a few days I was dealing with the same issue. Interestingly enough my code worked on day one on AWS and on the second day stoped working!!! 

I believe I have found the root cause. The issue is with not having the NTP (Network Time Protocol) and TimeZone properly set up on the server-side which I'm going to describe it based on my scenario.

The only thing that we always miss to compare between dev and test or prod environment is the local time of our machines especially when we move our app to the cloud. 

When I tested my code for the very first time, I tested on my AWS machine which worked just fine but on the second day of my testing, I decided to do it on my local machine and of course, I received the verification code but when I moved back to my AWS server things started acting strange!!!

The catch was my local zone was based on US Central (America/Chicago) and when I moved my code to my AWS the time zone of my server was UTC. Based on my past experience I have seen REST APIs get confused when they see the authentication requests coming from a different time. (one request is coming from the current time and one request coming from the future). 

The best way to avoid this type of situation is to use one standard time zone (e.g. UTC or Local Time Zone ) in both Dev and Test/Prod environments and that was exactly what I did. 

On my AWS machine, I synced my server with NTP and changed the time zone from UTC to America/Central and everything started working again. 

Here is the link for AWS NTP: 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

And here is the Linux command for setting up the right time zone:

$ timedatectl list-timezones
$ timedatectl list-timezones | grep Chicago
$ sudo timedatectl set-timezone America/Chicago

**Comment by LeonardoRick** [comment] 2020-10-17 23:16
@yekrangian awesome debug and you went one step further setting NTP, but it's still not working for me.

I had already settled my timezone because I'm from Brazil so it's intuitive for me to update that. I taught that this NTP configuration was the gap, but I think it's something else in my situation. 

Please let us know if anyone had fixed the problem with those two steps. Would be nice to compare another locations.

**Comment by yekrangian** [comment] 2020-10-18 16:04
@LeonardoRick also please make sure your time zone on your AWS machine is the same as your local (where you are developing the code).  

once you ensured that all your environments have the same time zone, run your code where you always run and get the verification code, and next run the same code in your other environment.

**Comment by LeonardoRick** [comment] 2020-10-20 14:04
**AWS selected Server**
![image](https://user-images.githubusercontent.com/17517057/96595578-31007100-12c2-11eb-9196-8a7a07566f45.png)


**timedatectl**
```
leonardo@ip-xxx-xx-xx-xxx:~$ timedatectl
                      Local time: Tue 2020-10-20 10:57:55 -03
                  Universal time: Tue 2020-10-20 13:57:55 UTC
                        RTC time: Tue 2020-10-20 13:57:56
                       Time zone: America/Sao_Paulo (-03, -0300)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no

```

``
**chronyc sources -v**
```
leonardo@ip-xxx-xx-xx-xxx:~$ chronyc sources -v
  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current synced, '+' = combined , '-' = not combined,
| /   '?' = unreachable, 'x' = time may be in error, '~' = time too variable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
^* 169.254.169.123               3   4   377    15    -29us[  -33us] +/-  483us
^- pugot.canonical.com           2  10   377   912  -2273us[-2297us] +/-  127ms
^- chilipepper.canonical.com     2  10   377   513    -85us[  -89us] +/-  131ms
^- golem.canonical.com           2  10   377   723   +562us[ +581us] +/-  133ms
^- alphyn.canonical.com          2  10   377   201   -246us[ -249us] +/-  137ms
^- a.ntp.br                      2  10   377   403   -107us[ -108us] +/- 5019us
^- time.cloudflare.com           3  10   377   958   -145us[ -139us] +/-   67ms
^- ntp1.ifsc.usp.br              2  10   377   616   +269us[ +280us] +/- 7578us
^- 45.11.105.223                 2  10   377   278    +36us[  +37us] +/- 3899us
```

**chronyc tracking**
```
leonardo@ip-xxx-xx-xx-xxx:~$ chronyc tracking
Reference ID    : A9FEA97B (169.254.169.123)
Stratum         : 4
Ref time (UTC)  : Tue Oct 20 13:53:08 2020
System time     : 0.000000886 seconds slow of NTP time
Last offset     : -0.000001058 seconds
RMS offset      : 0.000003360 seconds
Frequency       : 23.756 ppm slow
Residual freq   : -0.001 ppm
Skew            : 0.046 ppm
Root delay      : 0.000407746 seconds
Root dispersion : 0.000270084 seconds
Update interval : 16.3 seconds
Leap status     : Normal
```
@yekrangian I really don't know what I'm missing. The only weird thing for me is this `chronyc tracking` output that is showing a different UTC as ref time. Should this be different? I found NO where saying how to change this so I taught that maybe it's just the NTP server location or something like that. 

Besides that, I really don't know what else to do. I even tried multiple times to send the code running on my machine and try it on server before that but it's not working too.

Thanks a lot for helping.

**Comment by yekrangian** [comment] 2020-10-20 15:30
@LeonardoRick NTP is separate from the time zone. 
NTP will synchronize your machine's time based on whatever time zone you set. From what I see your NTP service on your AWS is up and synced. 

Now you need to make sure your AWS machine is set with the same time zone as your development machine where you can run the code successfully. 

For example, I live in the US Central Zone, and as you can see my both machines Local times are set in the same time zone (CDT)

![image](https://user-images.githubusercontent.com/66852880/96607913-70c55980-12be-11eb-9d63-2f56068ce68b.png)

![image](https://user-images.githubusercontent.com/66852880/96608416-f943fa00-12be-11eb-9e42-4b6e76555994.png)

**Comment by yekrangian** [comment] 2020-10-20 16:34
@LeonardoRick NTP service is separate from the time zone.
NTP will synchronize your machine's time based on whatever time zone you set. From what I see your NTP service on your AWS is up and synced.

Now you need to make sure your AWS machine time zone is set with the same time zone as your development machine where you can run the code successfully.

My local development machine where I was able to run my code successfully: 

![image](https://user-images.githubusercontent.com/66852880/96615988-9e62d080-12c7-11eb-8e8a-45b04986194e.png)

![image](https://user-images.githubusercontent.com/66852880/96616044-b20e3700-12c7-11eb-9079-1c803f434ea3.png)

My AWS Server

![image](https://user-images.githubusercontent.com/66852880/96616438-319c0600-12c8-11eb-9d55-c678dc0d884f.png)

**Comment by LeonardoRick** [comment] 2020-10-20 20:26
My local machine
![image](https://user-images.githubusercontent.com/17517057/96638700-f1a04780-12f6-11eb-882f-69256ad9b585.png)

timedatecrl on server
![timedatectl](https://user-images.githubusercontent.com/17517057/96640185-30370180-12f9-11eb-9324-afa2ef16d2ef.jpg)


date on server (i took 2 min to take the other screenshot)
![date](https://user-images.githubusercontent.com/17517057/96640179-2e6d3e00-12f9-11eb-80a8-199c36eea497.jpg)

@yekrangian can you see something missing?

**Comment by AndreaHasani** [comment] 2020-12-16 12:42
I think this has to do with ip adress from telegram side. 
I have encountered this problem a few times and my fix has always been to switch servers. I run a server clouster and if an issue like this arises i just switch telethon host. 

Probably would work even if we just switched the ip, never tried though

**Comment by Lonami** [comment] 2021-01-24 09:51
As pointed out by @avidale, it might be a good idea to document this:

> And if this restriction does really exist, maybe it should be reflected in Telethon documentation? Because the documentation creates the impression that the methods such as `TelegramClient.send_code_request` do work wherever they are called, and it turns out to be not so.

It's hard to tell if there would be any way to circumvent this, but this seems to be enough evidence that sending the code works just fine, but Telegram ignores it when used in certain locations. If someone wants to send a PR for this I'd appreciate.

**Comment by avidale** [comment] 2021-01-24 10:28
BTW, for me (#1680) authorization started working  when I ran it on the Yandex.Cloud platform in my country (Russia). 
Which reinforces the hypothesis that Telegram requires location of the server to match the locale of the phone used for authorization.

**Comment by Lonami** [comment] 2021-01-24 10:36
Note that you can tell Telethon to use a different locale when you create the client. Has anyone tried to play with these parameters?

**Comment by prashantsengar** [comment] 2021-03-15 05:47
I have never faced the issue with the client being in a different location. I live in UTC+0530 and have used different cloud providers to run my client and have always received the code. The cloud instances are hosted at UTC-5 and UTC. I have even had some other people from different time zones login to their telegram accounts from the same server instances.

**Comment by Lonami** [comment] 2021-05-09 00:17
Closing since I don't think I can do much about it on the Telethon side (but if anyone figures out some trick to make it work, I'll gladly review the pull request).

**Closed by Lonami** 2021-05-09 00:17 UTC
