### ISSUE TITLE
sign_up no longer works

### ISSUE THREAD

**Issue by Spartaques** [LonamiWebs/Telethon#4063] opened 2023-03-19 10:19 UTC
I use my code from previous version that looks like this:

`user = await client.sign_up(
            code=activationCode,
            first_name=randomFirstName,
            last_name=randomLastName,
            phone=phone,
            phone_code_hash=codeRequest.phone_code_hash
        )`

and i constantly get error: 

telethon.errors.rpcerrorlist.PhoneCodeInvalidError: The phone code entered was invalid (caused by SignInRequest)

my phone is:
6285876697247

Help pls fix this error after update..

**Comment by Lonami** [comment] 2023-03-19 10:25
Duplicate of #4050.

**Closed as completed by Lonami** 2023-03-19 10:25 UTC
