### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'messages'

### ISSUE THREAD

**Issue by chabanovsky** [LonamiWebs/Telethon#47] opened 2017-04-09 09:43 UTC
Got the following error a few times

```
Traceback (most recent call last):
  File "site/my_app.py", line 109, in <module>
    watch_telegram()
  File "site/my_app.py", line 94, in watch_telegram
    client.get_content(channels, telegram_on_message_callback)
  File "/path/to/my_app/chats/telegram/telegram.py", line 58, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_client.py", line 340, in get_message_history
    total_messages = getattr(result, 'count', len(result.messages))
```

> AttributeError: 'NoneType' object has no attribute 'messages'

I initialise my example exactly the same as it happens in the `InteractiveTelegramClient`. The `get_content`  method is an equivalent run. (Basically the same code)

**Comment by Lonami** [comment] 2017-04-09 09:50
Does this happen after a while or always inmediatly? It's probably related to #22.

**Comment by chabanovsky** [comment] 2017-04-09 09:59
It happens after some time. There is no pattern. I pull the `get_history` of some chats rooms once per 10 seconds. In request I send `min_id`. I work only with channels. (By the way, could you tell me please if there is a better way to get _new_ messages from a channel).

**Comment by Lonami** [comment] 2017-04-09 10:02
> By the way, could you tell me please if there is a better way to get new messages from a channel

I don't know why new messages on channels aren't received through the updates. Same with supergroups (I think they're treated as channels too?). Not sure how the original clients do it, but I bet that you'll get a notification if you're mentioned. I'd say it's server side.

**Comment by Lonami** [comment] 2017-04-09 11:17
Could you please try using the upstream version of Telethon and run your program with the `--telethon-log=DEBUG`? Then paste a [gist](https://gist.github.com).

**Comment by chabanovsky** [comment] 2017-04-09 11:23
Sure! I did. (Thank your the mentioning about subscribing for the updates. I setup the filtering and it works.) 

As soon as the error occur I'll report the dump.

**Comment by Lonami** [comment] 2017-04-09 11:28
> As soon as the error occur I'll report the dump.

What should happen is "Message ack confirmed a request". This causes the request you sent to be "confirmed", and exists the `.receive()` loop, without actually reading a `.result`, thus it's `None`. I'm not sure how to handle these ack requests.

They're only useful when logging out as far as I know, because no result is actually sent back; but since I wasn't sure whether that request (logging out request) was special, I decided to generalize the `acks_confirm` thing.

So, if you confirm that the problem is this (the ack confirmed your request), would you mind trying to delete the `request.confirm_received = True`? Since this bug happens only "sometimes" I have no reliable way to test it myself, but you (and other people) using it for "real" things seem to encounter this often enough…

Also, no need to paste the full log, only the last lines of it (100 or so perhaps).

**Comment by chabanovsky** [comment] 2017-04-09 12:04
It looks like there are two places with the line `confirm_received = True`.  If I change all of them to False or comment I get the following exceptions


```
Traceback (most recent call last):
  File "/development/Telethon/telethon/network/tcp_client.py", line 80, in read
    partial = self.socket.recv(left_count)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site/rudevs.py", line 112, in <module>
    watch_telegram()
  File "site/rudevs.py", line 82, in watch_telegram
    client = WatchTelegramClient()
  File "/development/rudevs/chats/telegram/telegram.py", line 23, in __init__
    self.connect()
  File "/development/Telethon/telethon/telegram_client.py", line 113, in connect
    layer=layer, query=query))
  File "/development/Telethon/telethon/telegram_client.py", line 167, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 138, in receive
    seq, body = self.transport.receive(timeout)
  File "/development/Telethon/telethon/network/tcp_transport.py", line 40, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/development/Telethon/telethon/network/tcp_client.py", line 92, in read
    'The read operation exceeded the timeout.')
TimeoutError: The read operation exceeded the timeout.
```

**Comment by Lonami** [comment] 2017-04-09 12:43
> If I change **all** of them to False or comment […]

Sorry, not all of them. Only the ack one (on [this](https://github.com/LonamiWebs/Telethon/blob/f24d4f4a0e629d65d19b9e37d03efdfa6cd07b57/telethon/network/mtproto_sender.py#L235) line.)

**Comment by chabanovsky** [comment] 2017-04-10 04:53
During the night got the following but there was no any kind of additional information. I run my app with `--telethon-log=DEBUG`. Could you please tell me if I should call anything additionally to provide the log?

```
  File "site/rudevs.py", line 112, in <module>
    watch_telegram()
  File "site/rudevs.py", line 97, in watch_telegram
    client.get_content(channels, telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 58, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 353, in get_message_history
    total_messages = getattr(result, 'count', len(result.messages))
AttributeError: 'NoneType' object has no attribute 'messages'
```

**Comment by pazis** [comment] 2017-04-10 04:55
@chabanovsky your `result` variable has no attribute `messages` as the error indicates. You can wrap your code in `try: ... except: ...` block.

**Comment by chabanovsky** [comment] 2017-04-10 05:00
Hey @pazis! Thank you for the reply! I seems it would not be a good solution since (1) it should not have happened and we want to investigate what is wrong (2) this is an exception that happens in the library code.

**Comment by pazis** [comment] 2017-04-10 05:08
@chabanovsky This kind of error (and similar ones) happens a lot in my code. Yes it should not have happened! I would be very happy if someone fix it. It would help a lot.

Here is a few sample of my log of other similar exceptions:

```
check = client.invoke(ImportChatInviteRequest(link))
check.chats[0].megagroup
....
'NoneType' object has no attribute 'chats'
'NoneType' object has no attribute 'megagroup'
```

**Comment by Lonami** [comment] 2017-04-10 07:16
I could actually workaround this…

**Comment by chabanovsky** [comment] 2017-04-10 07:20
@Lonami  If we want handle this on the library code level (not on the protocol level) would it be better to use `hasattr` and `not None` than `try: ... except:`?

**Comment by Lonami** [comment] 2017-04-10 07:22
@chabanovsky, `max_tries=3`, `if request.result is None` then `self.invoke(request)`

**Comment by chabanovsky** [comment] 2017-04-10 07:26
@Lonami  Could you please tell me where exactly I should add these lines?

**Comment by Lonami** [comment] 2017-04-10 07:28
> Only the ack one (on [this](https://github.com/LonamiWebs/Telethon/blob/f24d4f4a0e629d65d19b9e37d03efdfa6cd07b57/telethon/network/mtproto_sender.py#L235) line).

Note that calls to `log_out()` will fail with this line commented.

**Comment by chabanovsky** [comment] 2017-04-11 04:52
Got the following error

```

WARNING:root:Message ack confirmed a request
WARNING:root:Read RPC error: (RPCError(...), 'A wait of 16 seconds is required.')
Should wait 16s. Sleeping until then.
Exception in thread Updates thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 408, in updates_thread_method
    self.send_ping()
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 84, in send_ping
    self.receive(request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 138, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 221, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 281, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 243, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 256, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 100, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 62, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 363, in get_message_history
    add_offset=add_offset))
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 181, in invoke
    return self.invoke(request, timeout, throw_invalid_dc, tries - 1, expect_result)
  File "/development/Telethon/telethon/telegram_client.py", line 179, in invoke
    raise ValueError('The result of the invoked request is always None')
ValueError: The result of the invoked request is always None
```

**Comment by chabanovsky** [comment] 2017-04-11 09:44
Just updated and got the following error (with `request.confirm_received = True` commented)

```
WARNING:root:Read RPC error: (RPCError(...), 'A wait of 7 seconds is required.')
Should wait 7s. Sleeping until then.
Exception in thread Updates thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 438, in updates_thread_method
    reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 250, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 263, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 100, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 62, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 361, in get_message_history
    add_offset=add_offset))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 250, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 263, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 100, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 62, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 366, in get_message_history
    total_messages = getattr(result, 'count', len(result.messages))
AttributeError: 'NoneType' object has no attribute 'messages'
```

**Comment by Lonami** [comment] 2017-04-11 09:47
> Just updated and got the following error (with `request.confirm_received = True` commented)

No need to comment it anymore, since only the logout request can be confirmed via `ack`.

I assume you're trying to receive messages *from* the updates thread, right? For some reason it didn't sleep. **Please**, it would be really helpful if you got `--telethon-log=DEBUG` working…

**Comment by chabanovsky** [comment] 2017-04-11 10:14
@Lonami I uncommented the line. Could you please take a look at an error long

```
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
WARNING:root:Read RPC error: (RPCError(...), 'A wait of 16 seconds is required.')
Should wait 16s. Sleeping until then.
INFO:root:Request result received
DEBUG:root:receive() released the lock
Exception in thread Updates thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 420, in updates_thread_method
    self.send_ping()
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 87, in send_ping
    self.receive(request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 100, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 62, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 366, in get_message_history
    total_messages = getattr(result, 'count', len(result.messages))
AttributeError: 'NoneType' object has no attribute 'messages'
```

**Comment by Lonami** [comment] 2017-04-11 10:23
Strange. As you can see, the `.receive()` method acquires the lock, sleeps and releases it:
```
[!!] DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
WARNING:root:Read RPC error: (RPCError(...), 'A wait of 16 seconds is required.')
[!!] Should wait 16s. Sleeping until then.
INFO:root:Request result received
[!!] DEBUG:root:receive() released the lock
```

The updates thread can't do, in theory, any work until the `.receive()` releases the lock. By the time this happens, the "Should wait 16s" part should have set
`self.updates_thread_sleep = error.additional_data` (which is the time to sleep).

After this is set, the updates thread will meet the condition of `self.updates_thread_sleep` being set, thus `sleep(self.updates_thread_sleep)`. So, this shouldn't have at all happened.

Can you please try replacing:
```python
            if self.updates_thread_running:
                if self.updates_thread_sleep:
                    sleep(self.updates_thread_sleep)
                    self.updates_thread_sleep = None
                else:
                    # Longer sleep if we're not expecting updates (only pings)
                    sleep(0.1 if self.on_update_handlers else 1)
```
with:
```python
            if self.updates_thread_running:
                # Longer sleep if we're not expecting updates (only pings)
                sleep(0.1 if self.on_update_handlers else 1)
```
, and replacing:
```python
                with self.lock:
                    Log.d('Updates thread acquired the lock')
```
with:
```python
                with self.lock:
                    if self.updates_thread_sleep:
                        sleep(self.updates_thread_sleep)
                    Log.d('Updates thread acquired the lock')
```

This is only a guess, sorry :(

**Comment by chabanovsky** [comment] 2017-04-11 12:17
I did as you said. Here is the log. Could you please take a look at it.

```
DEBUG:root:Handling update for object updates_tg#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:date seq:int = Updates
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:Handling update for object updates_tg#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:date seq:int = Updates
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
DEBUG:root:Reading request response
INFO:root:Request result received
DEBUG:root:receive() released the lock
DEBUG:root:send() acquired the lock
DEBUG:root:send() released the lock
DEBUG:root:receive() acquired the lock
INFO:root:Trying to .receive() the request result...
DEBUG:root:Handling RPC result, request is not None
WARNING:root:Read RPC error: (RPCError(...), 'A wait of 16 seconds is required.')
Should wait 16s. Sleeping until then.
INFO:root:Request result received
DEBUG:root:receive() released the lock
Exception in thread Updates thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 418, in updates_thread_method
    self.send_ping()
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 87, in send_ping
    self.receive(request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 90, in sync_telegram
    channels = self.update_telegram_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 73, in update_telegram_channels
    channels = self.get_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 51, in get_channels
    dialogs, entities = self.get_dialogs(self.dialog_count)
  File "/development/Telethon/telethon/telegram_client.py", line 301, in get_dialogs
    limit=count))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 90, in sync_telegram
    channels = self.update_telegram_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 73, in update_telegram_channels
    channels = self.get_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 51, in get_channels
    dialogs, entities = self.get_dialogs(self.dialog_count)
  File "/development/Telethon/telethon/telegram_client.py", line 301, in get_dialogs
    limit=count))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 90, in sync_telegram
    channels = self.update_telegram_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 73, in update_telegram_channels
    channels = self.get_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 51, in get_channels
    dialogs, entities = self.get_dialogs(self.dialog_count)
  File "/development/Telethon/telethon/telegram_client.py", line 301, in get_dialogs
    limit=count))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 90, in sync_telegram
    channels = self.update_telegram_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 73, in update_telegram_channels
    channels = self.get_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 51, in get_channels
    dialogs, entities = self.get_dialogs(self.dialog_count)
  File "/development/Telethon/telethon/telegram_client.py", line 301, in get_dialogs
    limit=count))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 90, in sync_telegram
    channels = self.update_telegram_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 73, in update_telegram_channels
    channels = self.get_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 51, in get_channels
    dialogs, entities = self.get_dialogs(self.dialog_count)
  File "/development/Telethon/telethon/telegram_client.py", line 301, in get_dialogs
    limit=count))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 90, in sync_telegram
    channels = self.update_telegram_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 73, in update_telegram_channels
    channels = self.get_channels()
  File "/development/rudevs/chats/telegram/telegram.py", line 51, in get_channels
    dialogs, entities = self.get_dialogs(self.dialog_count)
  File "/development/Telethon/telethon/telegram_client.py", line 301, in get_dialogs
    limit=count))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 141, in receive
    request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 224, in process_msg
    return self.handle_container(msg_id, sequence, reader, request)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 287, in handle_container
    if not self.process_msg(inner_msg_id, sequence, reader, request):
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 249, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 262, in handle_update
    handler(tlobject)
  File "/development/rudevs/chats/telegram/telegram.py", line 70, in <lambda>
    self.add_update_handler(lambda x: self.update_handler(x, self))
  File "/development/rudevs/chats/telegram/telegram.py", line 175, in update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 157, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 100, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 62, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 366, in get_message_history
    total_messages = getattr(result, 'count', len(result.messages))
AttributeError: 'NoneType' object has no attribute 'messages'
```

It looks like a recursion. Maybe this is my failure?

**Comment by Lonami** [comment] 2017-04-11 13:43
> It looks like a recursion

It does, you're calling `add_update_handler` a lot. You are not adding update handlers from the updates thread, are you? You should be careful with this kind of stuff (sending a message from updates -> receives a reply -> sends another -> receives -> sends…).

**Comment by chabanovsky** [comment] 2017-04-11 15:21
I am not. I add a handler once when the app starts. But from the update_handler the app sends other requests to servers. If I try to start a new thread in the update_handler, I get all the time the following

```

Traceback (most recent call last):
  File "/development/Telethon/telethon/network/tcp_client.py", line 80, in read
    partial = self.socket.recv(left_count)
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/development/rudevs/chats/telegram/telegram.py", line 183, in threaded_update_handler
    lisntener.on_new_message(user, message, channel)
  File "/development/rudevs/chats/telegram/telegram.py", line 159, in on_new_message
    self.sync_telegram()
  File "/development/rudevs/chats/telegram/telegram.py", line 102, in sync_telegram
    self.get_content(channels, self.telegram_on_message_callback)
  File "/development/rudevs/chats/telegram/telegram.py", line 64, in get_content
    entity, limit=self.message_count, min_id=entity.min_id)
  File "/development/Telethon/telethon/telegram_client.py", line 361, in get_message_history
    add_offset=add_offset))
  File "/development/Telethon/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/development/Telethon/telethon/network/mtproto_sender.py", line 136, in receive
    seq, body = self.transport.receive(timeout)
  File "/development/Telethon/telethon/network/tcp_transport.py", line 40, in receive
    packet_length_bytes = self.tcp_client.read(4, timeout)
  File "/development/Telethon/telethon/network/tcp_client.py", line 92, in read
    'The read operation exceeded the timeout.')
TimeoutError: The read operation exceeded the timeout.

```

**Comment by Lonami** [comment] 2017-04-11 15:44
I'm sorry but I'm really clueless 😔

**Comment by chabanovsky** [comment] 2017-04-11 16:23
@Lonami I do apologise about that. I will not bother anymore.

**Comment by chabanovsky** [comment] 2017-04-12 04:52
@Lonami, thank you for the fix. My app worked all night without any exceptions with the fixes you provided above. 

PS It seems it might be a good idea to add current time to the log output. I could not understand what was the last message from the telegram servers that my app received. It looked it was waiting for messages but did not receive anything in the same time in web interface it looked that there were updates. I cannot tell since what moment it happened.

**Comment by Lonami** [comment] 2017-04-12 07:56
> PS It seems it might be a good idea to add current time to the log output.

**Yes**, I was surprised when the default log didn't have it 😅. I will add the time and close this issue if everything is fixed then :)

**Closed by Lonami** 2017-04-12 07:56 UTC
