### ISSUE TITLE
client.get_participants(group, aggressive=True) telethon.errors.common.MultiError FloodWaitError

### ISSUE THREAD

**Issue by ddbbqqpp** [LonamiWebs/Telethon#3718] opened 2022-02-11 11:13 UTC
client.get_participants(group, aggressive=True) 报错 telethon.errors.common.MultiError FloodWaitError
不是账号的问题，之前是没问题的
替换方案：
https://telethonn.readthedocs.io/en/latest/extra/examples/chats-and-channels.html
如果成员比较多，会执行比较慢，但是可以解决这个问题

  from telethon.tl.functions.channels import GetParticipantsRequest
  from telethon.tl.types import ChannelParticipantsSearch
  from time import sleep
  
  offset = 0
  limit = 100
  all_participants = []
  
  while True:
      participants = client(GetParticipantsRequest(
          channel, ChannelParticipantsSearch(''), offset, limit,
          hash=0
      ))
      if not participants.users:
          break
      all_participants.extend(participants.users)
      offset += len(participants.users)

**Comment by striller17** [comment] 2022-02-11 11:59
I have a full solution text me on my telegram @NGenOwn

**Comment by Lonami** [comment] 2022-02-11 14:30
Duplicate of #928. Please follow the issue template.

**Closed by Lonami** 2022-02-11 14:30 UTC
Labels: enhancement

**Comment by Creampanda** [comment] 2022-03-20 18:30
I have solved this problem guys
/lib/python3.8/site-packages/telethon/client/chats.py 
```
    async def _load_next_chunk(self):
        import time
        time.sleep(32)
```
add sleep method between loading chunks
and change max chunk size in same file (i make 2000 and it worked for me)
`_MAX_PARTICIPANTS_CHUNK_SIZE = 2000`
