### ISSUE TITLE
Can't upload large file because  FLOOD_PREMIUM_WAIT_9 (caused by SaveFilePartRequest) keeps interrupting the upload

### ISSUE THREAD

**Issue by doublep21** [LonamiWebs/Telethon#4419] opened 2024-07-25 11:36 UTC
### Code that causes the issue

await client.send_file(
                    forward,
                    filepath,
                    thumb=thumb,
                    caption=caption,
                    force_document=False,
                    silent=True,
                    progress_callback=lambda x, y: progress_bar(x, y, file),
                    attributes=[
                        DocumentAttributeVideo(duration, videohw[0], videohw[1], False, supports_streaming=True)
                    ]
                )

### Expected behavior

upload a file even if i have to wait for cooldown

### Actual behavior

the upload stops and i need to restart it in a infinite loop

### Traceback

An error occurred: RPCError 420: FLOOD_PREMIUM_WAIT_9 (caused by SaveBigFilePartRequest)

### Telethon version

1.36.1

### Python version

3.8

### Operating system (including distribution name and version)

debian 10

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by doublep21** [comment] 2024-07-25 11:38
Will Telegram be slowing connections to stimulate Premium purchases?
Latest Telegram iOS sources revealed a new server error prefix [FLOOD_PREMIUM_WAIT](https://github.com/TelegramMessenger/Telegram-iOS/blob/6547328217b8289bf226ca3b568d32123f4db4ec/submodules/MtProtoKit/Sources/MTRequestMessageService.m#L811)

When server returns this error, Telegram will show an alert with an offer to subscribe to Premium and make your network requests faster.

**Comment by Lonami** [comment] 2024-07-25 14:30
Duplicate of #4417.

**Closed as completed by Lonami** 2024-07-25 14:30 UTC
