### ISSUE TITLE
SSL issues (Unknown error on the read thread, please report)

### ISSUE THREAD

**Issue by stonemonk** [LonamiWebs/Telethon#482] opened 2017-12-09 08:45 UTC
Been using Telethon for 1 month and regularly get errors like this using Python 3.6 on macOS and Ubuntu:

```
Unknown error on the read thread, please report
Traceback (most recent call last):
  File "/Users/x/devel/x/.venv/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 858, in _recv_thread_impl
    self.idle(stop_signals=tuple())
  File "/Users/x/devel/x/.venv/lib/python3.6/site-packages/telethon/telegram_bare_client.py", line 835, in idle
    self._sender.receive(update_state=self.updates)
  File "/Users/x/devel/x/.venv/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 120, in receive
    message, remote_msg_id, remote_seq = self._decode_msg(body)
  File "/Users/x/devel/x/.venv/lib/python3.6/site-packages/telethon/network/mtproto_sender.py", line 170, in _decode_msg
    message = plain_text_reader.read(msg_len)
  File "/Users/x/devel/x/.venv/lib/python3.6/site-packages/telethon/extensions/binary_reader.py", line 66, in read
    .format(length, len(result), repr(result), repr(self._last))

BufferError: No more data left to read (need 951562959, got 160: b'%{$\xa5\x9e\xf1\x9e\xa8d@\x9cG\xc2\xabt\xc9*B\xc3\x91St\x99=\x17\x17\xbe\x01\xfd:1\tO<_Z[H\xb4\x8d\xf7\xd1\xba\x11\x87B\xd7\xcf\xe5\xf6X\xf3\xf6Gd\x88=\xbf\x1a\xb9\xfb\x004c\xc3\xcd\xfe\xe5,\xe2\xc6\xe5{!\xc2$\x9f4m\xab7h@L\x96\xd6\x9e\xdd\xb3\x08BE\xbe\x16g\tw[_{6:\xdc\x07U\xb7\x98\x92\xa9\x93\xb7sX\xaa\x1f\xa7\xa1\xae\xc7\xfa\x83Q\xde\xfa\xca\ny\x93\x12\xb1\x9a\x8f:\x08&\x18\xbe\xe2=\\\xfaz*v[H:\xda\xf7\xf5\xd9\x8b\xd0\x111$\xd0\xa9O\xfb'); last read b'\xcf\xb2\xb78'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/aes/aes_ige.c(86): OpenSSL internal error, assertion failed: (length % AES_BLOCK_SIZE) == 0
```

As this occurs on a BG thread and not on the main thread where I am invoking Telethon calls, I have no way to catch this Exception and prevent it from crashing my program.  Thus making Telethon non-viable from my program.

**Comment by Lonami** [comment] 2017-12-27 15:37
> ```
> need 951562959, got 160
```

That's strange. Some object must have been read strangely hence causing the rest to be "corrupted". Can you reproduce consistently?

**Comment by stonemonk** [comment] 2018-01-08 05:33
My program keeps a telegram session active all the time, and I see this crash randomly every 1-2 weeks. If there is a way for me to provide you with more information, let me know..

**Comment by stonemonk** [comment] 2018-01-08 05:36
But considering that you are managing BG threads in the library, it would be nice if you could just catch all exceptions (`BaseException`), and send them to consumer code via an API, `handle_exception(exc)` to let the consumer decide what to do for the default case that you don't already handle it in some sane way.

**Comment by Lonami** [comment] 2018-01-08 11:32
I try to do that:
https://github.com/LonamiWebs/Telethon/blob/46b088d44c14e856c045e2330a7da5b95881afd6/telethon/telegram_bare_client.py#L889

https://github.com/LonamiWebs/Telethon/blob/46b088d44c14e856c045e2330a7da5b95881afd6/telethon/telegram_bare_client.py#L428-L429

Please let me know if there is a better way. `handle_exception(exc)` would be called from the library background thread, and I'm not sure this is desirable either.

**Comment by stonemonk** [comment] 2018-01-08 12:30
Ahh, thanks, I didn't see that before.  Either approach would work for me personally (BG thread callback, or save and raise).

But you are only catching certain exceptions, whereas I would propose catching all (`BaseException`) since any uncaught exception will kill that BG thread anyway, at least sending it to consumer, there might be something the consumer can do.  In my case, I am already catching any unexpected exception and destroy/re-create the entire telethon session.

In this case, it appears to be a BufferError but I am pretty sure I saw another case where it caused an AssertionError. If I am understanding your code right, it only sets and raises `socks.GeneralProxyError, socks.ProxyConnectionError`.

**Comment by stonemonk** [comment] 2018-01-08 12:39
Didn't look at your code long enough. If I understand now, it reports only the socks errors, but ignores other exceptions and continues to loop calling idle().

So maybe it is just logging that BufferError to console but in fact continuing to work. Hrmm, I need to wait for it to happen again I guess. I thought it was actually causing my program to terminate but now I am not sure (working on too many projects simultaneously).

**Comment by Lonami** [comment] 2018-02-23 11:38
I'll close this since [`cryptg`](https://github.com/Lonami/cryptg) is now a thing. Upgrade and if you can consistently reproduce somehow let me know.

**Closed by Lonami** 2018-02-23 11:38 UTC
