### ISSUE TITLE
RuntimeError: coroutine ignored GeneratorExit

### ISSUE THREAD

**Issue by superarray** [LonamiWebs/Telethon#3846] opened 2022-06-06 13:45 UTC
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran ` pip3 install  git+https://github.com/LonamiWebs/Telethon.git@v1.24` and triggered the bug in the latest version.

**The latest version I installed today
I use this command install** 

```python
pip3 install  git+https://github.com/LonamiWebs/Telethon.git@v1.24
```

Python Version:
```
Python 3.9.6 (default, Jun  1 2022, 00:13:07) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-13)] on linux
```

**Code that causes the issue**
```python

try:
    ...
except:
    ...
finally:
     **await client_disconnect(client)**

async def client_disconnect(client):
    try:
        await client.disconnect()
    except Exception as e:
        logger.info("Disconnect Exception:{}".format(str(e)))
...

```

**Traceback**
```
2022-06-06 19:23:17,418-[Line:1738]-[Func:default_exception_handler]-[Level:ERROR] : Task was destroyed but it is pending!
task: <Task pending name='Task-44' coro=<test_task() running at /usr/telethontest.py:69> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f8eae36ab50>()]>>


Traceback (most recent call last):
  File "/usr/telethontest.py", line 387, in client_disconnect
    await client.disconnect()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 649, in _disconnect_coro
    await self._disconnect()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/telegrambaseclient.py", line 696, in _disconnect
    await self._sender.disconnect()
  File "/usr/local/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 147, in disconnect
    await self._disconnect()
RuntimeError: coroutine ignored GeneratorExit

```

**I don't know why I get this kind of error
Previously running Telethon V1.24 official release on Python 3.6
no such error**

**This problem happened by accident, so I don't know what caused it**
--------------------------------------

**Comment by Lonami** [comment] 2023-01-14 12:21
I am unable to reproduce this issue on my Windows 10 machine, with Python 3.10.4, on commit d81eb0b2e8121f68bf91ae66477b2d7c52b607fc. I am going to close this under the assumption that the problem lies in one of the `except` from the user code and not Telethon itself (therefore, there is nothing for me to fix in Telethon).

If you are still able to reliably trigger this error, please let me know, along with instructions, so that I can reproduce it myself, and try to solve it. Otherwise I could try with remote access.

**Closed as completed by Lonami** 2023-01-14 12:21 UTC

**Comment by Tanzin01** [comment] 2023-05-13 15:31
Same error!

**Comment by ChinaTengFei** [comment] 2023-11-02 05:26
@Lonami It seems to be related to the proxy

**Comment by igorivaniuk** [comment] 2024-01-10 10:40
Maybe same problem
```
Exception ignored in: <coroutine object Connection._recv_loop at 0x7f16d37e5d40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/typing.py", line 272, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
RuntimeError: coroutine ignored GeneratorExit
```

**Comment by aleksgrz** [comment] 2024-06-15 11:57
`bot = TelegramClient('anon', APP_ID, APP_HASH).start(bot_token=BOT_TOKEN)`

In my case the problem was in 'anon', before I was changed this variable to another one. So keep 'anon' or check that APP_ID or APP_HASH is correct.

**Comment by aleksgrz** [comment] 2024-06-15 12:26
You have multiple session started. 
`client = TelegramClient(sessionId, APP_ID, APP_HASH)` 
The first parameter here is the session id. So you can see the files in your project folder something like <session_id>.session

See the links below to understand how to manage it 
https://docs.telethon.dev/en/stable/quick-references/faq.html#sqlite3-operationalerror-database-is-locked
https://docs.telethon.dev/en/stable/concepts/sessions.html#sessions

So you can test it. For example before the running script, change 1st parameter and you will see new file .session will be generated.

**Comment by wzyustc** [comment] 2024-09-12 10:38
> @Lonami似乎和代理有关

请问您现在解决了这个问题吗，或者应该用什么样的代理呢
