### ISSUE TITLE
I was banned while using this library.

### ISSUE THREAD

**Issue by skhaz** [LonamiWebs/Telethon#4264] opened 2023-12-04 18:21 UTC
### Code that causes the issue

I wrote a simple script that downloads a user's photo. It worked the first time I ran it, but when I tried to run it again, I was logged out of Telegram, and when I tried to log in again, Telegram said my number was banned.

### Expected behavior

Not being banned.

### Actual behavior

Got banned.

### Telethon version

1.33.0

### Python version

3.10.12

### Operating system (including distribution name and version)

macOS 14.1.1

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-12-04 18:33
Duplicate of #824.

**Closed as completed by Lonami** 2023-12-04 18:33 UTC
