### ISSUE TITLE
AttributeError: 'TelegramClient' object has no attribute 'invoke'

### ISSUE THREAD

**Issue by Adreaming5101** [LonamiWebs/Telethon#3207] opened 2021-11-19 04:42 UTC
**Checklist**
* [ ] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
client = TelegramClient(session, api_id, api_hash, proxy=("socks5", "127.0.0.1", 1080)).start()

if client.is_connected():
    async def main():
        contact = InputPhoneContact(client_id=0, phone="+86xxxx", first_name="xx", last_name="xx")
        print(contact)
        result = client.invoke(ImportContactsRequest([contact]))
        print(result)
```

**Comment by Lonami** [comment] 2021-11-19 07:08
Duplicate of #1491.

**Closed by Lonami** 2021-11-19 07:08 UTC
