### ISSUE TITLE
Can't decode packet (b'l\xfe\xff\xff')

### ISSUE THREAD

**Issue by pazis** [LonamiWebs/Telethon#59] opened 2017-04-24 07:34 UTC
I get `Can't decode packet (b'l\xfe\xff\xff')` after running:

`client = TelegramClient(session_file, api_id=000, api_hash='XXX')`
`client.connect()`

my code stops here. When I Ctrl+C here is the output:

```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "kim.py", line 122, in connect_to_telegram
    client.connect()
  File "/root/anaconda3/lib/python3.5/site-packages/telethon/telegram_client.py", line 118, in connect
    layer=layer, query=query))
  File "/root/anaconda3/lib/python3.5/site-packages/telethon/telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "/root/anaconda3/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 135, in receive
    message, remote_msg_id, remote_sequence = self.decode_msg(body)
  File "/root/anaconda3/lib/python3.5/site-packages/telethon/network/mtproto_sender.py", line 186, in decode_msg
    raise BufferError("Can't decode packet ({})".format(body))
BufferError: Can't decode packet (b'l\xfe\xff\xff')
```

This happens for one of my SIMs.

**Comment by Lonami** [comment] 2017-04-24 07:55
Duplicate of #7, unless you didn't get any exception before?

**Comment by Lonami** [comment] 2017-05-02 14:27
I will close this since it's a duplicate. I managed to corrupt my file somehow so I will take a look at it when I have time.

**Closed by Lonami** 2017-05-02 14:27 UTC
