### ISSUE TITLE
Errors when handling NewMessage events

### ISSUE THREAD

**Issue by abk000** [LonamiWebs/Telethon#4088] opened 2023-04-13 04:05 UTC
I am using Telethon 1.28.2 for a simple program that handles NewMessage events from Telegram channels.

The general structure is this and it is running on my own dev computer for now (Mac OS):

```
from telethon import TelegramClient, events, sync

api_id = '<my_api_id>'
api_hash = '<my_api_hash>'

client = TelegramClient('session_name', api_id, api_hash)
client.start()

list_of_chats = ['11111', '222222']    

@client.on(events.NewMessage(chats=list_of_chats)):
    # application logic

client.run_until_disconnected()
```

The program ran fine for weeks until recently (last few days) where I've noticed some error messages. They occur sometimes (roughly 90% of the time the program works as expected) and include some sequence of the following:

> Server sent a very old message with ID ###################, ignoring (see FAQ for details)

> Security error while unpacking a received message: Too many messages had to be ignored consecutively

> Unhandled error while receiving data
> Traceback (most recent call last):
>   File "../venv/lib/python3.9/site-packages/telethon/network/mtprotosender.py", line 505, in _recv_loop
>     body = await self._connection.recv()
>   File "../venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 301, in recv
>     raise err
>   File "../venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 332, in _recv_loop
>     data = await self._recv()
>   File "../venv/lib/python3.9/site-packages/telethon/network/connection/connection.py", line 369, in _recv
>     return await self._codec.read_packet(self._reader)
>   File "../venv/lib/python3.9/site-packages/telethon/network/connection/tcpfull.py", line 25, in read_packet
>     packet_len_seq = await reader.readexactly(8)  # 4 and 4
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 721, in readexactly
>     raise exceptions.IncompleteReadError(incomplete, n)
> asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 8 expected bytes
> Server closed the connection: 0 bytes read on a total of 8 expected bytes

I have reviewed similar questions as well as the FAQ (https://docs.telethon.dev/en/stable/quick-references/faq.html#what-does-server-sent-a-very-new-message-with-id-mean) that provides common root causes. However:

- Automatically setting date and time is enabled on my computer, so I don't see how it could be a time zone issue.
- I am not using any sort of proxy.
- This is a small personal use script, so having multiple shared sessions could not be the issue. I do have a separate process that uses the same API credentials, but the session name is different, so I don't think that is causing a conflict.
- I've tried deleting the session file and re-authenticating but I'm experiencing the issue again.

Any suggestions on what could be causing this? If it is a Telegram server or Telethon issue that I cannot control, what would be the best way to handle failure to receive an expected message in my application code?

**Comment by Polaris-d** [comment] 2023-04-13 07:54
I also encountered the same problem on linux platform,by reading the source code I found that this is an exception that is caught and handled.
The processing method is to record the exception and reconnect
```python
self._log.exception('Unhandled error while receiving data')
self._start_reconnect(e)
return
```
I think this is because the author has dealt with the exceptions that have not been encountered before. But I don't have a deep enough understanding of the underlying telegram interface, otherwise I will try to handle this new exception and submit a PR

**Comment by possibilities** [comment] 2023-04-14 21:51
I can confirm this is happening to me also since I pulled yesterday. Also on linux. Things still seem to work OK and I don't appear to be missing any events when this error occurs.

**Comment by Lonami** [comment] 2023-04-14 23:15
I don't recall ever experiencing either of:

> Server sent a very old message with ID ###################, ignoring (see FAQ for details)
>
> Security error while unpacking a received message: Too many messages had to be ignored consecutively

myself, and therefore, I can only speak from experience about why *other* people *seemed* to face this error. Those causes are documented in the FAQ. Because there isn't really a way for me to reproduce the error, I can't really investigate why it happens. So if you're experiencing it, I encourage you to investigate, maybe use `git bisect` to find "when it broke", and share your findings with others so that we everyone else can avoid it in the future.

With that said, as I've explained many times before, this is unlikely to be something that can be fixed from the Telethon side. But by all means feel free to try, and perhaps there is a solution after all. I, like many others, are not affected, so it's hard for us to track down the cause. It's very probably Telegram or network related though.

**Comment by possibilities** [comment] 2023-04-15 14:13
@Lonami This one seems new but I'm unsure if it's distinct from the issues you are saying you've never experienced and can't investigate.

> Server closed the connection: 0 bytes read on a total of 8 expected bytes

Edit: Going to start working on git bisecting it but it can take a long time for it to happen

**Comment by possibilities** [comment] 2023-04-15 17:03
Looks like it happens at almost exactly the 2 minute mark:

https://github.com/LonamiWebs/Telethon/commit/68ea208b4378263d2e04abd8357fe957770ec620

```
▶ g bisect good
68ea208b4378263d2e04abd8357fe957770ec620 is the first bad commit
commit 68ea208b4378263d2e04abd8357fe957770ec620
Author: Kacnep89 <76146578+Kacnep89@users.noreply.github.com>
Date:   Tue Mar 28 22:00:36 2023 +0500

    Periodically save update state (#4071)

 telethon/client/telegrambaseclient.py | 25 ++++++++++++++-----------
 telethon/client/updates.py            |  2 ++
 2 files changed, 16 insertions(+), 11 deletions(-)
 ```
 
Edit 1: Initially being unfamiliar with the project and code it doesn't help me much but I'll try to understand it. Let me know if there's anything more I can do to help understand the problem, thanks!
 
 Edit 2: I'm pretty green here so not sure what to do but I did try subscribing to raw messages hoping this error would correspond to some event. Unfortunately, there doesn't seem to be any correlation with any events.

**Comment by Lonami** [comment] 2023-04-15 19:59
It would be surprising if the commit you linked truly is responsible for causing "Server closed the connection". There might indeed be a delay every now and then (because committing the sqlite database is relatively slow), but it should not have a noticeable impact in the network itself. What happens if you comment out the calls to `_save_states_and_entities`? Does it still happen? If yes, then that commit is unlikely to be what's causing the issue.

**Comment by possibilities** [comment] 2023-04-15 20:16
No sorry, I am only experiencing:

> Server closed the connection: 0 bytes read on a total of 8 expected bytes

I will try what you suggest and report back when I can.

**Comment by possibilities** [comment] 2023-04-15 20:35
Yeah, you're right, commenting out those calls does not make the error go away. I'll try git bisecting again. I must have had a false positive on one of the steps.

**Comment by possibilities** [comment] 2023-04-15 20:36
FWIW I definitely don't get the error on daf21f12d9c183351fef8e10373a13aa6f51f191 but always get it after 2 minutes on HEAD. I'll report back ASAP. Would it be better if I created a new issue only for `Server closed the connection: 0 bytes read on a total of 8 expected bytes`?

**Comment by Lonami** [comment] 2023-04-16 07:48
You can use a new issue if you prefer.

**Comment by possibilities** [comment] 2023-04-16 16:23
I bisected again waiting a full 5 minutes before marking a commit good and ended up here:

https://github.com/LonamiWebs/Telethon/commit/acd3407418b28f4fce33cf820629ed6bc3b2da88

```
▶ g bisect bad
acd3407418b28f4fce33cf820629ed6bc3b2da88 is the first bad commit
commit acd3407418b28f4fce33cf820629ed6bc3b2da88
Author: Lonami Exo <totufals@hotmail.com>
Date:   Sun Mar 12 17:43:19 2023 +0100

    Propagate errors at the connection level

 telethon/network/connection/connection.py | 56 ++++++++++++++-----------------
 1 file changed, 25 insertions(+), 31 deletions(-)
```

After about 2 minutes I see:
```
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
```

Then after another 1 minute:

```
Unhandled exception from recv_loop_handle after cancelling <class '_asyncio.Task'> (<Task finished name='Task-6' coro=<MTProtoSender._recv_loop() done, defined at /home/mike/src/Telethon/telethon/network/mtprotosender.py:495> exception=IncompleteReadError('0 bytes read on a total of 8 expected bytes')>)
Traceback (most recent call last):
  File "/home/mike/src/Telethon/telethon/helpers.py", line 176, in _cancel
    await task
  File "/home/mike/src/Telethon/telethon/network/mtprotosender.py", line 505, in _recv_loop
    body = await self._connection.recv()
  File "/home/mike/src/Telethon/telethon/network/connection/connection.py", line 301, in recv
    raise err
  File "/home/mike/src/Telethon/telethon/network/connection/connection.py", line 332, in _recv_loop
    data = await self._recv()
  File "/home/mike/src/Telethon/telethon/network/connection/connection.py", line 369, in _recv
    return await self._codec.read_packet(self._reader)
  File "/home/mike/src/Telethon/telethon/network/connection/tcpfull.py", line 25, in read_packet
    packet_len_seq = await reader.readexactly(8)  # 4 and 4
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 8 expected bytes
```

**Comment by Lonami** [comment] 2023-04-29 10:50
Before that commit, the `connection.py` disconnected on any error:

https://github.com/LonamiWebs/Telethon/blob/f3414d134a88d139b8506dee871f7d70f4b8fa99/telethon/network/connection/connection.py#L303

When that happens, any `IOError` could then be caught and `start_reconnect` would be called:

https://github.com/LonamiWebs/Telethon/blob/f3414d134a88d139b8506dee871f7d70f4b8fa99/telethon/network/mtprotosender.py#L506-L509

After that commit, the only thing that really changed is how the error is put:

https://github.com/LonamiWebs/Telethon/blob/acd3407418b28f4fce33cf820629ed6bc3b2da88/telethon/network/connection/connection.py#L333-L335

and then returned:

https://github.com/LonamiWebs/Telethon/blob/acd3407418b28f4fce33cf820629ed6bc3b2da88/telethon/network/connection/connection.py#L299-L301

but it's pretty much the same. The handling of `IOError` has not really changed:

https://github.com/LonamiWebs/Telethon/blob/acd3407418b28f4fce33cf820629ed6bc3b2da88/telethon/network/mtprotosender.py#L506-L509

*Maybe* it's because `read` is called after disconnection occurs.

**Comment by simbadmorehod** [comment] 2023-05-09 07:23
I will try to add my problem, as I recently moved to a more powerful Linux server and moved all the project files that were in the archive of the previous server.

Now the bot periodically misses new messages `@client.on(events.NewMessage(chats=[-100123456789])) async def my_event_handler(event):`

I am running multiple sessions at the same time in asynchronous mode, everything worked fine before, I read on the internet that it could be a problem with the server time and the account session files, but I doubt this is true.

Error: `` Security error while unpacking a received message: too many messages had to be ignored one after another Server sent a whole new message with ID ************, ignored ``.

@Lonami give me some food for thought, I want to fix the problem, and the main thing is that I skipped some messages through the bot (while I figure out the reason)


UP: Rebooting the server fixed the error problem and messages are normally processed by all accounts.

**Comment by Lonami** [comment] 2023-05-09 20:10
Recent versions of the library should detect gaps in updates and recover from those (as implemented in `messagebox.py`). You said it's working, so it shouldn't be necessary, but if you wanted to record a trace of the updates (to diagnose what's being received and handled and how), here's the:

<details><summary>Instructions to record updates trace</summary>

Install the development version with

```
pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip
```

and configure `logging` with something like this:

```python
import logging
logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s', level=logging.WARNING)
logging.getLogger('telethon.messagebox').setLevel(logging.NOTSET + 1)
```

(You can configure it to your liking, but the `messagebox` level must be as low as possible. If you have multiple `TelegramClient`, please set a different `base_logger='name'` for each in their constructor).

This will print all updates being processed along with the current state of the `MessageBox` (which deals with the updates).

**This log will contain sensitive information**, so you should only share it with people you trust (or redact it before sharing it). You can [send it to me privately](https://t.me/Lonami) so that I and nobody else can analyze it (please link to this issue, so I know you're not spam).

</details>

But anyway given that:

> UP: Rebooting the server fixed the error problem and messages are normally processed by all accounts.

then there's no problem. I think I'll close this in favor of  #4106.

**Closed as completed by Lonami** 2023-05-09 20:10 UTC

**Comment by speauty** [comment] 2024-01-08 02:06
so reboot server can fix this problem?

**Comment by simbadmorehod** [comment] 2024-01-09 16:09
> so reboot server can fix this problem?

It's worth a try

**Comment by speauty** [comment] 2024-01-11 01:37
> > so reboot server can fix this problem?
> 
> It's worth a try

I tried, but it wasn't much use, after a while, it was like that again, so must to restart that program again

**Comment by gurungsid941** [comment] 2024-09-26 22:48
anyone find a solution to this issue? I am having this issue very frequently. I tried re-running the script and it works ok for a little while before coming into the issue again. I am using a number of asynchronous processes, I wonder whether that could be causing the issues.
