### ISSUE TITLE
Couldn't scrape members

### ISSUE THREAD

**Issue by diri23** [LonamiWebs/Telethon#3709] opened 2022-02-08 13:23 UTC
[!] Couldn't scrape members
[!] ([FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), None, None, None, FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 31 seconds is required (caused by GetParticipantsRequest)')], [None, None, None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x00000202ADE56DF0>, <telethon.tl.types.channels.ChannelParticipants object at 0x00000202ADE6B6D0>, <telethon.tl.types.channels.ChannelParticipants object at 0x00000202ADE60D00>, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE60640>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE60C10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE60CD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE608B0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE60F40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE60FD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65190>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65310>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE653D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65490>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65550>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE659D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65A90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65CD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65D90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65E50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000202ADE65F10>])

**Comment by Thoufak** [comment] 2022-02-08 13:34
**Don't use aggressive=True**

This feature was using a hack which allowed extracting more thank 10k members from a chat. It's already removed from the master branch, and as far as I understand, it will not be implemented again.

Furthermore, according to one of the Telegram devs it can get your account banned.
![image](https://user-images.githubusercontent.com/40132582/152997527-9ad3ad70-0ac9-4d4b-9fef-7f52c082761b.png)

Please stop opening similar issues. Respect the library devs.

**Comment by Lonami** [comment] 2022-02-08 20:43
Duplicate of recent issues.

**Closed by Lonami** 2022-02-08 20:43 UTC

**Comment by cortex06** [comment] 2022-02-12 00:18
Hello @Lonami, sorry where is the original topic about this issues ?

**Comment by yihalem123** [comment] 2022-02-12 06:19
Solved. DM me on telegram @yihalemm

**Comment by Lonami** [comment] 2022-02-12 08:05
#928.
