### ISSUE TITLE
Invalid buffer Invalid response buffer (HTTP code 429)

### ISSUE THREAD

**Issue by mortezanabavi** [LonamiWebs/Telethon#3944] opened 2022-10-04 12:01 UTC
my code :

```
async def main():
    while True:
        bots = query(f"SELECT * FROM `ads` WHERE `time` < {int(time.time())}")
        if len(bots) > 0:
            for bot in bots:
                t = int(time.time()) + 2400
                id = bot[0]
                hash = bot[1]
                admin = bot[9]
                type = bot[2]
                adminn = query(f'SELECT * FROM `bots` WHERE `id`={id}')
                if len(adminn) < 1 or adminn[0][11] != admin:
                    update_database(f"DELETE FROM `ads` WHERE `id` = {id}")
                    continue
                admindata = query(f"SELECT * FROM `data` WHERE `id` = {admin}")
                account = admindata[0][8]
                if str(account) == 'unlimited' or str(account) == 'free' or int(time.time()) - int(account) >= 2592000:
                    update_database(f"DELETE FROM `ads` WHERE `admin` = {admin}")
                    continue
                
                update_database(f"UPDATE `ads` SET `time` = {t} WHERE `Hash` = '{hash}'")
                try:
                    mybot = TelegramClient(StringSession(get_string(id)), api_id, api_hash, receive_updates=False)
                    await mybot.connect()
                    async for dialog in mybot.iter_dialogs(limit=None):
                        try:
                            if dialog.is_group:
                                await asyncio.sleep(1)
                                if type == 'forward':
                                    await mybot.forward_messages(entity=dialog.id, from_peer=await mybot.get_entity(bot[5]), messages=int(bot[4]))
                                elif type == 'send':
                                    await mybot(ForwardMessagesRequest(to_peer=dialog.id, from_peer=bot[5], id=[int(bot[4])], drop_author=True))
                        except errors.FloodWaitError as e:
                            if e.seconds > 1200:
                                t = int(time.time()) + e.seconds
                                update_database(f"UPDATE `ads` SET `time` = {t} WHERE `Hash` = '{hash}'")
                                break
                            else:
                                break
                        except errors.MessageIdInvalidError:
                            update_database(f"DELETE FROM `ads` WHERE `Hash` = '{hash}'")
                            break
                        except errors.ChatWriteForbiddenError:
                            await mybot(LeaveChannelRequest(dialog.id))
                            continue
                        except (errors.AuthKeyUnregisteredError, errors.UserDeactivatedBanError, errors.UserDeactivatedError, errors.SessionExpiredError, errors.SessionRevokedError, ValueError, EOFError):
                            update_database(f"DELETE FROM `ads` WHERE `id` = {id}")
                            break
                        except:
                            continue
                    await mybot.disconnect()
                except (errors.AuthKeyUnregisteredError, errors.UserDeactivatedBanError, errors.UserDeactivatedError, errors.SessionExpiredError, errors.SessionRevokedError, ValueError, EOFError):
                    update_database(f"DELETE FROM `ads` WHERE `id` = {id}")
                    continue
                except:
                    continue
        else:
            await asyncio.sleep(20)


asyncio.run(main())
```

result after one hour :

Invalid buffer Invalid response buffer (HTTP code 429)
Invalid buffer Invalid response buffer (HTTP code 429)
Invalid buffer Invalid response buffer (HTTP code 429)
Invalid buffer Invalid response buffer (HTTP code 429)
Invalid buffer Invalid response buffer (HTTP code 429)

What should i do?

**Comment by Lonami** [comment] 2022-10-04 12:29
Duplicate of #3854.

**Closed as not planned by Lonami** 2022-10-04 12:29 UTC

**Comment by mortezanabavi** [comment] 2022-10-04 12:48
I saw this , but how should fix that. is there any way?

**Comment by Lonami** [comment] 2022-10-04 13:18
All that is known is described in the linked issue. If a solution isn't described it's because it is not known yet.
