### ISSUE TITLE
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)')

### ISSUE THREAD

**Issue by kthenurseone** [LonamiWebs/Telethon#3710] opened 2022-02-08 16:37 UTC
![image](https://user-images.githubusercontent.com/54042275/153032625-4784f4a3-dd2d-47dd-a423-ffc527c8f434.png)

When I try to use telethon it says that my account is spammed but its not. It's a new account but I cant use it. Any help or idea ?

**Comment by kthenurseone** [comment] 2022-02-08 16:37
Traceback (most recent call last):
  File "C:\Users\Kerim\Desktop\Dosyalar\selenium\tgbot\start.py", line 58, in <module>
    uyelist,cek,ekle = fonksiyonlar.startHandler(eklenecekgrup,cekilecekgrup,client_list[0])
  File "C:\Users\Kerim\Desktop\Dosyalar\selenium\tgbot\fonksiyonlar.py", line 66, in startHandler
    cekilecek_uyeler = getUserList(c, cekilecek)
  File "C:\Users\Kerim\Desktop\Dosyalar\selenium\tgbot\fonksiyonlar.py", line 79, in getUserList
    l = c.get_participants(grup, aggressive=True)
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\chats.py", line 222, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 80, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)')], [None, <telethon.tl.types.channels.ChannelParticipants object at 0x00000168438F1990>, <telethon.tl.types.channels.ChannelParticipants object at 0x000001684326FD90>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x00000168438F1D80>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843245C60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432455D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432457E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432456C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432456F0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432455A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843245CF0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843245D20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843245E10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843245F00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843245FC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246080>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246140>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246200>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432462C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246380>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246440>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246500>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432465C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246680>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246740>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246800>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000168432468C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246980>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246A40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000016843246B00>])

**Comment by micont92** [comment] 2022-02-08 17:36
Everyone is having the same problem :(

**Comment by Lonami** [comment] 2022-02-08 20:42
Duplicate of other recent issues.

**Closed by Lonami** 2022-02-08 20:42 UTC
