### ISSUE TITLE
Missing messages from NewMessage event

### ISSUE THREAD

**Issue by ngocbv** [LonamiWebs/Telethon#3014] opened 2021-04-01 13:21 UTC
I have implemented a messages listener, when I deploy the script to prod, at the first time, it works so well but after about 1 hour, the listener become hang and cannot be received the messages (no event coming). Then I have to restart the script and after 10min that error still happens.

**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.

**Code that causes the issue**
```python
        client = TelegramClient(
            StringSession(session_string),
            api_id,
            api_hash,
            auto_reconnect=True,
            connection_retries=None,
            request_retries=None,
            sequential_updates=True,
            retry_delay=0,
            flood_sleep_threshold=0,
        )
        @client.on(events.NewMessage(incoming=True))
        async def my_event_handler(event):
            try:
                Logger.print(f"Received new message: {event}")
                await MessageReceivedHandler().handle_message_incoming_event(event)
            except (BrokenPipeError, IOError) as error:
                Logger.print(f"[TelegramClientListener] {type(error).__name__}: {error}")
                await MessageReceivedHandler().handle_message_incoming_event(event)
            except Exception as error:
                Logger.print(f"[TelegramClientListener] {type(error).__name__}: {error}")
                rollbar.report_exc_info()

        Logger.print("Start listening new messages")
        client.start()
        client.run_until_disconnected()

```
Does anyone have any idea?

**Comment by Lonami** [comment] 2021-04-01 13:27
Duplicate of #1721.

**Closed by Lonami** 2021-04-01 13:27 UTC

**Comment by ngocbv** [comment] 2021-04-01 15:31
I found the solution to my issue. I used 1 session string for 2 TelegramClient connections, so when the second process initializes TelegramClient, the first process will be hang. I separated them with 2 session strings, so it's resolved.
