### ISSUE TITLE
Persistent timestamp empty error

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#808] opened 2018-05-21 19:27 UTC
Hi,

I run this code twice and in second run I get following exception:

```
client = TelegramClient("session", API_ID, API_HASH, proxy=(socks.SOCKS5, 'localhost', 8080),
                        spawn_read_thread=False)
client.connect()
client.catch_up()
client.disconnect()
```

```
Traceback (most recent call last):
  File "D:/work/bale/telegram_copier/telegram_bot/te.py", line 9, in <module>
    client.catch_up()
  File "C:\Python36\lib\site-packages\telethon\telegram_client.py", line 2445, in catch_up
    d = self(GetDifferenceRequest(state.pts, state.date, state.qts))
  File "C:\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 486, in __call__
    result = self._invoke(call_receive, request, ordered=ordered)
  File "C:\Python36\lib\site-packages\telethon\telegram_bare_client.py", line 583, in _invoke
    raise next(x.rpc_error for x in requests if x.rpc_error)
telethon.errors.rpc_error_list.PersistentTimestampEmptyError: Persistent timestamp empty
```

P.S.: authentication done in previous runs and I give the session file with empty "update_state" table to this program.

**Comment by Lonami** [comment] 2018-05-22 08:26
I think we need to modify this:
https://github.com/LonamiWebs/Telethon/blob/b667bb0c1a8cac480ca2ddc40be2d9ae6bc5d99f/telethon/telegram_client.py#L2439-L2440

For:
```python
if not state or not state.pts:
    return
```

**Comment by Lonami** [comment] 2018-05-22 08:38
Oh I see. If you use specify no worker at all, the updates are not handled, and the state is not updated so it remains 0. Because why would one do the job if there's nobody listening for updates?

**Comment by Lonami** [comment] 2018-05-22 08:40
While that's fixed now I'd prefer to keep this open for some more thought on my above comment. Should we at least always update the pts even if nobody is using updates? We definitely should in case you change your mind later and decide to enable them.

**Comment by hnikaein** [comment] 2018-05-22 09:26
I'm not sure if I get your words correctly or not... But this code also give error:

```
client = TelegramClient("name", API_ID, API_HASH, proxy=(socks.SOCKS5, 'localhost', 8080),
                        spawn_read_thread=False)
client.connect()
client.updates.workers = 1
client.catch_up()
client.disconnect()
```

**Comment by Lonami** [comment] 2018-05-22 09:26
@hnikaein workers must be set before connect, because connect gets a new state.

**Comment by hnikaein** [comment] 2018-05-22 09:46
right. thanks.

**Comment by vegeta1k95** [comment] 2018-05-30 20:51
This code produces the same error:

``` python
client = TelegramClient(session, api_id, api_hash, update_workers=1)

@client.on(events.NewMessage(incoming=True))
def my_event_handler(event):
    if event.is_private:
        event.reply('hi!')

client.connect()
client.catch_up()
client.disconnect()
```

Online updates handled just fine, but  `catch_up` throws this exception.

**Comment by Lonami** [comment] 2018-07-02 17:46
After some talk apparently `getDifference` is not the right way to get updates while the client was offline. You see, Telegram Desktop for instance gets dialogs and just checks the missed messages on demands. Perhaps `catch_up` should be removed or it needs more investigation I don't know.

**Comment by vegeta1k95** [comment] 2018-07-13 02:34
@Lonami 
For some sessions I'm never reaching a `DifferenceEmpty` response even if I'm requesting difference right after updating my state, multiple times.
E.g code like this
``` python
state = client(GetStateRequest())
diff = client(GetDifferenceRequest(state.pts, state.date, state.qts))
print(state)
print(diff)
``` 
returning a response:
``` python
State(pts=60936,
      qts=0,
      date=datetime.utcfromtimestamp(1531437560),
      seq=502,
      unread_count=4456)
Difference(new_messages=[],
           new_encrypted_messages=[],
           other_updates=[UpdateUserPhoto(...)],
           chats=[],
           users=[User(...)],
           state=State(pts=60936,
                          qts=0,
                          date=datetime.utcfromtimestamp(1531437560),
                          seq=502,
                          unread_count=4456))
```
As you can see, `State` objects are the same, but it returns the same `UpdateUserPhoro` every time I execute this code instead of returning `DifferenceEmpty` eventually. 
Am I missing something or this works as intended?

**Comment by Lonami** [comment] 2018-07-13 13:16
Nope, and that's why I could never complete the `catch_up` properly. Here's an [except](https://t.me/TelethonChat/55656) of previous conversation in [@TelethonChat](t.me/telethonchat):
> \<ivan\> ok,try to fix it, but still stuck with loop
now strange thing with it:
in intermidiate_state doesn't changes only date property, and at the end it stuck on one value
messages, wich I recieve changing same as state.date, BUT part of it repeated from request to request...

**Comment by izverev** [comment] 2018-07-13 13:40
@vegeta1k95 please have a look, do you have ChannelDifferenceTooLong or other TooLong in your other_updates?
Have same issue with my session, as I see in other clients code, they loop GetDifferenceRequest only if have DifferenceSlice response, so maybe State object can be same, but I have same behavior with DifferenceSlice responce, so I stuck in loop
Now'm trying to write handle ChannelDifferenceTooLong answer, hope it change situation

**Comment by vegeta1k95** [comment] 2018-07-13 14:58
@izverev 
This session does not have any other updates than `UpdateUserPhoto`, and in this case response is `Difference`, not `DifferenceSlice`, since I'm trying to get difference right after updating state manually.

Though I do have problems with `DifferenceSlice` for some other sessions (mostly those whose updates haven't been handled before).
 In this case I'm using new intermediate state from a `DifferenceSlice` as an input state for the next iteration of `GetDifferenceRequest`, but all incoming differences contain the same state parameters as before with exception of `date`, thus loop stucks.

You can avoid infinite loop of `DifferenceSlice` by replacing current session state with the most recent from servers by `GetStateRequest`, but all intermediate updates will be skipped. At least this allows you to proceed to further updates.

@Lonami 
I've also found some minor bugs in code.
1) Some updates has attribute `pts` with value `None`. This raises an exception when trying to handle such updates in this part (`telethon\client\updates.py`):
``` python
if hasattr(update, 'pts'):
    if self._state.pts and (update.pts - self._state.pts) > 1:
        need_diff = True
```
Better use
``` python
if getattr(update, `pts`, None):
```
2) Some inconsistencies with a timestamp attribute inside `State`. Due to UTC convertation timestamp inside a session file is not the same as returned by `get_update_state(0)`. You can check it by yourself.
``` python
print(state.date)
client.session.set_update_state(0, state)
print(client.session.get_update_state(0).date)
```
This will give you two different dates.

**Comment by vegeta1k95** [comment] 2018-07-13 15:01
Would be nice to get someone familiar with Java to look into Android version code and see how updates handling done there.

**Comment by vegeta1k95** [comment] 2018-07-13 15:17
@izverev 

> No, I already replace current state by intermediate, but as I said get infinite loop

I didn't say about an intermediate state of `DifferenceSlice`. I mean if you stuck with `DifferenceSlice` loop, you can fetch the latest state by `GetStateRequest` and set it as a current state by `client.session.set_update_state`. You will catch up to the latest update state but all previous updates will be gone , but you can further fetch updates with `GetDifferenceRequest` and response will contain either `Difference` or `DifferenceEmpty`.

**Comment by Lonami** [comment] 2018-07-13 21:54
> I've also found some minor bugs in code.

That was fixed already on https://github.com/LonamiWebs/Telethon/commit/ac5f8da50c3364692f8d3c2d2b423a18e4800940:
https://github.com/LonamiWebs/Telethon/blob/051d56af8844f70050a58783d0721b840aec1828/telethon/client/updates.py#L197

**Comment by Lonami** [comment] 2018-07-13 22:02
That one should help address your second point, along with https://github.com/LonamiWebs/Telethon/commit/38c65adf358ac42033cb2382b850fde9a82bcb71, both of which are not (as the moment of writing) on PyPi.

**Comment by vegeta1k95** [comment] 2018-08-10 19:05
Recently returned to my Telethon-based project (sync branch) and it seems that this problem has magically vanished for me with the latest versions. Maybe timezone fixes helped, but right now I can succesfully loop though `DifferenceSlice` updates, using intermediate states and eventually reach last `Difference` and `DifferenceEmpty` after it.

I've tested it on a number of sessions and for each it worked fine.
Does anyone still have this problem?

**Comment by Lonami** [comment] 2018-08-10 19:05
Thanks for the feedback, I'll be sure to test if the intermediate state works now.

**Comment by vegeta1k95** [comment] 2018-08-10 19:09
I'm using this piece of code to test it:
``` python
while True:
    old_state = client.session.get_update_state(0)    
    if not old_state or not old_state.pts:
        old_state = client(GetStateRequest())

    print('Current state', old_state.date)

    d = client(GetDifferenceRequest(old_state.pts, old_state.date, old_state.qts))

    if not isinstance(d, DifferenceEmpty):
        for m in d.new_messages:
            if not m.out:
                try:
                    print(getattr(m, 'message', None))
                    client.send_read_acknowledge(m.from_id, m, clear_mentions=True)
                except:
                    pass

    print(type(d))

    if isinstance(d, Difference):
        print(d.state.date)
        client.session.set_update_state(0, d.state)
    elif isinstance(d, DifferenceSlice):
        print(d.intermediate_state.date)
        client.session.set_update_state(0, d.intermediate_state)
    elif isinstance(d, DifferenceEmpty):
        old_state.date = d.date
        old_state.seq = d.seq
        client.session.set_update_state(0, old_state)
        break
client.session.save()
```

**Comment by vegeta1k95** [comment] 2018-08-10 19:48
Also, in the case of `DifferenceTooLong` shouldn't you update session's `pts` attribute (which is contained in the difference)? Because right now your `catch_up` method just breaks out of the function without actually doing anything in this case.

**Comment by Lonami** [comment] 2018-08-13 10:38
`DifferenceTooLong`'s `pts` is now used as well, thanks for the reminder.

**Closed by Lonami** 2018-08-13 10:38 UTC
Labels: help wanted
