### ISSUE TITLE
Telethon on NewMessage event always misses the first message!

### ISSUE THREAD

**Issue by nnthegreek** [LonamiWebs/Telethon#3936] opened 2022-09-25 15:36 UTC
Working on a simple NewMessage example I noticed that once client starts it always misses the first incoming message from group or channel.

eg. on:
 
   @client.on(events.NewMessage(chat=CHANNELID)
   async def handler(event):
      await event.reply('Hey!')

the function handler() runs only after the second message in chat.

**Comment by Lonami** [comment] 2022-09-27 08:56
I am not able to reproduce this issue with the following code:

```python
async def main():
    async with TelegramClient('anon', os.getenv('TG_ID'), os.getenv('TG_HASH')) as client:
        @client.on(events.NewMessage)
        async def h(e):
            print(e.id)

        await client.run_until_disconnected()

asyncio.run(main())
```

Sending messages in a channel works fine. I also tried adding `chats=CHANNELID` but that also worked. I will need more information if I'm to investigate this.

**Comment by nnthegreek** [comment] 2022-09-27 21:14
Telethon version: 1.25.2
Ubuntu 20.04 LTS

It Seems to work on private channel, but it always misses the first incoming message of another channel.

```
async def main():
    async with TelegramClient('anon', ID, HASH) as client:
        @client.on(events.NewMessage)
        async def h(e):
            await e.reply("you typed " + e.message.message)
            print(e.id)

        await client.run_until_disconnected()

asyncio.run(main())

```
![Screenshot_20220928_000804](https://user-images.githubusercontent.com/73097028/192636415-d17e6545-4f9f-436e-900c-1d7f5d94b14f.png)

**Comment by kaiopinho** [comment] 2022-10-07 22:32
to reproduce this problem, after connecting the group or channel they cannot send any messages for a certain time, I did a test with 4 hours it may be less, did you do anything to get around this?

**Comment by Lonami** [comment] 2022-10-13 16:31
Still not able to reproduce this. If with account A I join a public channel created by account B, and account B sends a message, account A receives the first message just fine.

> to reproduce this problem, after connecting the group or channel they cannot send any messages for a certain time, I did a test with 4 hours it may be less

Do you mean I have to join a channel, wait 4 hours without the channel sending messages, and then send a message?

**Comment by kaiopinho** [comment] 2022-10-14 17:35
> Still not able to reproduce this. If with account A I join a public channel created by account B, and account B sends a message, account A receives the first message just fine.
> 
> > to reproduce this problem, after connecting the group or channel they cannot send any messages for a certain time, I did a test with 4 hours it may be less
> 
> Do you mean I have to join a channel, wait 4 hours without the channel sending messages, and then send a message?

Tested on win10- python 3.7 and ubuntu 21-python 3.9.5.

Don't call client.get_dialogs() to reproduce the problem (it is not necessary to wait), my solution was to call the function every 1 hour but it's not the proper solution.

```py
import asyncio, time
from telethon import TelegramClient, events
from datetime import datetime

api_id = 'api-id'
api_hash = 'api-hash'

async def main():
  client = TelegramClient('save_bd', api_id, api_hash)

  @client.on(events.NewMessage)
  async def my_event_handler(event):
    try:
      try:
        message_id = str(str(event.message.chat.id).replace('-', ''))
      except:
        message_id = str(str(event.message.chat_id).replace('-', ''))
      if message_id == 'me_id_chat':
        print(event)
    except Exception as e:
      print('erro', e)

  # await client.start()
  print(await client.connect())
  print(client.is_connected())
  print(await client.is_user_authorized())
  print(await client.get_me())
  while 1:
    #chats = await client.get_dialogs()
    await asyncio.sleep(3600)

asyncio.run(main())
```

**Comment by Lonami** [comment] 2022-10-14 18:14
Joined a channel from another account. Ran your code (only changed the `if` / client parameters). Still works.

```python
client = TelegramClient('lonami', os.getenv('TG_ID'), os.getenv('TG_HASH'))
@client.on(events.NewMessage)
async def my_event_handler(event):
    try:
        try:
            message_id = str(str(event.message.chat.id).replace('-', ''))
        except:
            message_id = str(str(event.message.chat_id).replace('-', ''))
        if message_id == 'me_id_chat' or True:
            print(event)
    except Exception as e:
        print('erro', e)
print(await client.connect())
print(client.is_connected())
print(await client.is_user_authorized())
print(await client.get_me())
while 1:
    #chats = await client.get_dialogs()
    await asyncio.sleep(3600)
```

**Comment by kaiopinho** [comment] 2022-10-14 19:01
> Joined a channel from another account. Ran your code (only changed the `if` / client parameters). Still works.
> 
> ```python
> ...
> ```

restart the code and send a message to this group from another account.
make sure it is the first message received from all your telegram chats.

**Comment by nnthegreek** [comment] 2022-10-16 12:18
The problem exists in version 1.25.4 too.
Once you run your script, it still misses the first incoming message of a channel. Only the second fires the event.

**Comment by Lonami** [comment] 2022-10-16 16:08
> restart the code and send a message to this group from another account

I have tried this several times. I cannot reproduce the issue. Unfortunately this probably doesn't affect most people (which makes it harder to fix), or otherwise this issue would have *a lot* more people reporting the same issue.

> it still misses the first incoming message of a channel. Only the second fires the event

I don't know what the difference could be, but I have never seen this behavior myself.

**Comment by minecraft8997** [comment] 2022-10-18 20:49
Same issue for me.

**Comment by EnkhAmar** [comment] 2022-10-21 10:10
As I mentioned here in this issue #3943 . That missing first message problem occurs only in macOS computer, more specifically macbooks with M1 chip.

### update

I run the script on windows 10 laptop and everything worked as expected.

**Comment by minecraft8997** [comment] 2022-10-21 21:10
> As I mentioned here in this issue #3943 . That missing first message problem occurs only in MacOS computer, more specifically macbooks with M1 chip.

My laptop (HP ProBook 450 G7) is running Windows 11 and I do have this issue.

**Comment by Lonami** [comment] 2022-10-21 21:32
It is likely that someone experiencing this issue will have to be the one who attempts to fix it. I can't do much about if I know neither why the error happens, how, or when it happens. This is an important issue and I'd like it fixed but right now I can't do much about it.

If it happens reliably on some account, on some channels, I am willing to login to it to try myself (but you have to trust me for that).

Another option is to implement something to be able to record and replay network but that is also a lot of work (you'd also have to trust me a lot, but slightly less).

**Comment by Slexyy** [comment] 2022-10-30 18:26
I can replicate the issue by creating my own channel and then logging in to the client with the same phone number I created the channel with and with api keys. NewMessage event always misses the first message from the channel but reads the second one 👍

**Comment by steffen-lorenz** [comment] 2022-11-13 10:26
I have the same issue.
I try to listen to different broadcasting channels and react to messages. Currently i'm testing with my own channels.
After a restart of the script the first message per channel does not trigger the event
Code:
```python
client = TelegramClient(
    "forwarder",
    API_ID,
    API_HASH,
    proxy=None,
).start()

channel_ids = [...]

for id in channel_ids:
    @client.on(events.NewMessage(chats=PeerChannel(channel_id=id)))
    async def handler(event):
        chat_from = event.chat if event.chat else (await event.get_chat()) # telegram MAY not send the chat enity
        chat_title = chat_from.title
        print(f"message in {event.peer_id} / {chat_title} - forwarding")
        print(f"{event.message.id} - {event.message.message}")

def main():
    """Start the bot."""
    print("Starting now")
    client.run_until_disconnected()


if __name__ == "__main__":
    main()
```
Tested on:
- Telethon==1.25.4, Python 3.8.5 on WSL 
- Telethon==1.25.4, Python 3.10.6 on Ubuntu 22.04

I could reproduce the same behaviour with the following code on both machines as well:

```python
async def main():
    async with TelegramClient('forwarder', API_ID, API_HASH) as client:
        @client.on(events.NewMessage)
        async def h(e):
            print(e.id)

        await client.run_until_disconnected()

asyncio.run(main())
```

**Comment by Lonami** [comment] 2022-11-13 10:46
If this issue reliably occurs with some account or session file, and you would like me to test with it, you can [contact me privately](https://t.me/Lonami) (indicate you come from this issue 3936 so I know you're not spam) and give me access to the session file and faulty channels (of course you will need to trust me with the account, but I'll just use it to investigate this issue and then delete the files. You can also terminate the session after I'm done testing for extra security).

**Comment by Lonami** [comment] 2022-11-20 11:23
A Telegram user was kind enough to let me remotely debug this issue. The problem is Telegram is sending `UpdateReadChannelInbox` before `UpdateNewChannelMessage`. Because Telethon doesn't have the channel state yet, it uses the state of `UpdateReadChannelInbox` to initialize it, and then `UpdateNewChannelMessage` has the same state, so Telethon thinks it has already handled it.

```python
UpdateReadChannelInbox(channel_id=10001, max_id=101, still_unread_count=0, pts=201, folder_id=None)
UpdateNewChannelMessage(message=Message(id=101, peer_id=PeerChannel(channel_id=10001), date=datetime.datetime(2022, 11, 20, 11, 0, 0, tzinfo=datetime.timezone.utc), message='Test', out=True, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, noforwards=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to=None, media=None, reply_markup=None, entities=[], views=1, forwards=0, replies=None, edit_date=None, post_author=None, grouped_id=None, reactions=None, restriction_reason=[], ttl_period=None), pts=201, pts_count=1)
```

This can occur when the same account sending the message to a channel has that same channel open so that the message is immediately marked as read.

**Closed as completed** 2022-11-20 21:54 UTC

**Comment by Lonami** [comment] 2022-11-20 21:58
Here's the code used to test the fix, just in case:

```python
import datetime
from telethon import types
from telethon._updates import MessageBox

mb = MessageBox()
result = []
mb.process_updates(types.Updates([
    types.UpdateReadChannelInbox( channel_id=10001, max_id=19, still_unread_count=0, pts=20, folder_id=None ),
    types.UpdateNewChannelMessage( message=types.Message( id=19, peer_id=types.PeerChannel( channel_id=10001 ), date=datetime.datetime(2022, 1, 1, 0, 0, 0, tzinfo=datetime.timezone.utc), message='a', out=True, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, noforwards=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to=None, media=None, reply_markup=None, entities=[ ], views=1, forwards=0, replies=None, edit_date=None, post_author=None, grouped_id=None, reactions=None, restriction_reason=[ ], ttl_period=None ), pts=20, pts_count=1 ),
], [], [], datetime.datetime.now(), 0), None, result)
for r in result:
    print(r)
print('--')
result = []
mb.process_updates(types.Updates([
    types.UpdateReadChannelInbox( channel_id=10001, max_id=20, still_unread_count=0, pts=21, folder_id=None ),
    types.UpdateNewChannelMessage( message=types.Message( id=20, peer_id=types.PeerChannel( channel_id=10001 ), date=datetime.datetime(2022, 1, 1, 0, 0, 0, tzinfo=datetime.timezone.utc), message='b', out=True, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, edit_hide=False, pinned=False, noforwards=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to=None, media=None, reply_markup=None, entities=[ ], views=1, forwards=0, replies=None, edit_date=None, post_author=None, grouped_id=None, reactions=None, restriction_reason=[ ], ttl_period=None ), pts=21, pts_count=1 ),
], [], [], datetime.datetime.now(), 0), None, result)
for r in result:
    print(r)
```
