### ISSUE TITLE
send flac file failed

### ISSUE THREAD

**Issue by mengyyy** [LonamiWebs/Telethon#1385] opened 2020-02-11 14:46 UTC
Python 3.8.1 
Ubuntu 18 .04 x64

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
bot = TelegramClient("bot", API_ID, API_HASH).start(bot_token=BOT_TOKEN)
result = await bot.send_file(chat, file="./test.flac", caption="send test.flac, parse_mode="html", force_document=True)
...

```

**Traceback**
```
[warn] [/metadata] Duplicate field name Key 'stream_info' already exists
[warn] [/metadata] Duplicate field name Key 'stream_info' already exists
[warn] [/metadata] Duplicate field name Key 'stream_info' already exists
[warn] [/metadata] Duplicate field name Key 'stream_info' already exists
[warn] [/metadata] Duplicate field name Key 'stream_info' already exists
....
Until all memory exhaust
Ctrl +C 
UniqKeyError                              Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in _addField(self, field)
    193         try:
--> 194             self._fields.append(field._name, field)
    195         except UniqKeyError as err:

/usr/local/lib/python3.8/dist-packages/hachoir/core/dict.py in append(self, key, value)
     66         if key in self._index:
---> 67             raise UniqKeyError("Key '%s' already exists" % key)
     68         self._index[key] = len(self._value_list)

UniqKeyError: Key 'stream_info' already exists

During handling of the above exception, another exception occurred:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-11-3d5b904dcbd4> in <module>
----> 1 result = await bot.send_file(chat, file=file_path, caption=caption, parse_mode="html", force_document=True)

/usr/local/lib/python3.8/dist-packages/telethon/client/uploads.py in send_file(self, entity, file, caption, force_document, clear_draft, progress_callback, reply_to, attributes, thumb, allow_cache, parse_mode, voice_note, video_note, buttons, silent, supports_streaming, schedule, **kwargs)
    331                 await self._parse_message_text(caption, parse_mode)
    332
--> 333         file_handle, media, image = await self._file_to_media(
    334             file, force_document=force_document,
    335             progress_callback=progress_callback,

/usr/local/lib/python3.8/dist-packages/telethon/client/uploads.py in _file_to_media(self, file, force_document, progress_callback, attributes, thumb, allow_cache, voice_note, video_note, supports_streaming, mime_type, as_image)
    672             media = types.InputMediaUploadedPhoto(file_handle)
    673         else:
--> 674             attributes, mime_type = utils.get_attributes(
    675                 file,
    676                 mime_type=mime_type,

/usr/local/lib/python3.8/dist-packages/telethon/utils.py in get_attributes(file, attributes, mime_type, force_document, voice_note, video_note, supports_streaming)
    604
    605     if is_audio(file):
--> 606         m = _get_metadata(file)
    607         if m:
    608             attr_dict[types.DocumentAttributeAudio] = \

/usr/local/lib/python3.8/dist-packages/telethon/utils.py in _get_metadata(file)
    583         try:
    584             with hachoir.parser.createParser(file) as parser:
--> 585                 return hachoir.metadata.extractMetadata(parser)
    586         except Exception as e:
    587             _log.warning('Failed to analyze %s: %s %s', file, e.__class__, e)

/usr/local/lib/python3.8/dist-packages/hachoir/metadata/metadata.py in extractMetadata(parser, quality)
    326     metadata = extractor(quality)
    327     try:
--> 328         metadata.extract(parser)
    329     except Exception as err:
    330         error("Error during metadata extraction: %s" % str(err))

/usr/local/lib/python3.8/dist-packages/hachoir/metadata/audio.py in extract(self, flac)
    409
    410     def extract(self, flac):
--> 411         if "metadata/stream_info/content" in flac:
    412             self.useStreamInfo(flac["metadata/stream_info/content"])
    413         if "metadata/comment/content" in flac:

/usr/local/lib/python3.8/dist-packages/hachoir/field/field.py in __contains__(self, key)
    271         """
    272         try:
--> 273             return self.getField(key, False) is not None
    274         except FieldError:
    275             return False

/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in getField(self, key, const)
    231                 raise MissingField(self, key)
    232             return self._fields.values[key]
--> 233         return Field.getField(self, key, const)
    234
    235     def _truncate(self, size):

/usr/local/lib/python3.8/dist-packages/hachoir/field/field.py in getField(self, key, const)
    250                 current = self
    251             for part in key.split("/"):
--> 252                 field = current._getField(part, const)
    253                 if field is None:
    254                     raise MissingField(current, part)

/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in _getField(self, name, const)
    219                 field = self._fields[name]
    220             elif self._field_generator is not None and not const:
--> 221                 field = self._feedUntil(name)
    222         return field
    223

/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in _feedUntil(self, field_name)
    331             while True:
    332                 field = next(self._field_generator)
--> 333                 self._addField(field)
    334                 if field.name == field_name:
    335                     return field

/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in _addField(self, field)
    168         self.__is_feeding = True
    169         try:
--> 170             field.size
    171         except Exception as err:
    172             if field.is_field_set and field.current_length and field.eof:

/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in _getSize(self)
    112     def _getSize(self):
    113         if self._size is None:
--> 114             self._feedAll()
    115         return self._size
    116     size = property(

/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in _feedAll(self)
    366             while True:
    367                 field = next(self._field_generator)
--> 368                 self._addField(field)
    369         except StopIteration:
    370             self._stopFeeding()

/usr/local/lib/python3.8/dist-packages/hachoir/field/generic_field_set.py in _addField(self, field)
    196             self.warning("Duplicate field name " + str(err))
    197             field._name += "[]"
--> 198             self.setUniqueFieldName(field)
    199             self._fields.append(field._name, field)
    200         if ask_stop:

/usr/local/lib/python3.8/dist-packages/hachoir/field/basic_field_set.py in setUniqueFieldName(self, field)
    121         except KeyError:
    122             self._field_array_count[key] = 0
--> 123         field._name = key + "[%u]" % self._field_array_count[key]
    124
    125     def readFirstFields(self, number):

KeyboardInterrupt:

```

Here you can get this flac file
https://files.catbox.moe/zzcy3k.flac

md5sum test.flac
17b710198fff0a12f8369f6e8c04f4f1  test.flac

**Comment by Lonami** [comment] 2020-02-11 15:06
This is a bug in `hachoir`, and is similar to the one you linked. Closing in favour to that.

You *probably* can do the following to disable the use of `hachoir` in Telethon:

```python
from telethon import utils
utils.hachoir = None
```

This way, it should not run the buggy code.

**Closed by Lonami** 2020-02-11 15:06 UTC

**Comment by nneonneo** [comment] 2020-02-11 20:20
Hello, I'm a developer on the hachoir project. I took a look at this file, and it seems it is corrupt - a section of the file from 0x1000 to 0x492AD0 is zeroed out (about 4.6MB), which should not occur in a normal FLAC file. 

Unfortunately, unlike most media players or libraries, hachoir is not that robust against corrupted inputs because it is designed to analyze files completely. It may not be the best library to use for completely arbitrary files that might be damaged.

**Comment by Lonami** [comment] 2020-02-11 20:28
Thanks for the response, back when I looked for a library, hachoir was the only reasonable one I could find. I tried reproducing the issue with the first N bytes of the file, and hachoir parses that successfully. But it doesn't sound like a good solution (it's a rather arbitrary thing to do).

As suggested in the linked issue, maybe it's possible to store a list of visited sections to avoid infinite recursion, but I'll leave that investigation in hachoir's issue tracker.

**Comment by nneonneo** [comment] 2020-02-11 20:32
Sadly in this case it isn't so easy - it's not infinite recursion. Actually, the parser does make progress - but only 4 bytes at a time, through a section containing 4MB of zeroes.

Some efficiency improvements in the parser might help, but this is not an expected case; the metadata section really is corrupted rather than just containing millions of empty tags. 

I have some other ideas on how it could be fixed for metadata extraction specifically. I am not sure yet how media players are handling this file; perhaps they're just blindly skipping ahead until they see something resembling an audio frame. If you play the file it sounds like it starts in the middle of a song, which suggests some of the audio is missing too.
