### ISSUE TITLE
how to appoint to the way I receive message？

### ISSUE THREAD

**Issue by cdthy** [LonamiWebs/Telethon#379] opened 2017-10-25 09:23 UTC
sorry,I am Chinese. Maybe I have not expressed clearly. I want get confirmation code message via sms, but If my account has login in Android,It will send message to my account

**Comment by Lonami** [comment] 2017-10-25 09:25
Why did you open *a third* issue? Closing as a duplicate of #378, #377 *and* #147.

**Closed by Lonami** 2017-10-25 09:25 UTC
