### ISSUE TITLE
Cannot forward dice message (sendDice)

### ISSUE THREAD

**Issue by ilyaroot** [LonamiWebs/Telethon#1453] opened 2020-05-04 20:26 UTC
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x]  I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events, sync, functions, utils
import asyncio, os, sys
...
@client.on(events.NewMessage())
async def my_event_handler(event):
        sender = await event.get_sender()
        chat = await event.get_chat()
        name = utils.get_display_name(sender)
        chatname = utils.get_display_name(chat)
        where = "My Home"
        if chatname == where:
                if '+' in event.raw_text:
                        message_782 = await client.get_messages('me', ids=782)
                        await client.forward_messages(where, message_782)

```
message_782 is Dice roll (sendDice Bot API Method).
Got ID from:
```python
chat = 'me'
for message in client.iter_messages(chat):
        print(message.id, ':', message.text)
```

**Traceback**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telethon/client/updates.py", line 431, in _dispatch_update
    await callback(event)
  File "pygram.py", line 25, in my_event_handler
    await client.forward_messages(where, message_782)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/messages.py", line 887, in forward_messages
    for chat_id, chunk in itertools.groupby(messages, key=get_key):
  File "/usr/local/lib/python3.8/site-packages/telethon/client/messages.py", line 870, in _get_key
    raise TypeError('Cannot forward messages of type {}'.format(type(m)))
TypeError: Cannot forward messages of type <class 'telethon.tl.patched.MessageService'>

```

**Comment by Lonami** [comment] 2020-05-04 22:10
Are you sure that's a dice roll? The error sounds like it's a message service.

**Comment by ilyaroot** [comment] 2020-05-05 06:31
Tried to send_message, not to forward:

```
ERROR:telethon.client.updates:Unhandled exception on my_event_handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telethon/client/updates.py", line 431, in _dispatch_update
    await callback(event)
  File "pygram.py", line 25, in my_event_handler
    await client.send_message(where, dart)
  File "/usr/local/lib/python3.8/site-packages/telethon/client/messages.py", line 709, in send_message
    return await self.send_file(
  File "/usr/local/lib/python3.8/site-packages/telethon/client/uploads.py", line 352, in send_file
    raise TypeError('Cannot use {!r} as file'.format(file))
TypeError: Cannot use <telethon.tl.types.MessageMediaDice object at 0x7f883ceb11f0> as file
```

**Comment by Lonami** [comment] 2020-05-05 06:56
That's a different issue to the one you first posted.

**Comment by Lonami** [comment] 2020-05-05 07:29
The original issue is not a bug and most likely you made a mistake. The second issue is addressed in https://github.com/LonamiWebs/Telethon/commit/4393ec0b83d511b6a20d8a20334138730f084375.

**Closed by Lonami** 2020-05-05 07:29 UTC
