### ISSUE TITLE
When I log in from Telethon it crashes from all accounts.

### ISSUE THREAD

**Issue by ghost** [LonamiWebs/Telethon#4269] opened 2023-12-09 21:17 UTC
### Code that causes the issue

```
async def main():
    async with TelegramClient('ExoSuit', api_id, api_hash) as client:
        @client.on(events.NewMessage(pattern='.ExoSuit'))
        async def handle_info(event):
            await get_system_info(event)
        await client.run_until_disconnected()
```

### Expected behavior

When I execute the code, when I log into my account, it crashes from all devices. I expected to see that the account would not crash

### Actual behavior

When I execute the code, when I log into my account, it crashes from all devices.

### Telethon version

1.31.1

### Python version

3.11.6 64-bit

### Operating system (including distribution name and version)

Windows 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-12-09 23:20
Duplicate of #4051.

**Closed as completed by Lonami** 2023-12-09 23:20 UTC
