### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vishalsharma9411** [LonamiWebs/Telethon#3723] opened 2022-02-15 07:43 UTC
1. i have a code see my full code

from telethon.sync import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import (
    InputPeerEmpty,
    UserStatusLastWeek,
    UserStatusOnline,
    UserStatusRecently,
)
import csv
from datetime import date, datetime
from telethon.sync import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import InputPeerEmpty
from telethon.sync import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.types import InputPeerEmpty, InputPeerChannel, InputPeerUser
from telethon.errors.rpcerrorlist import PeerFloodError, UserPrivacyRestrictedError
from telethon.tl.functions.channels import InviteToChannelRequest
import sys
import csv
import traceback
import time
from datetime import datetime
import getpass
from telethon.errors import SessionPasswordNeededError

#client = TelegramClient('bjbjbj', api_id, api_hash)
client = TelegramClient('jekhjhtgdggjhai', api_id, api_hash)
#client = TelegramClient('#rcbd bala', api_id, api_hash)
#client = TelegramClient('#rcbdddddd bala', api_id, api_hash)

client.connect()
if not client.is_user_authorized():
    client.sign_in(phone)
    try:
        login = client.sign_in(code=input("‎Your login code: "))

    except SessionPasswordNeededError:
        login_2step = client.sign_in(password=input('Enter 2fa: '))
chats = []
last_date = None
chunk_size = 200
groups = []

result = client(
    GetDialogsRequest(
        offset_date=last_date,
        offset_id=0,
        offset_peer=InputPeerEmpty(),
        limit=chunk_size,
        hash=0,
    )
)
chats.extend(result.chats)

for chat in chats:
    try:
        if chat.megagroup == True:
            groups.append(chat)
    except:
        continue

print('Choose a group to scrape members from:')
i = 0
for g in groups:
    print(str(i) + '- ' + g.title)
    i += 1

g_index = input("Enter a Number: ")
target_group = groups[int(g_index)]

print('Fetching Members...')
all_participants = []
all_participants = client.get_participants(target_group, aggressive=True)
print(all_participants)

print('Saving In file...')
with open("G:\\Members\\19\\members.csv","w",encoding='UTF-8') as f:
    writer = csv.writer(f, delimiter=",", lineterminator="\n")
    writer.writerow(
        ['sr. no.','username', 'user id', 'name', 'group', 'group id', 'last seen']
    )
    i = 0
    for user in all_participants:
        accept = True
        try:
            lastDate = user.status.was_online
            num_months = (datetime.now().year - lastDate.year) * 12 + (
                datetime.now().month - lastDate.month
            )
            if num_months > 0.5:
                accept = False
        except:
            continue

        if not user.status == UserStatusRecently():
            accept = True
        if accept:
            i += 1
            if user.username:
                username = user.username
            else:
                username = ""
            if user.first_name:
                first_name = user.first_name
            else:
                first_name = ""
            if user.last_name:
                last_name = user.last_name
            else:
                last_name = ""
            name = (first_name + ' ' + last_name).strip()
            writer.writerow(
                [
                    i,
                    username,
                    user.id,
                    name,
                    'group name',
                    'groupid',
                    user.status,
                ]
            )

print('Members scraped successfully.')

1. - [ ] 
2. ### **This code now giving this error sir please tell me what to do step by step sir its a humbel request sir**

Fetching Members...
Traceback (most recent call last):
  File "C:\Users\visha\PycharmProjects\test\pythonProject2\Other Work\copyer online by numbers one.py", line 90, in <module>
    all_participants = client.get_participants(target_group, aggressive=True)
  File "C:\Paython 39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Paython 39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Paython 39\lib\site-packages\telethon\client\chats.py", line 474, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Paython 39\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Paython 39\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Paython 39\lib\site-packages\telethon\client\chats.py", line 200, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Paython 39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Paython 39\lib\site-packages\telethon\client\users.py", line 75, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), None, None, None, None, FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 29 seconds is required (caused by GetParticipantsRequest)')], [None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025272239100>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025271C25EE0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025271B022E0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000025271C25BE0>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AA9B50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x00000252719C8940>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEA00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEAC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEB80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEC40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAED00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEDC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEE80>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AAEF40>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2040>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2100>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB21C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2280>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2340>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2400>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB24C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2580>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2640>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2700>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB27C0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2880>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2940>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2A00>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2AC0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000025271AB2B80>])

Process finished with exit code 1

**Comment by Lonami** [comment] 2022-02-15 08:31
Duplicate of #928. Please follow the issue template.

**Closed by Lonami** 2022-02-15 08:31 UTC

**Comment by vishalsharma9411** [comment] 2022-02-16 06:44
no i cant find anything there sir

**Comment by vishalsharma9411** [comment] 2022-02-16 06:46
no sir i cant find anything there sir you said there that (the issue is solved in the development version,) so sir how can i get that virstion sir

**Comment by vishalsharma9411** [comment] 2022-02-18 10:07
sirrr
