### ISSUE TITLE
Traceback telethon.errors.rpcerrorlist.ChannelInvalidError

### ISSUE THREAD

**Issue by dumpload** [LonamiWebs/Telethon#1303] opened 2019-10-22 09:37 UTC
**Checklist**
telethon:  1.9.0
python:3.6

any request to traceback error,  but, program not stop. 

may be found this error to join more group 

**Code that causes the issue**
```python
from telethon.sync import TelegramClient,sync
...

```

**Traceback**
```
Task exception was never retrieved
future: <Task finished coro=<UpdateMethods._dispatch_update() done, defined at telegeenv/lib/python3.6/site-packages/telethon/client/updates.py:373> exception=ChannelInvalidError('Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)',)>
Traceback (most recent call last):
  File "telegeenv/lib/python3.6/site-packages/telethon/client/updates.py", line 382, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "telegeenv/lib/python3.6/site-packages/telethon/client/updates.py", line 473, in _get_difference
    force=True
  File "telegeenv/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by GetChannelDifferenceRequest)
```

**Comment by Lonami** [comment] 2019-10-22 09:49
Fixed in newer versions. Duplicate of #1278.

**Closed by Lonami** 2019-10-22 09:49 UTC
