### ISSUE TITLE
Installation Telethon on Windows 11

### ISSUE THREAD

**Issue by mohsensemsarpour** [LonamiWebs/Telethon#3968] opened 2022-11-01 04:29 UTC
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**

**pip3 install telethon**
Collecting telethon
  Using cached Telethon-1.25.4-py3-none-any.whl (569 kB)
Collecting pyaes
  Using cached pyaes-1.6.1.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>

And also

**pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip**
Collecting https://github.com/LonamiWebs/Telethon/archive/v1.zip
  Using cached https://github.com/LonamiWebs/Telethon/archive/v1.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyaes
  Using cached pyaes-1.6.1.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>

**Comment by Lonami** [comment] 2022-11-01 09:36
I don't have access to a Windows 11 machine and the traceback provided is not very helpful. You're welcome to send a PR with a fix for Windows 11 support if you can figure out what's broken.

**Comment by mohsensemsarpour** [comment] 2022-11-01 10:16
I did the installation using a **Python virtual environment** and the installation was done without any problem. But outside the **Python virtual environment**, the problem still remains.

**Comment by alteralt** [comment] 2022-12-08 18:19
> I did the installation using a **Python virtual environment** and the installation was done without any problem. But outside the **Python virtual environment**, the problem still remains.

what is the python version?

**Comment by mohsensemsarpour** [comment] 2022-12-09 16:33
My Python Version is 3.10.8

**Comment by magoerlich** [comment] 2023-01-02 16:40
python 3.11.1
Windows Version 22H2 (Build 22621.963)
Can't reproduce here

> I did the installation using a **Python virtual environment** and the installation was done without any problem. But outside the **Python virtual environment**, the problem still remains.

Maybe check your global environment.

**Comment by Lonami** [comment] 2023-01-14 12:00
I'm going to close this issue assuming it was a problem with the environment and not something that can be "fixed" from Telethon. Please let me know if that's not the case and we can reopen the issue to keep looking into it.

**Closed as completed by Lonami** 2023-01-14 12:00 UTC
