### ISSUE TITLE
ImportError: cannot import name 'types'

### ISSUE THREAD

**Issue by avivaarifin** [LonamiWebs/Telethon#357] opened 2017-10-19 05:00 UTC
when i follow [this](https://github.com/LonamiWebs/Telethon/blob/master/README.rst) and try import 
`from telethon import TelegramClient` i got error like below:
```python
>>> from telethon import TelegramClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/telethon/__init__.py", line 1, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/usr/local/lib/python3.4/dist-packages/telethon/telegram_bare_client.py", line 12, in <module>
    from .crypto import rsa, CdnDecrypter
  File "/usr/local/lib/python3.4/dist-packages/telethon/crypto/__init__.py", line 3, in <module>
    from .auth_key import AuthKey
  File "/usr/local/lib/python3.4/dist-packages/telethon/crypto/auth_key.py", line 5, in <module>
    from ..extensions import BinaryReader
  File "/usr/local/lib/python3.4/dist-packages/telethon/extensions/__init__.py", line 6, in <module>
    from .binary_reader import BinaryReader
  File "/usr/local/lib/python3.4/dist-packages/telethon/extensions/binary_reader.py", line 7, in <module>
    from ..tl.all_tlobjects import tlobjects
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/__init__.py", line 2, in <module>
    from .session import Session
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/session.py", line 9, in <module>
    from .entity_database import EntityDatabase
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/entity_database.py", line 5, in <module>
    from .. import utils
  File "/usr/local/lib/python3.4/dist-packages/telethon/utils.py", line 9, in <module>
    from .tl.types import (
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/types/__init__.py", line 3, in <module>
    from ...tl import types
ImportError: cannot import name 'types'
>>> 
```

**Comment by Lonami** [comment] 2017-10-19 06:47
You didn't install from `pip`, did you? You have to run `python setup.py gen_tl`.

**Comment by avivaarifin** [comment] 2017-10-19 09:34
I am install from pip

$ `sudo pip3 install telethon`
Downloading/unpacking telethon
  Downloading Telethon-0.15.2.3-py3-none-any.whl (217kB): 217kB downloaded
Requirement already satisfied (use --upgrade to upgrade): rsa in /usr/local/lib/python3.4/dist-packages (from telethon)
Requirement already satisfied (use --upgrade to upgrade): pyaes in /usr/local/lib/python3.4/dist-packages (from telethon)
Installing collected packages: telethon
Successfully installed telethon
Cleaning up...
$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
`from telethon import TelegramClient`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ali/Downloads/Telethon-master/telethon/__init__.py", line 1, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/home/ali/Downloads/Telethon-master/telethon/telegram_bare_client.py", line 12, in <module>
    from .crypto import rsa, CdnDecrypter
  File "/home/ali/Downloads/Telethon-master/telethon/crypto/__init__.py", line 3, in <module>
    from .auth_key import AuthKey
  File "/home/ali/Downloads/Telethon-master/telethon/crypto/auth_key.py", line 5, in <module>
    from ..extensions import BinaryReader
  File "/home/ali/Downloads/Telethon-master/telethon/extensions/__init__.py", line 6, in <module>
    from .binary_reader import BinaryReader
  File "/home/ali/Downloads/Telethon-master/telethon/extensions/binary_reader.py", line 7, in <module>
    from ..tl.all_tlobjects import tlobjects
  File "/home/ali/Downloads/Telethon-master/telethon/tl/__init__.py", line 2, in <module>
    from .session import Session
  File "/home/ali/Downloads/Telethon-master/telethon/tl/session.py", line 9, in <module>
    from .entity_database import EntityDatabase
  File "/home/ali/Downloads/Telethon-master/telethon/tl/entity_database.py", line 5, in <module>
    from .. import utils
  File "/home/ali/Downloads/Telethon-master/telethon/utils.py", line 9, in <module>
    from .tl.types import (
  File "/home/ali/Downloads/Telethon-master/telethon/tl/types/__init__.py", line 3, in <module>
    from ...tl import types
ImportError: cannot import name 'types'

**Comment by Lonami** [comment] 2017-10-19 09:35
Not sure what the issue is then, I can install just fine.

**Comment by Lonami** [comment] 2017-10-19 10:19
I don't know why it doesn't work. It works on my end:
```python
$ pip install -U telethon --user
Collecting telethon
  Downloading Telethon-0.15.2.3-py3-none-any.whl (217kB)
    100% |████████████████████████████████| 225kB 726kB/s 
Requirement already up-to-date: pyaes in ./.local/lib/python3.6/site-packages (from telethon)
Requirement already up-to-date: rsa in /usr/lib/python3.6/site-packages (from telethon)
Requirement already up-to-date: pyasn1>=0.1.3 in ./.local/lib/python3.6/site-packages (from rsa->telethon)
Installing collected packages: telethon
  Found existing installation: Telethon 0.15.1.3
    Uninstalling Telethon-0.15.1.3:
      Successfully uninstalled Telethon-0.15.1.3
Successfully installed telethon-0.15.2.3
[lonami@lonami-pc ~]$ python
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from telethon import TelegramClient
>>> TelegramClient
<class 'telethon.telegram_client.TelegramClient'>
>>> 
```

**Comment by Lonami** [comment] 2017-10-19 10:54
@ebs111 now that you say that the issue was fixed on https://github.com/LonamiWebs/Telethon/commit/0e1249c8337d1aa61a0e23875fe8fcfd370e4b95. Pushing to PyPi.

**Comment by avivaarifin** [comment] 2017-10-19 12:50
$ `sudo pip3 install -U telethon --user`
Downloading/unpacking telethon from https://pypi.python.org/packages/92/81/1c89d53a3e5c104c042469fcad9a4ed44c779a5f277c5c68a482cbf7f78b/Telethon-0.15.2.4-py3-none-any.whl#md5=95f394e124391b9d196c57fe5b62b769
  Downloading Telethon-0.15.2.4-py3-none-any.whl (217kB): 217kB downloaded
Requirement already up-to-date: rsa in /usr/local/lib/python3.4/dist-packages (from telethon)
Requirement already up-to-date: pyaes in /usr/local/lib/python3.4/dist-packages (from telethon)
Installing collected packages: telethon
Successfully installed telethon
Cleaning up...
$ python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
 `from telethon import TelegramClient`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/telethon/__init__.py", line 1, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/usr/local/lib/python3.4/dist-packages/telethon/telegram_bare_client.py", line 12, in <module>
    from .crypto import rsa, CdnDecrypter
  File "/usr/local/lib/python3.4/dist-packages/telethon/crypto/__init__.py", line 3, in <module>
    from .auth_key import AuthKey
  File "/usr/local/lib/python3.4/dist-packages/telethon/crypto/auth_key.py", line 5, in <module>
    from ..extensions import BinaryReader
  File "/usr/local/lib/python3.4/dist-packages/telethon/extensions/__init__.py", line 6, in <module>
    from .binary_reader import BinaryReader
  File "/usr/local/lib/python3.4/dist-packages/telethon/extensions/binary_reader.py", line 7, in <module>
    from ..tl.all_tlobjects import tlobjects
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/__init__.py", line 2, in <module>
    from .session import Session
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/session.py", line 9, in <module>
    from .entity_database import EntityDatabase
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/entity_database.py", line 5, in <module>
    from .. import utils
  File "/usr/local/lib/python3.4/dist-packages/telethon/utils.py", line 9, in <module>
    from .tl.types import (
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/types/__init__.py", line 3, in <module>
    from ...tl import types
ImportError: cannot import name 'types'

**Comment by Lonami** [comment] 2017-10-19 12:51
Is it that hard to properly format your comments?

**Comment by avivaarifin** [comment] 2017-10-19 13:53
when I try to add an exception it appears like this

```python
>>> try:
...     from telethon import TelegramClient
... except Exception as e:
...     print("Failed to import TelegramClient due to", e)
...     TelegramClient = None
... 
Failed to import TelegramClient due to cannot import name 'helpers'
>>> 
```

**Comment by avivaarifin** [comment] 2017-10-19 22:28
Ok ... can work well with [#359](https://github.com/LonamiWebs/Telethon/pull/359) 

Thanks

**Comment by Lonami** [comment] 2017-10-21 17:07
Can you try installing older versions and report which one works?

**Comment by stek29** [comment] 2017-10-22 08:59
I'm sorry heh

**Comment by jollheef** [comment] 2017-10-22 12:48
@Lonami 

```
jollheef@localhost ~ $ pip install telethon==0.15.2 --user      
...
jollheef@localhost ~ $ /usr/bin/python3 -c 'import telethon'
# works
```

```
jollheef@localhost ~ $ pip install telethon==0.15.3 --user
...
jollheef@localhost ~ $ /usr/bin/python3 -c 'import telethon'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/__init__.py", line 1, in <module>
    from .telegram_bare_client import TelegramBareClient
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/telegram_bare_client.py", line 12, in <module>
    from .crypto import rsa, CdnDecrypter
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/crypto/__init__.py", line 3, in <module>
    from .auth_key import AuthKey
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/crypto/auth_key.py", line 5, in <module>
    from ..extensions import BinaryReader
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/extensions/__init__.py", line 6, in <module>
    from .binary_reader import BinaryReader
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/extensions/binary_reader.py", line 7, in <module>
    from ..tl.all_tlobjects import tlobjects
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/tl/__init__.py", line 2, in <module>
    from .session import Session
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/tl/session.py", line 9, in <module>
    from .entity_database import EntityDatabase
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/tl/entity_database.py", line 5, in <module>
    from .. import utils
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/utils.py", line 9, in <module>
    from .tl.types import (
  File "/home/jollheef/.local/lib64/python3.4/site-packages/telethon/tl/types/__init__.py", line 3, in <module>
    from ...tl import types
ImportError: cannot import name 'types'
```
```
jollheef@localhost ~ $ /usr/bin/python3 --version
Python 3.4.5
```

**Comment by Lonami** [comment] 2017-10-22 12:51
Okay thanks did you try latest `v0.15.3.1`?

**Comment by jollheef** [comment] 2017-10-22 12:54
```
jollheef@localhost ~ $ pip install telethon==0.15.3.1 --user         
...
jollheef@localhost ~ $ /usr/bin/python3 -c 'import telethon'
Traceback (most recent call last):
...
ImportError: cannot import name 'types'
```

**Comment by Lonami** [comment] 2017-10-22 12:54
Okay thank you.

**Comment by avivaarifin** [comment] 2017-10-22 15:42
0.14.2 -> work
0.15 -> work
0.15.1 -> work
0.15.2 -> work
0.15.3 -> not working (ImportError: cannot import name 'types')
0.15.3.1 -> not working (ImportError: cannot import name 'types')

**Comment by BorisPlus** [comment] 2017-10-22 20:19
Hello, I have the same problem when I work under user not root

```
root@***:# /usr/bin/python3 --version
Python 3.4.2
root@***:# pip3 install telethon==0.15.2
It says me OK
root@***:# /usr/bin/python3 -c 'import telethon'
It says me OK
root@***:# exit
exit
dev@***:$ /usr/bin/python3 -c 'import telethon'
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.4/dist-packages/telethon/tl/types/__init__.py", line 3, in <module>
    from ...tl import types
ImportError: cannot import name 'types'

```

How can I solve it?

**Comment by Lonami** [comment] 2017-10-22 20:27
> How can I solve it?

You make a pull request or wait for me to fix it.

**Closed** 2017-10-24 08:08 UTC

**Comment by Lonami** [comment] 2017-10-24 08:11
I've pushed version `v0.15.3.2` to [PyPi](https://pypi.python.org/pypi/Telethon/0.15.3.2), please let me know if this really solved the issue.

**Comment by jollheef** [comment] 2017-10-24 08:13
Really solved.

**Comment by Lonami** [comment] 2017-10-24 08:14
Great, it's not as clean as I'd like it to be but I can't think of any other solution. #359 would have done the same (import only when needed) but with a different approach, this fix is more straightforward.
