### ISSUE TITLE
unexpected authorization request

### ISSUE THREAD

**Issue by Vertinskyj** [LonamiWebs/Telethon#4178] opened 2023-08-23 07:41 UTC
### Code that causes the issue

...
client = TelegramClient('sess', api_id, api_hash)

async def main():
    # Now you can use all client methods listed below, like for example...
    await client.send_message('me', 'Hello to myself!')

with client:
    client.loop.run_until_complete(main())

### Expected behavior

greetings

### Actual behavior

Re-authorization requirement: "Please enter your phone (or bot token):".

### Telethon version

1.29.3

### Python version

3.9.6

### Operating system (including distribution name and version)

Windows 10

### Other details

The file sess.session is in the same directory as the code file.

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-08-23 14:17
If the `.session` file is not saved correctly after login, it cannot be used without having to login again. Telegram may also be closing. Regardless, I likely cannot reproduce the issue.

**Closed as completed by Lonami** 2023-08-23 14:17 UTC

**Comment by Vertinskyj** [comment] 2023-08-23 17:38
Thanks a lot.
Unfortunately I don't know how to save correctly, nor to check correctness ;(
Program doesn't work.

**Comment by Lonami** [comment] 2023-08-23 19:43
The session should be saved on `.disconnect()`. This problem is likely not widespread or I'd expect more users to report this serious issue. Make sure the process can actually write to the session file.

**Comment by Vertinskyj** [comment] 2023-08-24 17:02
> This problem is likely not widespread or I'd expect more users to report this serious issue

I'm probably doing something wrong. But I don't understand what exactly.

> The session should be saved on .disconnect(). 

I tried this way. The result is the same.

In addition: after each such session creation, the telegram program in the phone requires authorization when entering.

**Comment by Lonami** [comment] 2023-08-24 19:37
If other sessions are logged out, then that's #4051.

**Comment by Vertinskyj** [comment] 2023-08-28 14:52
Thank You! 
The .session file works, the session has not been interrupted yet.
Belousov-Aleksandr's advice helped.
