### ISSUE TITLE
Error in Forward

### ISSUE THREAD

**Issue by Abolfazl-Dalily** [LonamiWebs/Telethon#1298] opened 2019-10-15 13:10 UTC
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
For some events I get this error:
The specified message ID is invalid or you can't do that operation on such message (caused by ForwardMessagesRequest)

telethon version : Version: 1.10.6

```python
event.forward_to(to_id)
...

```

**Traceback**
```


```

**Comment by Lonami** [comment] 2019-10-15 15:29
> For some events

Could you details *which* events trigger this issue?

**Comment by Abolfazl-Dalily** [comment] 2019-10-15 16:21
I use this function
```
    async def doAction(self,client,custom_event):

        to_id = int(self.to_contact)

        try:
            await custom_event.original_event.forward_to(to_id)
        except Exception as e:
            logger.elog("Event Can not Forward Because : "+str(e))
```
 for forwarding messages. And most of the time it works properly.
But sometimes I give this error.
```
The specified message ID is invalid or you can't do that operation on such message (caused by ForwardMessagesRequest)
```
I don't know exactly for what event this error occurs.

![Screenshot from 2019-10-15 19-49-14](https://user-images.githubusercontent.com/52946636/66850174-24e22500-ef85-11e9-9179-7787d202231a.png)

**Comment by Abolfazl-Dalily** [comment] 2019-10-15 16:32
I use this code to pars events:
```

class UpdateShortMessage:
    def __init__(self,event):
        self.original_event = event
        self.type = self.__get_type()
        self.message_id = self.__get_message_id()
        self.message = self.__get_message()
        self.from_id = self.__get_from_id()
        self.to_group_id = self.__get_to_group_id()
        self.to_channel_id = self.__get_to_channel_id()
        self.media = self.__get_media()
        self.entities = self.__get_entities()

    def __get_type(self):
        return "User"

    def __get_message_id(self):
        return self.original_event.original_update.id

    def __get_message(self):
        return self.original_event.original_update.message

    def __get_from_id(self):
        return self.original_event.original_update.user_id

    def __get_to_group_id(self):
        return None

    def __get_to_channel_id(self):
        return None

    def __get_media(self):
        return None

    def __get_entities(self):
        return self.original_event.original_update.entities

class UpdateShortChatMessage:
    def __init__(self,event):
        self.original_event = event
        self.type = self.__get_type()
        self.message_id = self.__get_message_id()
        self.message = self.__get_message()
        self.from_id = self.__get_from_id()
        self.to_group_id = self.__get_to_group_id()
        self.to_channel_id = self.__get_to_channel_id()
        self.media = self.__get_media()
        self.entities = self.__get_entities()

    def __get_type(self):
        return "Group"

    def __get_message_id(self):
        return self.original_event.original_update.id

    def __get_message(self):
        return self.original_event.original_update.message

    def __get_from_id(self):
        return self.original_event.original_update.from_id

    def __get_to_group_id(self):
        return self.original_event.original_update.chat_id

    def __get_to_channel_id(self):
        return None

    def __get_media(self):
        return None

    def __get_entities(self):
        return self.original_event.original_update.entities

class UpdateNewMessage:
    def __init__(self,event):
        self.original_event = event
        self.type = self.__get_type()
        self.message_id = self.__get_message_id()
        self.message = self.__get_message()
        self.from_id = self.__get_from_id()
        self.to_group_id = self.__get_to_group_id()
        self.to_channel_id = self.__get_to_channel_id()
        self.media = self.__get_media()
        self.entities = self.__get_entities()

    def __get_type(self):
        if type(self.original_event.original_update.message.to_id).__name__ == "PeerUser" :
            return "User"
        else:
            return "Group"

    def __get_message_id(self):
        return self.original_event.original_update.message.id

    def __get_message(self):
        return self.original_event.original_update.message.message

    def __get_from_id(self):
        return self.original_event.original_update.message.from_id

    def __get_to_group_id(self):
        if type(self.original_event.original_update.message.to_id).__name__ == "PeerChat":
            return self.original_event.original_update.message.to_id.chat_id
        else:
            return None

    def __get_to_channel_id(self):
        return None

    def __get_media(self):
        return self.original_event.original_update.message.media

    def __get_entities(self):
        return self.original_event.original_update.message.entities

class UpdateNewChannelMessage:
    def __init__(self,event):
        self.original_event = event
        self.type = self.__get_type()
        self.message_id = self.__get_message_id()
        self.message = self.__get_message()
        self.from_id = self.__get_from_id()
        self.to_group_id = self.__get_to_group_id()
        self.to_channel_id = self.__get_to_channel_id()
        self.media = self.__get_media()
        self.entities = self.__get_entities()

    def __get_type(self):
        return "Channel/MegaGroup"

    def __get_message_id(self):
        return self.original_event.original_update.message.id

    def __get_message(self):
        return self.original_event.original_update.message.message

    def __get_from_id(self):
        return self.original_event.original_update.message.from_id

    def __get_to_group_id(self):
        return None

    def __get_to_channel_id(self):
        return self.original_event.original_update.message.to_id.channel_id

    def __get_media(self):
        return self.original_event.original_update.message.media

    def __get_entities(self):
        return self.original_event.original_update.message.entities


def event_parser(event):
    event_type = type(event.original_update).__name__
    if event_type == "UpdateShortMessage":
        return UpdateShortMessage(event)
    elif event_type == "UpdateShortChatMessage":
        return UpdateShortChatMessage(event)
    elif event_type == "UpdateNewMessage":
        return UpdateNewMessage(event)
    elif event_type == "UpdateNewChannelMessage":
        return UpdateNewChannelMessage(event)
    else:
        return None
```
then use ```event_parser``` function in this code 
```
async def message_handler(self, event):
        custom_event = event_parser(event)
        if custom_event is not None:
           # call doAction 
        else:
            logger.elog("A Unknown event was received")
            print(type(event.original_update).__name__)
```

**Comment by nn23** [comment] 2019-10-16 20:27
same problem, 1.10.6 version, I catch a new message event from the client and try to forward it throught the bot for "RESULTS_RECIPIENT_ID" (it's a integer ID of the client):
```python 
@client.on(events.NewMessage(incoming=True))
async def client_event_handler(event):
        await bot.forward_messages(RESULTS_RECIPIENT_ID, event.message)
```

if I received message from Telegram bot and trying to forward it, I have
`telethon.errors.rpcerrorlist.MessageIdInvalidError: The specified message ID is invalid or you can't do that operation on such message (caused by ForwardMessagesRequest)`
on channel message I have
`telethon.errors.rpcerrorlist.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited (caused by ForwardMessagesRequest)`

**Comment by Lonami** [comment] 2020-10-01 11:34
This issue is quite old and Telegram recently changed some stuff regarding messages, so I'm closing it. If this issue still occurs, please post a smaller code triggering the issue along with what's needed (for example if it needs to be tested in a group, with messages sent by someone in particular… Debugging with the code listing above is too much effort).

**Closed by Lonami** 2020-10-01 11:34 UTC

**Comment by sidqdev** [comment] 2022-02-13 12:39
I have same problem on
`await self.client.forward_messages(self.admin_chat, message)`

**Comment by kruzalus** [comment] 2022-03-24 12:44
I had the same problem and then I found out, that the problem occurs with messages, which were deleted by author for everybody in the chat, but Telethon's client still can get and handle these messages.

**Comment by alexeyhimself** [comment] 2025-01-18 18:37
Also faced this issue today. Most messages are forwarded well, but 2 messages (from the same author) didn't. Maybe the issue is somehow related to some settings in Telegram made by that author. Still don't know the answer and continue investigations.
