### ISSUE TITLE
Error 400: MESSAGE_EMPTY RPCError(...) and "Registered to #1 DC."

### ISSUE THREAD

**Issue by TGibsonn** [LonamiWebs/Telethon#88] opened 2017-05-18 14:56 UTC
When I tried to connect, I received the following:

[10:16:00.474/MainThread] WARNING: Read RPC error: (RPCError(...), 'Unknown error message with code 400: MESSAGE_EMPTY')
Could not stabilise initial connection: (RPCError(...), 'Unknown error message with code 400: MESSAGE_EMPTY')

I then attempted to terminate the session and deleted sessionid.session to reauthorize it, only to get this:

telethon.errors.InvalidDCError: (InvalidDCError(...), 'Your phone number is registered to #1 DC. This should have been handled automatically; if it has not, please restart the app.')

Restarting the app does not resolve the issue.

**Comment by TGibsonn** [comment] 2017-05-18 15:56
Actually, it managed to start working after I performed a full server reboot. It still threw "[11:55:13.140/MainThread] WARNING: Read RPC error: (RPCError(...), 'The phone number a user is trying to use for authorization is associated with a different data center (#1).')" but it ended up receiving the code regardless after a few seconds of waiting.

Unknown why this happened.

**Comment by Lonami** [comment] 2017-05-18 16:45
> MESSAGE_EMPTY

Very strange you got that error for the first time logging in, without having performed any previous request. In theory it happens, as it says, when an empty message is sent (see https://core.telegram.org/method/messages.sendMessage).

> The phone number a user is trying to use for authorization is associated with a different data center (`#1`).

About that yes, that issue is common. The fact it's a "warning" is arbitrary and you shouldn't really worry about that. The fact it fails sometimes, though, is related to #7.

What are the steps to reproduce the `MESSAGE_EMPTY` error?

**Comment by TGibsonn** [comment] 2017-05-18 17:10
For `MESSAGE_EMPTY` it seemed to be out of nowhere, but maybe I was disconnecting and reconnecting too frequently. I had been changing around snippets of code and connected/reconnected over the course of an hour, however, I may have done it too fast without waiting and that might have been why. I don't post any requests prior to the login. 

It only runs TelegramClient's connect() at first, then goes through checking the is_user_authenticated(), and does a run definition for message handling.

My only guess is that it didn't terminate properly and was running in the background and that's why terminating the sessions and killing the related tasks (apparently) resolved the problem.

**Comment by Lonami** [comment] 2017-05-18 17:16
> but maybe I was disconnecting and reconnecting too frequently

So it wasn't the first **first** time trying to login. That makes more sense. If Telethon crashes, Telegram re-sends, for some reason, the previous error. So I will close this issue since `MESSAGE_EMPTY` *per se*, is after trying to send an empty message :P

**Closed by Lonami** 2017-05-18 17:16 UTC
