### ISSUE TITLE
Session broke after 10 minutes

### ISSUE THREAD

**Issue by 4myr** [LonamiWebs/Telethon#1402] opened 2020-03-12 11:17 UTC
hello.
i have two session in my server but they crashes and **logout** after 10-20 minutes from running!
and when i run that again, it ask me sign in again!!!
i have just a NewMessage event handler in my code

**Code that causes the issue**

```from telethon import TelegramClient, events
from telethon.sync import TelegramClient
from telethon import functions, types, errors
import sys
thisBot = 'sara'
import importlib
config = importlib.import_module(thisBot + ".config")

import json
import time
from datetime import datetime
import tzlocal
import random
import re
import asyncio

with open(thisBot + '/' + 'config.json') as f:
        conf = json.loads(f.read())

def convertDate(mydate):
    local_timezone = tzlocal.get_localzone()
    return datetime.fromtimestamp(mydate, local_timezone).strftime('%Y-%m-%d %H:%M:%S')

print('hi there')
client = TelegramClient(thisBot, config.api_id, config.api_hash)

commands = ['/ping', 'stats']

@client.on(events.NewMessage)

async def my_event_handler(event):
    try:
        global commands
        text = event.raw_text
        sender = await event.get_sender()
        chat_id = event.chat_id
        sender_id = event.sender_id

        # Pinging Command
        if text == '/ping':
            print('Pinging...')
            await event.reply('`Im Online`')
        elif chat_id == sender_id and hasattr(sender, 'bot') and sender.bot == False and text not in commands:
            await event.reply(config.tabliq)
    except Exception as error:
        print('An Error: {}'.format(error))

client.start()

client.run_until_disconnected()    
```

**Traceback**
```
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
An Error: auth_key generation failed 5 time(s)
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    client.run_until_disconnected()
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 67, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 23, in _run_until_disconnected
    return await self.disconnected
  File "/root/.local/lib/python3.6/site-packages/telethon/client/updates.py", line 508, in _handle_auto_reconnect
    await self.get_me()
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 139, in get_me
    functions.users.GetUsersRequest([types.InputUserSelf()])))[0]
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "main.py", line 43, in my_event_handler
    sender = await event.get_sender()
  File "/root/.local/lib/python3.6/site-packages/telethon/tl/custom/sendergetter.py", line 51, in get_sender
    await self._client.get_entity(self._input_sender)
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 280, in get_entity
    tmp.extend(await self(functions.users.GetUsersRequest(curr)))
  File "/root/.local/lib/python3.6/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
  File "/root/.local/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 363, in _reconnect
    await self._connect()
  File "/root/.local/lib/python3.6/site-packages/telethon/network/mtprotosender.py", line 254, in _connect
    raise e
ConnectionError: auth_key generation failed 5 time(s)


```

**Comment by Lonami** [comment] 2020-03-12 13:08
What version of the library, Python version, OS are you using? What country is the server in, and what server is it? Does it work in your local machine?

**Comment by 4myr** [comment] 2020-03-12 15:04
> What version of the library, Python version, OS are you using? What country is the server in, and what server is it? Does it work in your local machine?

Thanks for reply

`[root@server ~]# python3 --version
Python 3.6.8
[root@server ~]# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
[root@server ~]# python3 -c "import telethon; print(telethon.__version__)"
1.11.3
[root@server ~]#`

Server country: Germany
DC: Hetzner
Ram: 1024

And i never tried it on my local machine

**Comment by Lonami** [comment] 2020-03-12 18:48
Please try in your local machine. It might be a temporary issue as well.

**Comment by 4myr** [comment] 2020-03-12 20:57
i tried that but same problem has occurred
event i tried on another server with centos & ubuntu 16 os

**Comment by Digoya** [comment] 2020-03-21 03:53
Encountered the same issue here. I have a few StringSessions and few SQLite sessions as well. Most of them are currently broken. 
Local machine with doker and Python 3.8
Ubuntu: 19.10
Telethon: 1.11.3

**Comment by den-kar** [comment] 2020-03-28 11:22
Encountered the same issue.
Local machine in Germany
Ubuntu 18.04
Python 3.7.4
Telethon 1.10.9

**Comment by Ashish0804** [comment] 2020-09-23 16:57
this error is still there. sad its still not fixed

**Comment by Lonami** [comment] 2020-09-23 19:50
I really didn't keep this issue in my mind, nor did I have much interest in prioritizing a solution for it. If it happened to everyone, the library would be pretty much unusable, and I haven't been able to reproduce this. Because I don't know what causes this, any fix would be "blind", which is not a good way to develop. 

Auth key generation issues are likely an issue with the server, or maybe the location where the code is ran from, because if it was broken in the Telethon side it would be broken for everyone and not just a few people.

**Comment by Ashish0804** [comment] 2020-09-24 04:46
> I really didn't keep this issue in my mind, nor did I have much interest in prioritizing a solution for it. If it happened to everyone, the library would be pretty much unusable, and I haven't been able to reproduce this. Because I don't know what causes this, any fix would be "blind", which is not a good way to develop.
> 
> Auth key generation issues are likely an issue with the server, or maybe the location where the code is ran from, because if it was broken in the Telethon side it would be broken for everyone and not just a few people.

My server is running in Singapore(https://ssh.cloud.google.com/cloudshell/editor), while my account is registered in India. I have been able to reproduce this error multiple times. Let me know if i can help you in way.  I always had tg opened on my pc too while the server was running in case that causes the problems

**Comment by Lonami** [comment] 2020-11-07 11:11
Closing under the assumption https://github.com/LonamiWebs/Telethon/commit/09f4c5c7086d3fb08b27d792edcfd358f44fa304 and https://github.com/LonamiWebs/Telethon/commit/026c992395f9c70b5c65c8102d00423dd8b20309 helped with regards to this issue. -404 still means the auth key is no longer valid, but on buffer errors it shouldn't "break".

**Closed by Lonami** 2020-11-07 11:11 UTC
