### ISSUE TITLE
Crash while get participants

### ISSUE THREAD

**Issue by json1c** [LonamiWebs/Telethon#3730] opened 2022-02-17 23:06 UTC
**Checklist**
* [ x] The error is in the library's code, and not in my own.
* [ x] I have searched for this issue before posting it and there isn't a duplicate.
* [ x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```
participants = await client.get_participants(msg.peer_id)
```

**Traceback**
```
Traceback (most recent call last):                                                 File "/root/.local/lib/python3.9/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "/root/parser.py", line 37, in handler
    participants = await client.get_participants(
  File "/root/.local/lib/python3.9/site-packages/telethon/client/chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "/root/.local/lib/python3.9/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/root/.local/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/root/.local/lib/python3.9/site-packages/telethon/client/chats.py", line 224, in _load_next_chunk
    participants = results[i]
TypeError: 'ChannelParticipants' object is not subscriptable
```

**Comment by Lonami** [comment] 2022-02-18 08:46
Duplicate of #928.

**Closed by Lonami** 2022-02-18 08:46 UTC

**Comment by json1c** [comment] 2022-02-25 12:45
your solution doesn't help

**Comment by Lonami** [comment] 2022-02-25 20:45
The solution has not yet been released. It will work once released.

**Comment by SpangleLabs** [comment] 2022-03-04 12:50
It will work, but will also break a bunch of other stuff, right?
> The next version will be v2, which contains many more breaking changes, and there is no planned release date

Do you know if the issue is fixable enough that one can make a working fork, for folks who don't want to rewrite their applications?

**Comment by Lonami** [comment] 2022-03-04 14:38
There's already forks with this issue fixed.

**Comment by SpangleLabs** [comment] 2022-03-11 19:11
> There's already forks with this issue fixed.

Any idea which?

**Comment by Lonami** [comment] 2022-03-12 09:23
No, I don't keep track of them. I only know I've seen them.
