### ISSUE TITLE
[Bug] Telegram Code Not Being Sent

### ISSUE THREAD

**Issue by RafayGhafoor** [LonamiWebs/Telethon#4041] opened 2023-02-20 20:27 UTC
**Steps to reproduce:**

```python
from telethon import TelegramClient, events

api_id = None
api_hash = ""
client = TelegramClient('SESSION', api_id, api_hash)


if __name__ == '__main__':
    print("Program is running...")

    @client.on(events.NewMessage())
    async def new_order(event):
        try:
            print('Delivery new order...')
            contain_key_word = False

            print(event)
        except Exception as ex:
            print(f'Exception: {ex}')


    client.start()
    client.run_until_disconnected()
```

@Lonami  Upon entering the phone number, there is input stating "Please enter the received code: " but no code is being sent while this procedure works fine when trying to login from telegram desktop itself or telegram app.

**Comment by Lonami** [comment] 2023-02-20 21:26
Closing as a duplicate of https://github.com/LonamiWebs/Telethon/issues/3835.

**Closed as completed by Lonami** 2023-02-20 21:26 UTC
