### ISSUE TITLE
NewMessage event: Some messages take time to be received intermittently on a particular channel. Does not happen on all channels

### ISSUE THREAD

**Issue by devcapixaba** [LonamiWebs/Telethon#4132] opened 2023-06-14 14:49 UTC
### Code that causes the issue

Using python's datetime.now() at the moment the message is identified

Please observe how I am running and maintaining the connection

<img width="443" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/41216360/2f45f36e-0e94-405e-9886-97798206e2c5">

<img width="599" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/41216360/8f224bb0-de17-47ac-b022-6dcc3d0ef61f">

<img width="221" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/41216360/287d48a9-5c54-4eb1-9f53-739c526e0dd2">

I'm running on a Debian 11 machine in Azure with a Brazilian IP and I don't get any errors during execution, just randomness regarding messages that arrive at the right time and others that don't.

### Expected behavior

Example of message received at the correct time. Please note the log times. The message was registered correctly at the time it was sent: 03:26

<img width="241" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/41216360/76219418-c6b1-484f-89a4-ffbc1506019b">

<img width="881" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/41216360/d0a884fe-9449-4fea-a54a-5094155ce3a4">

### Actual behavior

Example of message received late. Please note the log times. It should have registered around 02:56, but it registered 03:05

<img width="248" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/41216360/5d501c22-6fa8-411b-bbc8-7633009bab56">

<img width="882" alt="image" src="https://github.com/LonamiWebs/Telethon/assets/41216360/e9888360-ec43-4774-8622-2083d1abb68f">

### Telethon version

1.28.5

### Python version

3.10.6

### Operating system (including distribution name and version)

Debian 11

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2023-06-14 20:56
Thanks for the detailed report. Unfortunately, this has been brought to my attention several times before, and I have never been possible to reproduce it myself from what I can remember.

The conclusion we've arrived to in the past is, it's Telegram the one who decides when to deliver messages. My suspicion is that the delivery can be very slow when the client is not active, there are other sessions being more active, or the channel is simply very large. Of course, there's probably more other factors, decided by Telegram. As you point out:

> I don't get any errors during execution, just randomness regarding messages that arrive at the right time and others that don't.

There's a good chance Telethon behaves fine (or else you could expect all messages would be delayed, not just *some*), but it's Telegram instead. I have also heard of Telethon not having the issue and other libraries experiencing the problem. And vice-versa.

I don't really have have the time or interest to spend any more hours on this, as I've already spent a fair amount with no progress, and have no personal need for it. Because of this, I will close the issue.

But, if you have interest in debugging it further, I can reopen it and assign you to it.

**Closed as completed by Lonami** 2023-06-14 20:56 UTC

**Comment by devcapixaba** [comment] 2023-06-14 21:34
Thanks for the answer. I tested reducing the sessions, I had 16 simultaneous sessions and now 5 which is my limit, I noticed a reduction in the receiving time from 5 to 2 minutes, but I still received messages at the correct time before that. I believe that it really could be a problem related to the idle time of the session, I will test it to maintain interactivity with the session and return with more details.

**Comment by HamidZaeri** [comment] 2023-12-24 19:53
> Thanks for the answer. I tested reducing the sessions, I had 16 simultaneous sessions and now 5 which is my limit, I noticed a reduction in the receiving time from 5 to 2 minutes, but I still received messages at the correct time before that. I believe that it really could be a problem related to the idle time of the session, I will test it to maintain interactivity with the session and return with more details.

Hi @devcapixaba
Did you have any luck with this?

**Comment by cashriver** [comment] 2024-06-03 20:24
I encountered the same problem: the delay of a new message is arbitrary up to 15 minutes, but only in chats, after updating the telegram itself on May 28, 2024. Despite the fact that personally, nothing has changed for me at all.

What I tried and what **didn't** help:

1. Account activity. I read messages, wrote in chats with my hands.
2. Re-release of the session file
3. Buying premium
4. Proxy installation

**What helped:** Problems occurred on accounts that were authorized for SIM cards from Russia. And there were two accounts with Argentine phone numbers - there were no problems at all! I issued another Argentine SIM card and everything works without delays.

That is, the data route in telegram depends 100% on the country of the SIM card, and for me this is a routing problem, not a telethon library.

@Lonami thank you for your work. I hope this will be useful to someone.

**Comment by HamidZaeri** [comment] 2024-06-04 06:56
> I encountered the same problem: the delay of a new message is arbitrary up to 15 minutes, but only in chats, after updating the telegram itself on May 28, 2024. Despite the fact that personally, nothing has changed for me at all.
> 
> What I tried and what **didn't** help:
> 
>     1. Account activity. I read messages, wrote in chats with my hands.
> 
>     2. Re-release of the session file
> 
>     3. Buying premium
> 
>     4. Proxy installation
> 
> 
> **What helped:** Problems occurred on accounts that were authorized for SIM cards from Russia. And there were two accounts with Argentine phone numbers - there were no problems at all! I issued another Argentine SIM card and everything works without delays.
> 
> That is, the data route in telegram depends 100% on the country of the SIM card, and for me this is a routing problem, not a telethon library.
> 
> @Lonami thank you for your work. I hope this will be useful to someone.

Did you try this on large channels? Still no delay?

**Comment by cashriver** [comment] 2024-06-04 09:24
> > Столкнулся с такой же проблемой: задержка нового сообщения произвольная до 15 минут, но только в чатах, после обновления самого телеграмма 28 мая 2024 года. При том, что лично у меня вообще ничего не изменилось.
> > Что я пробовал и что **не** помогло:
> > ```
> > 1. Account activity. I read messages, wrote in chats with my hands.
> > 
> > 2. Re-release of the session file
> > 
> > 3. Buying premium
> > 
> > 4. Proxy installation
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Что помогло:** Проблемы возникли на аккаунтах, авторизованных для сим-карт из России. А аккаунтов с аргентинскими номерами телефонов было два - проблем вообще не было! Оформил другую аргентинскую симку и все работает без задержек.
> > То есть маршрут данных в телеграмме на 100% зависит от страны сим-карты, и для меня это проблема маршрутизации, а не библиотеки телемарша.
> > @LonamiСпасибо вам за вашу работу. Надеюсь, это будет кому-то полезно.
> 
> Вы пробовали это на крупных каналах? Все еще нет задержки?

Unfortunately, no, I still sometimes see only one pattern - that the delay can only be where there are more than 30k subscribers in the chat. But there are much fewer of them
