### ISSUE TITLE
Reconnect problem

### ISSUE THREAD

**Issue by gtavasoli** [LonamiWebs/Telethon#65] opened 2017-05-01 08:59 UTC
Hi, I reconnect to another dc and reconnection is done successfully (I have checked server address in client's session) but when restart script this error is shown when client tries to connect.

```
[13:22:41.576/MainThread] WARNING: Read RPC error: (RPCError(...), 'The key is not registered in the system.')
Traceback (most recent call last):
  File "sample.py", line 110, in <module>
    channel_info = client.invoke(ResolveUsernameRequest(username))
  File "C:\installation-path\Python\Python35\site-packages\telethon\telegram_client.py", line 175, in invoke
    self.sender.receive(request, timeout)
  File "C:\installation-path\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 139, in receive
    request)
  File "installation-path\Python\Python35\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 217, in process_msg
    return self.handle_rpc_result(msg_id, sequence, reader, request)
  File "C:\installation-path\Python\Python35\Python\Python35\site-packages\telethon\network\mtproto_sender.py", line 350, in handle_rpc_result
    raise error
telethon.errors.RPCError: (RPCError(...), 'The key is not registered in the system.')
```

**Comment by Lonami** [comment] 2017-05-01 09:14
That's really strange, did you try deleting the `*.session` file? Were you successfully connected before this happened?

**Comment by gtavasoli** [comment] 2017-05-01 09:21
No, I did not delete  *.session file.
It's my code

```
from telethon import TelegramClient

api_id = ---
api_hash = '---'

client = TelegramClient('@Sess1', api_id, api_hash)
client.connect()   # Successfull connection

if not client.is_user_authorized():
    client.send_code_request('+phone_number')
    client.sign_in('+phone_number', input('Enter the code (+phone_number): '))

print(client.session.server_address)   # Successfull

client.reconnect_to_dc(1)

print(client.session.server_address)   # Successfull
```

When I rerun this code the error occurred.

**Comment by Lonami** [comment] 2017-05-01 09:23
> `client.reconnect_to_dc(1)`

*Don't* do that. That must be handled automatically.

**Comment by gtavasoli** [comment] 2017-05-01 09:25
I'm sorry but I don't understand; how can I change current dc to another dc?

**Comment by Lonami** [comment] 2017-05-01 09:31
> how can I change current dc to another dc?

You shouldn't do that. That should be handled automatically. It's not something you should worry about.

**Comment by gtavasoli** [comment] 2017-05-01 09:38
Thanks, but how can download media from another dc?

**Comment by Lonami** [comment] 2017-05-02 06:19
You just use Telethon as usual. It will reconnect when required. What error are you getting when trying to download it _without_ manually reconnecting? What version are you using?

**Comment by gtavasoli** [comment] 2017-05-02 08:47
My dc_id is 4 and channel's photo exist in another data center (dc_id = 1). When I attempt to download the photo without reconnecting I get an RPC error `The file to be accessed is currently stored in a different data center`

**Comment by Lonami** [comment] 2017-05-02 11:27
> What version are you using?

**Comment by gtavasoli** [comment] 2017-05-02 11:34
The last version `0.8`

```
>>> from telethon import TelegramClient
>>> print(TelegramClient.__version__)
0.8
```

**Comment by nicorac** [comment] 2017-05-05 07:43
Same here: logged in to DC#4 and trying to download a media (stored in DC#1)

```
output = self.download_msg_media(
    media,
    file_path=filename,
    progress_callback=self.download_progress_callback
)
```
I get this error:
```
[18:51:17.612/UpdatesThread] WARNING: Read RPC error: (RPCError(...), 'The file to be accessed is currently stored in a different data center (#1).')
```
Since it's a warning the download should proceed and, as long as I understand, Telethon should reconnect to the correct DC to download the media.
But the program hangs (on `self.download_msg_media()` call) and a 0 bytes file is saved.

I need to kill it (CTRL+C) and, when I restart it I get this errors:
```
[18:53:36.140/MainThread] WARNING: Read RPC error: (RPCError(...), 'The key is not registered in the system.')
Exception during automation process:  (RPCError(...), 'The key is not registered in the system.')
```
The only way to fix everything is to delete the session file and reauthenticate again, but downloading the same file restarts the whole loop from the beginning.

My 2 cents:
- Telethon user login happens on DC#4 then, upon media download failure, it switches to DC#1; the switch should be **temporary** and the new DC should not be stored into session file, otherwise at restart the next login will be attempted to the wrong DC
- DC switch fails for some reason and Telethon hangs just after creating the downloaded (empty) file.
I'm not a Python guru so I can't find where Telethon manages the FILE_MIGRATE_X response received when the media is stored in a different DC, but it seems that the authorization to the new DC is not based to the current one (https://core.telegram.org/api/datacenter#authorization-transfer), so it hangs

**Comment by nicorac** [comment] 2017-05-05 10:55
>> the switch should be temporary and the new DC should not be stored into session file

> That's a great idea.

Since this often happens with `download_x()` calls, if the download could be *sandboxed* into its own thread (together with DC details and stuff) the call could complete asynchronously without the main thread being locked waiting for the download to complete.

But this is something I can (try to) do externally within `download_x()` caller ;)

**Comment by Lonami** [comment] 2017-05-05 10:58
> if the download could be *sandboxed* into its **own thread** (together with DC details and stuff) the call could complete asynchronously without the main thread being locked waiting for the download to complete.

Yes, I was totally thinking about that too - but first we need to get this working :)

If it does happen to work, we could potentially keep two separate connections since *now* they're indeed connected to **different** addresses, and one could work for updates while the other could be used on the main thread (!). But first things first, let's test this.

> But this is something I can (try to) do externally within `download_x()` caller ;)

It would definitely be more powerful if Telethon itself handled 2 connections itself (maybe even one per data center, and those which are unused for a long time, could be self-closed, self-terminated).

**Comment by Lonami** [comment] 2017-05-05 12:02
@nicorac I tried with little success, because #7 occured.

**Comment by nicorac** [comment] 2017-05-05 12:17
> I tried with little success, because #7 occured.

Me too, but I didn't want to put a lot of things on the table.
The workaround I've found is to repeat `delete session + restart program` over and over till it works.

**Comment by Lonami** [comment] 2017-05-05 12:18
> The workaround I've found is to repeat `delete session + restart program` over and over till it works.

Not a nice UX though. I will push what I made to a new branch and let you know, if you want to take a look and/or help.

**Comment by Lonami** [comment] 2017-05-05 12:22
> The workaround I've found is to repeat `delete session + restart program` over and over till it works.

Not a nice UX though. I will push what I made to a new branch and let you know, if you want to take a look and/or help.

**Edit*: New branch is [`multiple-connections`](https://github.com/LonamiWebs/Telethon/tree/multiple-connections).

**Comment by nicorac** [comment] 2017-05-05 13:12
I'm actually receiving a [FLOOD_WAIT_X](https://core.telegram.org/api/errors#error-example) error just after the code request:
`FLOOD_WAIT_X: A wait of 22591 seconds is required.`

Will test it tomorrow... :(

**Comment by Lonami** [comment] 2017-05-05 13:15
> I'm actually receiving a [FLOOD_WAIT_X](https://core.telegram.org/api/errors#error-example) error just after the code request:
`FLOOD_WAIT_X: A wait of 22591 seconds is required.`

That's one of the caveats of testing login-related bugs (don't worry, it's happened *a lot* to me too)

**Comment by nicorac** [comment] 2017-05-05 18:52
The login issue seems to be ok, no more connection to the wrong DC when restarting the client.

I've downloaded 2 files without issues, then I got this on the third.
The file was created empty and client exited with an error:
```
[...]
IMPORTING AUTHORIZATION
Exception in thread UpdatesThread:
Traceback (most recent call last):
  File "/usr/src/Telethon/telethon/telegram_client.py", line 180, in invoke
    self.sender.receive(request, timeout)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 151, in receive
    request)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 229, in process_msg
    return self.handle_rpc_result(msg_id, sequence, reader, request)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 359, in handle_rpc_result
    raise InvalidDCError(error)
telethon.errors.InvalidDCError: (RPCError(...), 'The file to be accessed is currently stored in a different data center (#1).')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 446, in updates_thread_method
    reader)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 236, in process_msg
    return self.handle_gzip_packed(msg_id, sequence, reader, request)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 385, in handle_gzip_packed
    request)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 259, in process_msg
    return self.handle_update(msg_id, sequence, reader)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 272, in handle_update
    handler(tlobject)
  File "./my_client.py", line 130, in UpdateHandler
    self.ParseMessage(message)
  File "./my_client.py", line 175, in ParseMessage
    output = self.download_document(media, file_path=filename, progress_callback=self.download_progress_callback)
  File "/usr/src/Telethon/telethon/telegram_client.py", line 724, in download_document
    progress_callback=progress_callback)
  File "/usr/src/Telethon/telethon/telegram_client.py", line 785, in download_file_loc
    GetFileRequest(input_location, offset, part_size))
  File "/usr/src/Telethon/telethon/telegram_client.py", line 233, in invoke
    result = new_sender.receive(import_request)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 147, in receive
    message, remote_msg_id, remote_sequence = self.decode_msg(body)
  File "/usr/src/Telethon/telethon/network/mtproto_sender.py", line 198, in decode_msg
    raise BufferError("Can't decode packet ({})".format(body))
BufferError: Can't decode packet (b'l\xfe\xff\xff')
```

**Comment by Lonami** [comment] 2017-05-05 18:55
> Maybe a cross-thread issue?

Doubt so, I mean, this happened before. It's related to #7. And I don't know why we get a '-404'. The session is not corrupt (is it?), and I don't know what can be causing this error… But at least using this new sender it doesn't corrupt the original session so it's easier to test. If you would like to debug the changes to your session, see if you can troubleshoot something, you can add this to the `Session` class:
```python

    def __setattr__(self, key, value):
        print('UPDATING "{}" FROM "{}" TO "{}"'.format(key, getattr(self, key, None), value))
        super().__setattr__(key, value)

```

But I don't know why it happens :(

**Comment by Lonami** [comment] 2017-05-30 08:15
Both:

> The key is not registered in the system.

and:

> ```
> BufferError: Can't decode packet (b'l\xfe\xff\xff')
> ```

Are being worked on #53. Once downloading media from a different DC works, the `b'l\xfe\xff\xff'` packet won't be received anymore (it's caused by a corrupt authorization). Closing this issue to clean up the issues section.

**Closed by Lonami** 2017-05-30 08:15 UTC
