### ISSUE TITLE
Client doesn't get content from a channel with resctricted saving content enabled.

### ISSUE THREAD

**Issue by umatrix81** [LonamiWebs/Telethon#3265] opened 2022-01-03 12:34 UTC
If a channel has "Restrict saving content" enabled, then `event.message.message` is empty `message=''` and media is `media=MessageMediaUnsupported()`

**Comment by LightCannon** [comment] 2022-01-03 15:22
Same problem occurs with me and I cannot find any workaround it.

**Comment by jorgeoa** [comment] 2022-01-03 15:44
Same problem here. I hope the Telegram API allow retrieving this type of messages...

**Comment by mohinderq** [comment] 2022-01-03 16:16
Unfortunately I do have the same problem.

**Comment by ArthurTimmermans** [comment] 2022-01-03 16:28
Same problem ^^

**Comment by kshubham506** [comment] 2022-01-03 16:36
Check this thread : https://github.com/LonamiWebs/Telethon/issues/3261

**Comment by mohinderq** [comment] 2022-01-03 17:06
> Check this thread : #3261

I can confirm this is a working solution for now. Thank you! <3

**Comment by Lonami** [comment] 2022-01-03 22:56
Likely a duplicate of #3264.

**Closed by Lonami** 2022-01-03 22:56 UTC

**Comment by snowman** [comment] 2022-09-03 01:39
Simply upgrading to the latest version works for me:

```sh
$ pip install --verbose -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade telethon
$ pip show Telethon
Name: Telethon
Version: 1.25.0
Summary: Full-featured Telegram client library for Python 3
Home-page: https://github.com/LonamiWebs/Telethon
Author: Lonami Exo
Author-email: totufals@hotmail.com
License: MIT
Location: /home/w7/.local/lib/python3.10/site-packages
Requires: pyaes, rsa
Required-by:
```

**Comment by afterdelight** [comment] 2022-09-11 20:37
yes, it was fixed in version 1.25.0!! Thanks!!!

**Comment by Robertefendi02** [comment] 2022-12-27 06:18
Are there any updates on how to forward media from a restricted channel? I have no problem forwarding a text message, but not images/videos.

**Comment by kshubham506** [comment] 2022-12-27 06:21
you will have to explicitly download the media and then send it, [ send the message like usual - if it throws `RESTRICTED_EXCEPTION` - download the media and call api again with file param as the input ]

**Comment by Robertefendi02** [comment] 2022-12-27 06:44
Could you please provide some guidance or recommendation on how to download the media? Thanks

**Comment by Robertefendi02** [comment] 2022-12-27 07:04
> you will have to explicitly download the media and then send it, [ send the message like usual - if it throws `RESTRICTED_EXCEPTION` - download the media and call api again with file param as the input ]

Could you please provide some guidance or recommendation on how to download the media? Thanks

**Comment by kshubham506** [comment] 2022-12-27 07:17
the `.download_media` method [available in telethon](https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.downloads.DownloadMethods.download_media)

**Comment by Lonami** [comment] 2022-12-28 21:34
> you will have to explicitly download the media and then send it, [ send the message like usual - if it throws `RESTRICTED_EXCEPTION` - download the media and call api again with file param as the input ]

Would you be able to provide the full error (including exact `ERROR_TEXT`, request that caused it, and code)? This way I could add it to [`errors.csv`](https://github.com/LonamiWebs/Telethon/blob/v1/telethon_generator/data/errors.csv). Thanks!

**Comment by Robertefendi02** [comment] 2022-12-28 22:23
> > you will have to explicitly download the media and then send it, [ send the message like usual - if it throws `RESTRICTED_EXCEPTION` - download the media and call api again with file param as the input ]
> 
> Would you be able to provide the full error (including exact `ERROR_TEXT`, request that caused it, and code)? This way I could add it to [`errors.csv`](https://github.com/LonamiWebs/Telethon/blob/v1/telethon_generator/data/errors.csv). Thanks!

I used the above recommendation ".download_media method [available in telethon]" in my own code and it worked. After using "try and except e:" I got this error "(caused by SendMediaRequest)". Is there a way to determine if this message was sent from a restricted channel? Is there any type of tag available in event. message which show the message was send from restricted channel?
