### ISSUE TITLE
Telethon update username and name

### ISSUE THREAD

**Issue by saarmia123** [LonamiWebs/Telethon#1440] opened 2020-04-20 20:38 UTC
Been trying to auth and than update username and name from a random txt file... seems like theres an error with the await...

from telethon import TelegramClient
from telethon.tl.functions.messages import GetDialogsRequest
from telethon.tl.functions.account import UpdateProfileRequest
from telethon.tl.functions.account import UpdateUsernameRequest
import random
from os import path
from telethon import functions, types
import sys
import csv
import traceback
import time
import signal
import requests
import pynput
import asyncio

  

api_id = 569194
api_hash = 'baa712364f25b56aa2468be7e94132b6'
file = open("number.txt").readlines()
proxies = open("proxies.txt").read().split("\n")
print(proxies)
while True:
    phone = input("Enter Number with CountryCode: ")
    if path.exists(f"{phone}.session"):
        print("Already Saved Session..")
    else:
        proxy = random.choice(proxies)
        p = {"hostname":proxy.split(":")[0],"port":int(proxy.split(":")[1])}
        print(p)
        print(phone)
        with TelegramClient(phone, api_id, api_hash) as client:
        if not client.is_user_authorized():
            client.send_code_request(phone)
            client.sign_in(phone, input('Enter the code : '))
        else:
            file = open("firstnames.txt").readlines()
            reader = csv.reader(file)
            nrow = random.choice(list(reader))
            file2 = open("usernames.txt").readlines()
            reader2 = csv.reader(file2)
            urow = random.choice(list(reader2))        
            await client(functions.account.UpdateProfileRequest(first_name=nrow ))
            await client(UpdateUsernameRequest(urow))

**Comment by saarmia123** [comment] 2020-04-20 20:42
Please ignore the  random proxy part

**Comment by Lonami** [comment] 2020-04-20 22:15
You didn't actually indicate what the issue is. Because I believe there is no bug, I will close the issue. If there's a bug please post the **issue in the library** (not in your code) and I'll reopen.

**Closed by Lonami** 2020-04-20 22:15 UTC
