### ISSUE TITLE
send_read_acknowledge doesn't work for megagroup

### ISSUE THREAD

**Issue by VYBIG** [LonamiWebs/Telethon#4383] opened 2024-05-28 07:59 UTC
### Code that causes the issue

@client.on(events.NewMessage(incoming=True))
async def mark_archived_dialogs_as_read(event):
    async for dialog in client.iter_dialogs(archived=True):
        if event.message.message == dialog.message.message:
            if isinstance(event.peer_id, types.PeerChat):
                await client.send_read_acknowledge(entity=event.message.peer_id.chat_id,
                                                   max_id=event.message.id,
                                                   clear_mentions=True,
                                                   clear_reactions=True,
                                                   )
            elif isinstance(event.peer_id, types.PeerChannel):
                await client.send_read_acknowledge(entity=event.message.peer_id.channel_id,
                                                   max_id=event.message.id,
                                                   clear_mentions=True,
                                                   clear_reactions=True,
                                                   )

### Expected behavior

I have some function for marking archived dialogs as read in my telegram account, it is marking archived dialogs as read, if it is common group

### Actual behavior

This function work for common groups, but doesn't work for mega groups and there is no any error message 

### Telethon version

1.35.0

### Python version

3.11

### Operating system (including distribution name and version)

any

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment] 2024-05-28 13:11
If you believe the implementation is wrong, please call the raw API directly, and let me know what the correct method and parameters are:

https://github.com/LonamiWebs/Telethon/blob/47673680f4f615aac15d7e8c1886abea2fe40d9e/telethon/client/messages.py#L1310

As far as I can see, the implementation for both is almost identical. So I will close this assuming the problem is Telegram's, not Telethon's.

**Closed as completed by Lonami** 2024-05-28 13:11 UTC
